### ISSUE TITLE
In order to ensure that icons load consistently and quickly across platforms and browsers, decide what the best front end approach for loading icons is.

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#1]
Do we want to do SVG sprites as suggested here? https://css-tricks.com/svg-sprites-use-better-icon-fonts/

**Comment by noahmanger** [comment]
@msecret what are your thoughts on this? We're going to have a lot of  svg icons.

**Comment by andrewmaier** [comment]
:popcorn:

**Comment by msecret** [comment]
I'd suggest svg sprites that are automatically generated. So we'll have an svg directory that gets combine into the sprite. Are there svg libraries that we'd use? Thats more from the design side.

**Comment by noahmanger** [comment]
Pretty sure they're all going to be custom. Do you have a preferred method
of generating an svg sprite?

On Fri, Aug 21, 2015 at 10:58 AM, Marco Segreto <notifications@github.com>
wrote:

> I'd suggest svg sprites that are automatically generated. So we'll have an
> svg directory that gets combine into the sprite. Are there svg libraries
> that we'd use? Thats more from the design side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/issues/1#issuecomment-133513134>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
This isn't launch critical, and will be better solved by @msecret. So I'm moving this out of the backlog for now.

**Comment by noahmanger** [comment]
https://18f.storiesonboard.com/m/fec/!card/X8qV-96qTN7j5DnUEHzR2Q

**Comment by noahmanger** [comment]
We resolved this with our switch to data URI icons.
