### ISSUE TITLE
Minor contrast fail

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#106]
![screen shot 2015-09-22 at 2 05 28 pm](https://cloud.githubusercontent.com/assets/1696495/10031620/310a2628-6133-11e5-8c42-34b124dc60d0.png)

The #ffffff on #DD3900 is failing (4.48:1). Not a huge deal, but we should adjust.

**Comment by jenniferthibault** [comment]
Let's move to #fffff9 and #dd3700 I don't think there should be any #ffffff
