### ISSUE TITLE
To present a consistent style, use double- or single-quotes consistently.

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#144]
While merging #143, I noticed that we have a mixture of single- and double-quotes in our definitions. We also seem to have some smart quotes / apostrophes and some ascii quotes. Let's pick a preferred style and stick with it throughout (including our other repos).

cc @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Ah. Smart catch. It won't mess up our glossary if I put double quotes inside the quotes?

**Comment by jmcarp** [comment]
It won't if we escape double-quotes with backslashes: "52 U.S.C. 30118 allows \"communications by a corporation...".

**Comment by emileighoutlaw** [comment]
Ah great. I'll go in and make consistent now.
