### ISSUE TITLE
To help readers clarify the purpose of "Registration and reporting" pages, rework header and button content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-style#180]
## Needs addressing
 - Make the button text and headlines more specific; "discover" and "explore" are too vague.
<img width="1177" alt="screen shot 2015-11-12 at 12 21 37 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130096/05a28f34-8938-11e5-9abd-b712354d4d9c.png">
<img width="425" alt="screen shot 2015-11-12 at 12 23 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130116/2ed1a3ae-8938-11e5-9650-cffea9d1aca1.png">
<img width="357" alt="screen shot 2015-11-12 at 12 23 13 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130117/2ed7414c-8938-11e5-97b0-bf4c757371a0.png">  

## Google doc
[Draft of new language](https://docs.google.com/document/d/1ZOnGy1bnVEJmvaR-M8JR_7Y9PHNjUCfQD0vLSawguYg/edit)

## Related issues:
- https://github.com/18F/fec-cms/issues/19#issuecomment-142363805
- This issue addresses the content-specific sections of 18F/fec-style/issues/176

**Comment by emileighoutlaw** [comment]
Put together some thoughts on the content! Would love your take, @jenniferthibault @noahmanger: 

https://docs.google.com/document/d/1ZOnGy1bnVEJmvaR-M8JR_7Y9PHNjUCfQD0vLSawguYg/edit#heading=h.no6ftpfsn8bv

**Comment by jenniferthibault** [comment]
This is stellar @emileighoutlaw — comments in the doc, but point for discussion here. With these new edits, it looks like we may not even NEED that button in the hero area. That leaves our heroic hero a bit weak, but I'm wondering if we'll learn what purpose it could serve as this section of the site fleshes out and we get more user feedback about what they want from that page. 
So...remove the button, do usability testing on the page, then fill the hero section with what users need to learn more about in a later iteration. :question:

**Comment by emileighoutlaw** [comment]
Yes! I agree that we could eliminate the hero button. Let's go with it!

**Comment by jenniferthibault** [comment]
I'm still working through the layout of the essentials pages, but here's the mockup of what the combined landing page & registration options page could be like. Gotta say, I'm really liking having the info on one page instead of two.

I'm imagining the table of contents-like thing in the second half of the screen would be sticky so that users can easily get between sections on the page, since the content will get quite long once it's all in place. 

(Content on Nonconnected committees and political party committees is for placement only)

![registration home 2 copy 3a](https://cloud.githubusercontent.com/assets/11636908/11346280/dc8a9974-91e9-11e5-8b7b-640b29cfe20e.png)

@emileighoutlaw / @noahmanger thoughts?

**Comment by emileighoutlaw** [comment]
Oh yeah. I think the incorporation of all this onto one page is really cool. I *love* having the campaign guide linked where it is here. 

I'm also curious to see this style in testing — I have a small, gut concern that people are so used to looking to the campaign guides for information that they'll click on them automatically and miss the "Get started" button.

**Comment by jenniferthibault** [comment]
Helpful gut preview! I semi-shared that concern and hoped that making the title of each section a clickable link to their essentials page would make that the first target, then the button would be a backup option. 

I'll wait for testing, but I can easily give the guides less visual priority to avert some attention from them.

**Comment by emileighoutlaw** [comment]
Sounds great!

**Comment by jenniferthibault** [comment]
Moving to implementation in #192 !
