### ISSUE TITLE
Implement design changes from review of Registration & Reporting side

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#183]
Based on #176, implement the following changes: 

### Universal changes
 - [x] Change body copy to 1rem = 16pt throughout the site, **except for** any table copy. This will help in cases where character count per line is currently too large for ideal readability but also...
 - [x] Limit paragraph text to 3/4 columns wide at max:

This
<img width="1279" alt="screen shot 2015-11-12 at 12 51 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130868/479b09a8-893c-11e5-9150-fdd05e7ac837.png">

instead of this:
<img width="1280" alt="screen shot 2015-11-12 at 12 52 53 pm" src="https://cloud.githubusercontent.com/assets/11636908/11130878/554fef3c-893c-11e5-8a8c-27234affa996.png">

### Changes to Essentials page templates:
<img width="1279" alt="screen shot 2015-11-12 at 1 05 10 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131164/18c52f4e-893e-11e5-9cf3-764a4590a773.png">
 - [x] Remove top rule line from H1's 
 - [x] Increase space between bottom of H1 rule and body copy @jenniferthibault to mockup
 - [x] Put at least 1 column of space between edge of body copy content and resources panel on the right @jenniferthibault to mockup
 - [x] Increase space between bottom H1 rule line and top of resources box @jenniferthibault to mockup
 - [ ] Originally, this was our design for the resources panel: why did we move away from this, and do we want to bring this back as "Coming soon" content? cc @noahmanger 

<img width="238" alt="screen shot 2015-11-12 at 1 14 57 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131401/7b69de5a-893f-11e5-96c6-0212f3e570c6.png">

 - [x] Consider removing accordion functionality in favor of lists that are shorter than most users might assume. The content is surprisingly short! - @jenniferthibault for mockups
 - [x] Depending on ^ change checkboxes to bullets - @jenniferthibault

<img width="265" alt="screen shot 2015-11-12 at 1 19 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131537/fa7c9c5a-893f-11e5-9e3d-1d32f5d2287f.png">

 - [x] Add link and `PDF` to campaign guide to match original design.
Second paragraph [here](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/)

<img width="327" alt="screen shot 2015-11-12 at 1 20 02 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131580/3780f5d8-8940-11e5-9c5e-3d957bbbe559.png">

 - [x] Another place we deviated from the design was having the "Need help?" as an element at the end of the page, but above the footer. Do we want to bring this back, complete with "Coming soon" content elements? cc @noahmanger 
<img width="851" alt="screen shot 2015-11-12 at 1 22 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131675/abc326c8-8940-11e5-9bce-d60203ed9502.png">

### Changes to individual articles/page templates:
<img width="1278" alt="screen shot 2015-11-12 at 1 26 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/11131757/196b8652-8941-11e5-8187-6095957b4461.png">
 - [x] Remove top rule line from H1's 
 - [x] Reconsider title line-length caps
 - [x] Same spacing changes between content and resources box as Essentials pages

Glad to talk though anything as we go!

**Comment by jenniferthibault** [comment]
Here's a rough layout of the adjustments for the spacing issues from above on the Essentials and individual article pages:

![screen shot 2015-11-17 at 2 47 17 pm](https://cloud.githubusercontent.com/assets/11636908/11222762/66b5fc2e-8d3a-11e5-8f5a-4ebd2da22b46.png)

**Comment by noahmanger** [comment]
Setting the body copy to 16px, do you want to also bump heading sizes up too?

**Comment by noahmanger** [comment]
This is coming along nicely:

![image](https://cloud.githubusercontent.com/assets/1696495/11259528/2627ca1a-8e17-11e5-91bb-5484f6091097.png)

![image](https://cloud.githubusercontent.com/assets/1696495/11259539/3d62c694-8e17-11e5-8ff0-08f65cee4bf3.png)

The sub-heading size looks a little weird with the new bigger body size though.

Also, the max-width of the container was set to 68em, and so adjusting body font size bumped that up so it's wider, which I think makes sense. It's now 1088px wide vs 952px before.

**Comment by jenniferthibault** [comment]
OOOOH! I'm going to set up a real short pairing session on the header size and container-width (+anything else that came up) this afternoon. 
I think we may actually want to decrease the container max-width to closer to what it was before, but would love to talk that out together.
