### ISSUE TITLE
Implement redesign for Registration and Reporting home

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#192]
Story map card: [Candidate committees can find out how to register](https://18f.storiesonboard.com/m/fec/!card/4sHk8_8fF-AnQTnTwqtsBA)

Design reviews in https://github.com/18F/fec-style/issues/180#issue

Partial new content in [this Google Doc](https://docs.google.com/document/d/1ZOnGy1bnVEJmvaR-M8JR_7Y9PHNjUCfQD0vLSawguYg/edit#heading=h.no6ftpfsn8bv)

Desktop designs with linking & interaction notes: 
![registration home 2 copy 3](https://cloud.githubusercontent.com/assets/11636908/11409121/c5be37ac-938b-11e5-932c-e0860b2a03d3.png)

Mobile designs to come!

**Comment by jenniferthibault** [comment]
Grids & guides for reference:

![screen shot 2015-11-25 at 3 51 29 pm](https://cloud.githubusercontent.com/assets/11636908/11409242/7d2f068c-938c-11e5-8e2d-6cd86d18b571.png)
![screen shot 2015-11-25 at 3 51 40 pm](https://cloud.githubusercontent.com/assets/11636908/11409243/7d3495ca-938c-11e5-87b8-aae053ca0cb0.png)

**Comment by noahmanger** [comment]
Small question: what heading style is the "Campaign Guide" headings above each thumbnail image?

**Comment by noahmanger** [comment]
Another question: the dark orange cards with the light text aren't high enough contrast. What would you prefer?

**Comment by jenniferthibault** [comment]
It's the same font, size, and weight as the headings in the filter bars for the data browse page, and table headers: (Karla, Bold, uppercase, 1.4 or 1.6 rem, I think)

<img width="295" alt="screen shot 2015-12-01 at 10 10 36 am" src="https://cloud.githubusercontent.com/assets/11636908/11504539/dfd72b4e-9813-11e5-8f0e-3342d94c45e8.png">

We might have this as h4 or h5?

On the colors, I was using #FFFFFF and red/orange #DD3A00
My Sketch plugin said it passed, but I just double-checked it on a different tool, and it's coming up as 4.49:1, so the plugin must have rounded.
Let's change that red/orange to #DC3A00, which makes the contrast with white 4.52:1

Thank you!

**Comment by noahmanger** [comment]
Cool, thanks!
