### ISSUE TITLE
Implement redesign of Article page template

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#194]
Story map card: [Candidate committees can find out how to register](https://18f.storiesonboard.com/m/fec/!card/4sHk8_8fF-AnQTnTwqtsBA)

Discussion in https://github.com/18F/fec-style/issues/176

Mobile designs to come!

Desktop designs with linking & interaction notes: 

![knowledge center item](https://cloud.githubusercontent.com/assets/11636908/11409380/84c60264-938d-11e5-8a94-ec1fb89fbf0f.png)

Grids & guides for reference:
![screen shot 2015-11-25 at 4 00 05 pm](https://cloud.githubusercontent.com/assets/11636908/11409395/a13bbd44-938d-11e5-90ce-1f13e48fd3ec.png)

**Comment by jenniferthibault** [comment]
@noahmanger here's what it could look like with the article titles included, but ellipsed at the length of the button:

![screen shot 2015-12-02 at 3 14 32 pm](https://cloud.githubusercontent.com/assets/11636908/11542889/be82a3d4-9907-11e5-8082-a0fc91775e8b.png)

If creating a new text style at this point isn't crazy, I'd like to have the article title text be a bit smaller. I have it at 12pt here, so could we try either 1.2rem or 1.4rem ? That way it acts as more of a detail, and we can fit slightly more of the title copy in before the ellipse.

**Comment by noahmanger** [comment]
This has been mostly implemented, but has two separate remaining tasks captured here:

- Implement the new sidebar content https://github.com/18F/fec-cms/issues/136
- Figuring out breadcrumb nav stuff https://github.com/18F/fec-cms/issues/144

Before figuring out the breadcrumb stuff, I need to:
- [ ] Remove the next / previous buttons after testing for the time being
