### ISSUE TITLE
So that users have a consistent experience, build an interaction pattern for filtering and filter tag instances

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#204]
We're starting to see a pattern emerge in the calendar and in data browse tables that would benefit from intentionally designing an interaction pattern. The two are close now, but could match up more tightly.

Calendar designs: https://github.com/18F/fec-cms/issues/117

Filter tags: https://github.com/18F/openFEC-web-app/issues/754 

[Candidate browse view](https://beta.fec.gov/data/candidates/?cycle=2012&cycle=2014&cycle=2016)
[Committee browse view](https://beta.fec.gov/data/committees/?cycle=2012&cycle=2014&cycle=2016)
[Filings browse view](https://beta.fec.gov/data/filings/)
[Receipt browse view](https://beta.fec.gov/data/receipts/?is_individual=true&max_date=12-10-2015)
[Disbursement browse view](https://beta.fec.gov/data/disbursements/?max_date=12-10-2015)

**Comment by jenniferthibault** [comment]
Pending feedback on the interactions proposed in https://github.com/18F/openFEC-web-app/issues/754#issuecomment-164934879

Here are some templates that flesh out individual elements and layouts across applications (currently Data browse views and the FEC calendar):

![filter patterns](https://cloud.githubusercontent.com/assets/11636908/11829689/6a2edffe-a36c-11e5-800b-89fc18c1db07.png)

![filter tag patterns](https://cloud.githubusercontent.com/assets/11636908/11829743/de4adf78-a36c-11e5-9186-7f48ef8b23c7.png)

@noahmanger I could use your eagle eye on other filter interactions that we could define. I've been basing the current off of [this Google spreadsheet](https://docs.google.com/spreadsheets/d/1-LjKQy3dOJI9FJmrhNEfgsr-uD7HzzH0qf1zpo3azTE/edit#gid=0)

**Comment by noahmanger** [comment]
Looking really great. Just to capture my notes from the call just now:
- I like the idea of grouping filters related to similar information in a single accordion item, but we should figure out what the rule is for when multiple filters are in a single accordion vs each in their own
- We currently have two kind of text-based inputs for filters: typeahead filters and regular text inputs. Typeahead filters produce a checkbox filter (and allow the creation of multiple checkbox options). Text filters do not. We need to figure out if we want them to behave more similarly, and if not, they should look visually distinct. [You can see more thinking and tinkering here](https://github.com/18F/openFEC-web-app/issues/982)
- How do you think color coding for the regular browse filters would work? Where else would the color be visible?

**Comment by jenniferthibault** [comment]
- Filter grouping: We need to do some content design in this area (pinging @emileighoutlaw as a heads up for work down the line) I started to do **some** thinking into this in the spreadsheet attached above, but I think we'd do well to think about how filter areas could be grouped.
- I don't think I can answer the question without research backing up behavior, but agree on the principal that if we have 2 that ACT differently, they should LOOK different
- I think color coding would only be applicable to the calendar so far. I haven't come across another scenario in browse tables with a need to color code anything

**Comment by emileighoutlaw** [comment]
Yes! Thrilled to jump in on content design, whenever you think I'd be most helpful :)

**Comment by noahmanger** [comment]
I had a thought on this: if there are no tags present, do we want to say something like "Viewing all records" or something?

**Comment by noahmanger** [comment]
Also, transfering to me for implementation (which is almost done)

**Comment by jenniferthibault** [comment]
Showing "Viewing all records) would make sense to me

**Comment by emileighoutlaw** [comment]
Makes sense to me too

**Comment by noahmanger** [comment]
Remaining task on this is to review and merge:
- [ ] https://github.com/18F/openFEC-web-app/pull/1015
- [ ] https://github.com/18F/fec-style/pull/213

@ccostino let me know if you want to talk through 1015. It's kinda gnarly, but not as bad as it looks.

**Comment by ccostino** [comment]
Just to follow up on this issue, I had completed reviewing #213 (which is now merged) and @jmcarp and @noahmanger took over the review of 18F/openFEC-web-app#1015 (which is also merged) - I took a quick look over it as well just to gain more familiarity with things and didn't see anything wrong while reading it over.
