### ISSUE TITLE
Typeahead filters allow repeated values

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#219]
<img width="280" alt="screen shot 2016-01-04 at 11 50 42 am" src="https://cloud.githubusercontent.com/assets/1633460/12094919/7c681f92-b2d9-11e5-9cf6-e6627e535269.png">

We should either exclude results that already have checkboxes from typeahead search results, or just not duplicate already-existing checkboxes on typeahead select. This should probably be done either after or as part of #213 to avoid conflicts.

**Comment by noahmanger** [comment]
Resolved in this release.
