### ISSUE TITLE
Fix minor z-index and toggle issues on calendar event tooltips

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#220]
Already talked about this with @noahmanger--just filing since I'm liable to forget, and in case others have thoughts. This applies to #213, not master.

* Event tooltips appear underneath other widgets in the calendar interface, like event markers and day numbers. They're also obscured if they fall outside the calendar widget itself.
* I'm wondering if we should only show one event tooltip at a time--when we show several, they can overlap and make each other hard to close.

cc @jenniferthibault 

<img width="680" alt="screen shot 2016-01-06 at 10 16 14 am" src="https://cloud.githubusercontent.com/assets/1633460/12145967/30207a76-b45f-11e5-95aa-a4c55da7da63.png">

**Comment by jenniferthibault** [comment]
Your instinct is right on to me @jmcarp - if a user has one event toggle open, that one should close if they select another event without closing the previous one themselves.

**Comment by noahmanger** [comment]
This is now implemented.
