### ISSUE TITLE
Calendar table elements occlude events, buttons

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#224]
The weekly calendar view includes seven `<td>` elements that prevent clicking on some events, as well as the navigation buttons above the calendar. It looks like this issue either comes from not using the styles provided by fullcalendar, or was introduced by our custom styles.

**Comment by noahmanger** [comment]
Ugh, yeah the way they do the markup for this view is kind of a pain. I'll look into it.

**Comment by noahmanger** [comment]
Resolved in upcoming PR https://github.com/18F/fec-style/pull/213
