### ISSUE TITLE
Calendar/data filter tag style corrections

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#229]
When I was styling the calendar filter elements, I must have inadvertently restyled a common element that affected the data filter tag. @noahmanger could I beg your help to fix my frankenstyle before this goes out to production?

"All records" should be aqua here, but remain orange on the calendar side

<img width="558" alt="screen shot 2016-01-25 at 6 00 30 pm" src="https://cloud.githubusercontent.com/assets/11636908/12567615/0f7caac2-c38e-11e5-8895-397900129da8.png">

Ideally, one styling I couldn't find out where to control was the "apply filters" button on the calendar side. Could we make this button match the crimson/orange pairing for the calendar color scheme? Button should be crimson, text should be orange. 

<img width="572" alt="screen shot 2016-01-25 at 6 00 45 pm" src="https://cloud.githubusercontent.com/assets/11636908/12567652/5d64573a-c38e-11e5-933e-5496a1b16108.png">

**Comment by jenniferthibault** [comment]
Apologies, a further correction. Here's what I intended my style patch to do in the first place, and are the ideal text color combos. The intention is that the cream-colored "All records" text is replaced by cream-colored tags when they are applied.

<img width="254" alt="screen shot 2016-01-25 at 6 09 51 pm" src="https://cloud.githubusercontent.com/assets/11636908/12567761/143a2f70-c38f-11e5-856c-26da10dfb80d.png">
<img width="187" alt="screen shot 2016-01-25 at 6 10 59 pm" src="https://cloud.githubusercontent.com/assets/11636908/12567762/143dc52c-c38f-11e5-8f13-60ef512b9e57.png">

**Comment by noahmanger** [comment]
Got it! Was just starting to look at this.

**Comment by noahmanger** [comment]
Resolved in an upcoming PR.
