### ISSUE TITLE
Safari typeahead bug

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#230]
Noticed this Safari bug on the typeahead filters (currently [on production](https://beta.fec.gov/data/receipts)

<img width="301" alt="screen shot 2016-01-26 at 3 40 46 pm" src="https://cloud.githubusercontent.com/assets/1696495/12599048/8a3e70aa-c443-11e5-84e6-6a101e50a65c.png">

I see in the code that it's creating multiple typeahead divs, but I can't figure out why. @jmcarp can you take a look? I'm only seeing it in Safari (mobile and desktop). Firefox and Chrome are fine.

<img width="870" alt="screen shot 2016-01-26 at 3 41 36 pm" src="https://cloud.githubusercontent.com/assets/1696495/12599058/9e4d1b82-c443-11e5-9813-e23eb9d87ff1.png">

**Comment by jmcarp** [comment]
I did some reworking of the typeahead filters in https://github.com/18F/fec-style/pull/231, and I didn't see this weirdness in Safari on that branch--things do look funky on develop, though. If this can wait until we have the typeahead consolidation ready, I think it'll get solved for free then--if not, I can figure out which specific changes in that patch fixed this bug and send a hotfix.

**Comment by noahmanger** [comment]
Cool. Yeah, that's fine with me. Let's try to get that sorted out and merged in to fec-style for the release next week.

**Comment by jenniferthibault** [comment]
Also reported (and I verified) on mobile for Receipts, Disbursements, and IEs. I'm using Chrome

**Comment by noahmanger** [comment]
This is resolved in the release.
