### ISSUE TITLE
Upgrade to latest typeahead.js version

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#232]
Note: I'm pretty sure I filed more or less the same issue a while back, but I'm not sure where it went--likely in another repo, and closed by now.

We're currently using typeahead.js version 0.10.5, but the latest version is 0.11.1. Some features have changed between 0.10 and 0.11, which means that the current docs occasionally lead us astray. If I remember correctly some css classes may have also changed. I think it would be worth upgrading when time permits.

**Comment by noahmanger** [comment]
Do you think it makes sense to do this now while we're light on other dev stuff?
