### ISSUE TITLE
Review mobile styles for calendar

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#234]
Review and propose changes to calendar mobile view

**Comment by jenniferthibault** [comment]
@noahmanger I have a few questions about functionality based on your mockup:

![screen_shot_2016-01-28_at_11 28 05_am](https://cloud.githubusercontent.com/assets/11636908/12724717/3c0a8da8-c8dd-11e5-866d-356e8f21b6b4.png)

1. What's the functionality of the "Today" button? It seems like it would only be useful if that part of the navigation were fixed while the user scrolled the list below. 
2. This mockup doesn't show the event categories, is that intentional and we're going to user chronological order only? Or do we want to keep events grouped by type, then chronologically within each group, as we're doing in the current list view.
3. What increments of time are we looking at in this view?

**Comment by jenniferthibault** [comment]
@noahmanger here are the (partially polished) mockups we were just talking though. A few points we just talked about:
- use `|  ` in front of location to offset it, in "details" style typography (Karla)
- Move location to bottom of event details div, with a little margin on top to keep it separated
- move add to calendar dropdown to the right-most position for mobile and desktop
- add hrs between events in cream/beige, and between event groups in navy (mobile and desktop)
- on mobile, unstack subscribe/download buttons

![calendar_list](https://cloud.githubusercontent.com/assets/11636908/12734684/2b8cbbee-c910-11e5-93a0-48eb9d5ea111.png)

![calendar_list mobile](https://cloud.githubusercontent.com/assets/11636908/12734689/2fbd9652-c910-11e5-8e50-2b0b701b6176.png)

**Comment by noahmanger** [comment]
Ok, mostly done. I'm going to add the toggle between category grouping and chronological grouping here soon because it's easy. But other than that I think it's there:

![screen shot 2016-02-01 at 5 32 51 pm](https://cloud.githubusercontent.com/assets/1696495/12737010/f0174058-c909-11e5-9f5f-585e85300bb9.png)
![screen shot 2016-02-01 at 5 32 34 pm](https://cloud.githubusercontent.com/assets/1696495/12737009/f015a87e-c909-11e5-8e5e-450716fbdcf8.png)

Lemme know if you notice anything else.

**Comment by jenniferthibault** [comment]
Hmm. That pipe really isn't working well here. Sorry for the last switcharoo, but could we instead use a en dash followed by a space there instead to indent the line? A bit nontraditional, but I think it will bump it down a level of hierarchy just enough to be noticeably different. 

It won't look MUCH different here:
`– Mississippi` (en dash) vs
`- Mississippi` (hyphen)

but Karla's hyphens are a bit smaller (en dash top, hyphen bottom).
![screen shot 2016-02-01 at 10 33 40 pm](https://cloud.githubusercontent.com/assets/11636908/12739073/092f0a60-c934-11e5-968d-badd6313044e.png)

Other than that, which really isn't much, I think this came together nicely! Thanks for the great detail work, Noah.

**Comment by noahmanger** [comment]
This has been merged in.
