### ISSUE TITLE
Design loading state on tables

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#24]
We should have some sort of different visual state on the tables if data is loading. An overlay, a spinner, something. Currently it just says loading above (which was meant as a placeholder).

**Comment by jenniferthibault** [comment]
This screencap gets a little glitchy, but this is what I'm imagining as an overlay for the table, maybe centered at the top over a 70% opacity federal blue (#022C53) overlay, like so

<img width="559" alt="screen shot 2015-08-26 at 10 26 47 am" src="https://cloud.githubusercontent.com/assets/11636908/9496106/bd16159e-4bdc-11e5-886a-28cb05aceed7.png">


![loading1](https://cloud.githubusercontent.com/assets/11636908/9495903/c5b144ae-4bdb-11e5-806b-35b5cf1b01f0.gif)

@noahmanger is there a way to do this with SVGs that make the transition smoother? I have a clean transparent gif file, that I could send you of this animation, if not.

**Comment by noahmanger** [comment]
Oooh! I love it! Yep, we can definitely make it smoother, but it'd take a little work. Let's use the gif for now and then switch it later.

**Comment by jenniferthibault** [comment]
ok! The gif is below, but since it's white on transparent it won't be visible. You should be able to download it if you right-click.

![loading_icon1](https://cloud.githubusercontent.com/assets/11636908/9500841/bffb7312-4bf5-11e5-87c7-10ff8bced4a6.gif)
gif^

**Comment by jeremiak** [comment]
That is snazzy!

**Comment by leahbannon** [comment]
love this gif :)
