### ISSUE TITLE
Refine designs for typeahead filter

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#240]
- Design loading indicator for typeahead searches so that users can tell the typeahead exists and is preparing results
- Restyle placement for Committee IDs on name typeahead searches. Previous styles aren't feasuble due to space limitations. 

See existing designs https://github.com/18F/fec-style/pull/231#issuecomment-179376044

**Comment by jenniferthibault** [comment]
Waiting for a clear release to make improvements, so moving this back to the backlog

**Comment by noahmanger** [comment]
Closing in favor of openFEC #1672
