### ISSUE TITLE
Carry out discovery plan for understanding experience of betaFEC's visual design

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#241]
In order to understand if our visual design system is meeting the goals we set out for it, develop a discovery research plan to check in on it and redirect it while in flight.

**Comment by jenniferthibault** [comment]
[This is the Google document](https://docs.google.com/document/d/1OouA9iN10C420O2rKLkxQptQfcb-rSw_uZR4F-tAvk8/edit#heading=h.ej85ji9iw93k) I've been working in to think about how we should get feedback on the look and feel of betaFEC at this midway point in the project. Before we ramp up FEC Eregs too much, we're at a great point to check in and course-correct.

I'm looking for thoughts on if there are big red flags on any of the exercises I've proposed, or if any better ideas come to mind after seeing what I'm hoping to get from each. @brethauer @noahmanger @emileighoutlaw

**Comment by jenniferthibault** [comment]
Next up, I'll be updating this with something that looks very much like the workflow and calendar here: https://github.com/18F/openFEC-web-app/issues/1045#issuecomment-182582670

**Comment by jenniferthibault** [comment]
Alrighty, here's how the discovery activities in the G Doc above fit into a workflow for the next few weeks ahead of our workshop. This primarily influences my own work flow, but there is a meeting I'd like to set up with @noahmanger / @emileighoutlaw  next Weds to do an activity reflecting on "If I knew then what I know now, how would I have changed the style?" I'll go ahead and schedule that, but in the meantime, please do chime in if you see ways to improve anything.

![calendar copy](https://cloud.githubusercontent.com/assets/11636908/13014473/fad3c36a-d181-11e5-97e2-b93d64ea0470.png)

**Comment by noahmanger** [comment]
:+1: sounds good to me! Just re-read the research plan. So excited you're doing this.

**Comment by noahmanger** [comment]
Can we close this one too?

**Comment by jenniferthibault** [comment]
I think I'd rather just have one issue to track than many. Renaming it seems more efficient than closing this just to open others.

**Comment by noahmanger** [comment]
Do you still want to keep this open now that you've been making separate issues?

**Comment by jenniferthibault** [comment]
We can close it!
