### ISSUE TITLE
Finesse styling of filter and filter tag space

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#246]
Recommend style tweaks based on new accordion-wrapped filters

**Comment by jenniferthibault** [comment]
Related: https://github.com/18F/openFEC-web-app/pull/1092#issuecomment-182601962

**Comment by jenniferthibault** [comment]
@noahmanger I'm wondering if we disentangle the filter space from the subnav in this issue, could we move ahead with the redesigned filer style/placement/and interaction that we've been looking at on browse tables and the calendar? Since it touches the calendar design, this could be a this sprint activity if there's availability on your end.

Relevant to discussion of secondary nav here: https://github.com/18F/openFEC-web-app/issues/1088

**Filters open**

![all candidates copy 4](https://cloud.githubusercontent.com/assets/11636908/13854684/146b0a32-ec43-11e5-9ff9-1f1f8a512e0a.png)


**Filters closed**

![all candidates copy 3](https://cloud.githubusercontent.com/assets/11636908/13854695/263c54aa-ec43-11e5-8e11-fabc2017560b.png)

**Comment by noahmanger** [comment]
Good call. Yes, let's do that.

**Comment by jenniferthibault** [comment]
Awesome, ok so looking solely at the filter and filter tag space, this could be ready for implementation and I'm transferring the issue to you.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1161
