### ISSUE TITLE
So that colorblind users can tell events apart, distinguish event category by more than color: 508 conformance

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#251]
Part of https://github.com/18F/fec-cms/issues/207#issuecomment-188073934

<img width="1276" alt="screen shot 2016-02-24 at 9 56 41 am" src="https://cloud.githubusercontent.com/assets/11636908/13289135/ee3affc4-dadc-11e5-8b27-9125558dcc83.png">

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/256
