### ISSUE TITLE
Migrate fact tables from Data Warehouse to views

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-style#252]
For more timely updates and to move off the warehouse, Jeff, Jean and Rohan are going to make views from the FECP tables that replace the fact tables. This will provide reports that are named using the API conventions. 

Here are the fact tables that need to be created and the corresponding 18F sql report import scripts that rename the columns.  

* [ ] factpacsandparties_f3 [18F sql update script PACs parties](https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_reports_pacs_parties_view.sql)
* [ ] factpresidential_f3p [18F sql update script presidential](
https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_reports_presidential_view.sql)
* [ ] facthousesenate_f3 [18F sql update House and Senate](https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_totals_house_senate_view.sql)
* [ ] factindpexpcontb_f5 [18F sql update IE only groups](
https://github.com/18F/openFEC/blob/develop/data/sql_updates/create_totals_ie_only_view.sql)

Noting, that there are also the totals scripts that import these tables, but those should follow the same naming conventions.

**Comment by LindsayYoung** [comment]
Updating- the current views are not as-amended so these tables will be comprehensive, That way we are not changing our API offerings. (The schedules will be as-amended that is in a different issue.) Thanks @jmcarp for catching that!

**Comment by jmcarp** [comment]
For clarity: we're currently using the `expire_date` columns of the fact* tables to separate current and previous versions of reports. If possible, I'm expecting we'll do something similar with the new views.

**Comment by LindsayYoung** [comment]
wrong repo should be: 18F/openFEC/issues/1537
