### ISSUE TITLE
Right-align numbers in tables?

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-style#255]
numbers in tables are easier to read when they are right-aligned

Here is an example of one of our new office view tables:
![screen shot 2016-02-25 at 2 03 33 pm](https://cloud.githubusercontent.com/assets/4406333/13330806/942072c0-dbc8-11e5-81a8-12b5672651b8.png)
I think it would be easier for me to scan them if they were right-aligned

**Comment by noahmanger** [comment]
Oh hey we did this.
