### ISSUE TITLE
To make the site feel less stale and increase color legibility, recommend replacement colors for beige

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#264]
Based on the visual feedback, we learned that over time we were using more of the beige color palette than intended in the original design direction, because the need for neutral explainers or low-priority info panels became really common. Additionally, we've heard that $ivory sometimes appears very different shades on different user computers—sometimes pinkish, sometimes very yellow. Having so much beige around is making the site feel a little stale, and I'd like to look into swapping it out for another neutral palette complement. 

I'll be looking specifically at instances of these colors:

<img width="637" alt="screen shot 2016-03-17 at 1 47 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/13855458/f9ec2e80-ec46-11e5-8276-042c3b4d5878.png">

<img width="647" alt="screen shot 2016-03-17 at 1 47 46 pm" src="https://cloud.githubusercontent.com/assets/11636908/13855460/fe31bcda-ec46-11e5-9a78-7a6dc0273050.png">

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/279
