### ISSUE TITLE
Glossary colors seem harsh, investigate other ways of separating content

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#265]
The glossary can feel out-of-system when opened on a page with primarily navy/dark blue palettes. Investigate alternative ways of separating the glossary's content form the rest of the page, some of which might include (but definitely aren't limited to):
- changing the glossary's color scheme to be more neutral
- creating deeper sense of space between the glossary overlay and the page background

<img width="1278" alt="screen shot 2016-03-17 at 1 55 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/13855720/2715c082-ec48-11e5-8562-7e9ca9a3622c.png">

<img width="1279" alt="screen shot 2016-03-17 at 1 57 25 pm" src="https://cloud.githubusercontent.com/assets/11636908/13855742/37375430-ec48-11e5-8414-9acf7851513b.png">

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/279
