### ISSUE TITLE
Unify error / info / message styles 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#266]
@noahmanger, you brought this up in our "If I knew then what I know now" activity — could you elaborate or screenshot some examples?

**Comment by noahmanger** [comment]
This may turn out to be a non-issue, but I want to capture all the places and ways these are used:

## Filters:
![image](https://cloud.githubusercontent.com/assets/1696495/14300000/91118fd0-fb42-11e5-88d8-77634d5ea72e.png)

## Feedback form (success and error):
![image](https://cloud.githubusercontent.com/assets/1696495/14300009/9f389bda-fb42-11e5-90eb-10d3d34443b6.png)

## Search results
![image](https://cloud.githubusercontent.com/assets/1696495/14300031/b1c13226-fb42-11e5-9b8f-fce784f08deb.png)

(From production site, so using old colors):
![image](https://cloud.githubusercontent.com/assets/1696495/14300066/d1606156-fb42-11e5-9730-f5d078e6d400.png)

## Election search resuls
![image](https://cloud.githubusercontent.com/assets/1696495/14300054/c6a6aa5e-fb42-11e5-88af-15288df1ea47.png)

## Candidate and committee pages (no data)
![image](https://cloud.githubusercontent.com/assets/1696495/14300090/f11e1a24-fb42-11e5-875e-6b259b297b08.png)

![image](https://cloud.githubusercontent.com/assets/1696495/14300109/0e792514-fb43-11e5-8376-f5d627fda2ec.png)

## Error pages:
![image](https://cloud.githubusercontent.com/assets/1696495/14300101/fe77e984-fb42-11e5-8d6c-2606c9812fcb.png)

**Comment by noahmanger** [comment]
I'll defer to @jenniferthibault on this, but the only thing I can think of that might be worth doing is standardizing the "inverse background" version. Currently, we have two versions, one against the navy of the feedback box and one against the gray of the filter panel.

We should also identify when we use icons or not.

**Comment by noahmanger** [comment]
Reassigning to @jenniferthibault to take it from here.

**Comment by jenniferthibault** [comment]
I re-audited to get the colors aligned (thank youuuuuu staging push!). I was trying to diagnose how we were using the alerts through identifying patterns. 

I have two options for unified alert systems that we could implement, with some preliminary documentation. Click the image to open a huge version in a new tab :)

**1: More u-turns**
- This system uses the `!` as a warning for no results returned. This is closest to how we're using them now, but I'm worried that comes off as alarming when no results are returned, and could more easily be interpreted as a negative warning.

![alert system 1](https://cloud.githubusercontent.com/assets/11636908/14512664/0c34142c-01af-11e6-8d8a-4b110d4f3f88.png)

**2: No results ≠ alert style **
- This system stops treating "no results" as an alert, and more of a formatted announcement. I'd like to look more closely at the search results pattern here and across Legal Resources, but my hunch is that this is a better (less negative) approach.
  
![alert system 2](https://cloud.githubusercontent.com/assets/11636908/14512670/12bd6d34-01af-11e6-85d2-ed3e2433dcea.png)


For now, let's focus on the system, then move to some copy improvements that I've opened/flagged in the comments later. 

cc @noahmanger @emileighoutlaw

**Comment by emileighoutlaw** [comment]
I'm excited to start thinking about content, but don't want to jump in early before we have a system in place! Shall I stay in lurking/thinking mode until y'all are ready for me?

**Comment by jenniferthibault** [comment]
Your thoughts are welcome on the system as well @emileighoutlaw ! 
I'll leave the decision on the right time to start thinking about how content could be molded to you, but you are welcome to participate or lurk in the meanwhile!

**Comment by emileighoutlaw** [comment]
Excellllllent. I'll put some thoughts in here sooner rather than later, then ;)

**Comment by noahmanger** [comment]
I agree with you. The second approach seems more accurate and like a better experience. Great notes on the copy throughout.These are definitely areas we can improve. (Remind me to talk about the "designing for failure" talk I saw recently).

**Comment by emileighoutlaw** [comment]
I agree that the `!` is alarming, and I do think the second approach is the friendlier refinement. 

Copyedits to follow. Let me know if you have notes!

_I can add these changes to the forthcoming style PR or make my own copyedits PR, whichever you prefer._

_**One more question**: Did we ever figure out who "Email support" goes to? It'll be easier to suggest text edits knowing where that email goes, but I did a text search for "Email support" and can't find the code in any of the repos :(_

### Make a u-turn
###### Original: 
**Oops: We messed up.** 
We just experience a server issue. Please try reloading the page.

###### Revised: 
**Oops: We messed up** 
We had trouble processing your request. Please try reloading the page.

### Success alert
###### Original: 
**Thanks for helping us improve betaFEC** 
This information has been reported on GitHub, where it is publicly visible. _Track_ the status of your feedback.
[ Submit another issue ] 

###### Revised: 
**Thanks for helping us improve** 
This information has been reported on GitHub, where it's publicly visible. 
[ Track your feedback ] [ Submit another issue ]


### Results returned 1

###### Original: 
**No results** 
This committee has no financial data for the 2013–2014 election cycle in betaFEC.
For complete data, search the FEC Candidate and Committee Viewer

Is this information correct? Let us know.
[ File an issue ] [ Email support ] 

_Note: At what point do we want to get rid of the link to the FEC Candidate and Committee Viewer? I think our data is just about ready for us to remove this note, right?_

###### Revised: 
**No results** 
We didn't find any financial data for this committee in the 2013–2014 election cycle.

Think this is this a mistake? Please let us know.
[ File an issue ] [ Email support ] 



### Results returned 2

###### Original: 
**No results** 
Sorry, there are no results for your search, "zebra"
View search results for _committees matching "zebra" (5)_

Or try browsing one of the following data sets:
[ X ] [ X ] [ X ] [ X ] [ X ] [ X ] 

###### Revised: 
**No results** 
Sorry, no results match your your search, "zebra."
View _5 committee results_ matching "zebra."

Or browse a different data set:
[ X ] [ X ] [ X ] [ X ] [ X ] [ X ]

**Comment by jenniferthibault** [comment]
Sorry for the delay here. I brought the text changes in to the second system:

![alert system 2 copy](https://cloud.githubusercontent.com/assets/11636908/14683429/acbabc36-06f8-11e6-996d-973c26e0c9b0.png)


@emileighoutlaw it looks like the email links shoot to `betafeedback@fec.gov` which is also the email link in the footer. Does that allow us to be more helpful?

For naming things, it also probably makes more sense to call U-turns "Warning Alerts" instead. 

Last bit: (and maybe needs advice from @noahmanger here) What guidance can we offer to people on the "No data found" result? Can we change the messaging by adding more helpful text about why data wasn't found, or if no data exists? I think users need a better explanation here.

Next, and sort of related, I'm going to be looking at the Results Returned pattern in https://github.com/18F/fec-style/issues/318 , but I don't think that should hold this up.

**Comment by noahmanger** [comment]
The "No data found" message is used when a data table doesn't have any results. In the case of a committee receipt or disbursement tab table, it means that there's no reported receipts or disbursements for that period.

**Comment by emileighoutlaw** [comment]
This revision looks awesome, Jen! Notes:

#### Warning alert
- No period after `Oops: We messed up` 
- Also, it looks like we got "Please try reloading the page" written twice in that alert.
- `Email support` could become `Email our team` 
    - (What do you think? It's kind of a mish-mash of people who monitor that email, so it's hard to be more concrete there.)

**Comment by jenniferthibault** [comment]
Whoops, copy paste error :)

I think `email our team

**Comment by emileighoutlaw** [comment]
Yes! For consistency with the other no results alerts, how about: 

#### No results
**Sorry, we didn't find any financial data for** _(insert their search term or timeframe here? If that's a heavy lift, we could say `that matched your search` instead)_. 
**Think this is a mistake? Please let us know.**
[ File an issue ] [ Email our team ]



#### One other note:
The **No results** alert for "we didn't find financial data for this committee..." should probably also start with a "Sorry," for consistency.

**Comment by jenniferthibault** [comment]
Thanks Emileigh! So the below captures where we've netted out, and I believe it's ready for implementation by @noahmanger 

The middle two designs for Results Returned will improve what we currently have, while the improved search results pattern gets implemented from #318 , which I see entirely replacing these two.

![alert system 2 copy](https://cloud.githubusercontent.com/assets/11636908/14790327/ca789510-0ade-11e6-9773-56e8821e0783.png)
