### ISSUE TITLE
Create more engaging ways for users to share FEC info on social media

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#267]
We've been using the same meta image since we launched, and it's not terribly evocative (though it is pretty and consistently recognized). It would be nice to offer some more options for meta images that users could choose from, or more ideally, find ways users could share specific content on social media more easily. From the social media audit, there was a pattern of people uploading their own screenshots (often annotated, or with arrows or circles) when they wanted to share something they found on the site. How could we make this a better, more delightful interaction?
- Look into ways of making content modules share-able, to the extent possible
- Offer more meta image options for facebook and twitter

**Comment by noahmanger** [comment]
Creating shareable graphics is a pretty different thing than coming up with more interesting meta images. What if we keep this issue focused on designing meta images. 

It's totally possible to have unique images for different pages. The easiest thing to do is to have different images for different _types_ of pages (e.g. candidate pages have a different meta image than CMS pages). But down the road I could imagine using some server-side magic to create unique meta images for each particular candidate page. 

If we're keeping it simple, do you want to do that this sprint, or later?

**Comment by jenniferthibault** [comment]
Later sprint.
