### ISSUE TITLE
Deploy the static styleguide to github pages

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#268]
We should deploy the styleguide to github pages so that users don't need to build the guide in order to view it.

This can be automated with Travis so that it's kept up to date.

**Comment by noahmanger** [comment]
I'm into this idea. Do we need to deploy it to an "18F Pages" site? Or is regular github-pages ok?

**Comment by jenniferthibault** [comment]
OMG PLEASE DON'T MAKE ME DEPLOY IT TO SEE IT ANYMORE. 
This will make me so happy!

**Comment by adborden** [comment]
Yeah, #admins-github said to host it on 18f pages. A version is up there now https://pages.18f.gov/fec-style. I should get to this soon.
