### ISSUE TITLE
Audit appearance of the fonts on different browsers and operating systems

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#269]
In order to determine whether we've chosen a suitable font package, or need to make adjustments, see how it is appearing for different users.

- Get screenshots from FEC partners, and individuals outside of FEC and 18F to compare. 
- Determine changes or optimizations needed based on ^

**Comment by jenniferthibault** [comment]
**Screenshots on Mac OS X El Capitan and Chrome:**

<img width="1271" alt="screen shot 2016-03-22 at 11 49 53 am" src="https://cloud.githubusercontent.com/assets/11636908/13963280/2a4d2ec4-f03b-11e5-8575-161364a56949.png">

<img width="1274" alt="screen shot 2016-03-22 at 11 48 09 am" src="https://cloud.githubusercontent.com/assets/11636908/13963289/323a9f18-f03b-11e5-95d1-e95a0717181f.png">

<img width="1271" alt="screen shot 2016-03-22 at 11 49 28 am" src="https://cloud.githubusercontent.com/assets/11636908/13963296/3891a974-f03b-11e5-8a4e-66996538c8ea.png">



**Screenshots on a virtual instance of Windows 7 and Internet Explorer:**
- Karla not loading
- Some inaccuracies in contrast of Gandhi (especially bold weight)

<img width="1280" alt="screen shot 2016-03-22 at 12 12 40 pm" src="https://cloud.githubusercontent.com/assets/11636908/13963316/4c108f4c-f03b-11e5-8e37-59d29566b231.png">

<img width="1258" alt="screen shot 2016-03-22 at 12 13 36 pm" src="https://cloud.githubusercontent.com/assets/11636908/13963326/5195967e-f03b-11e5-8c71-8790a9ad1c1d.png">

<img width="1280" alt="screen shot 2016-03-22 at 12 14 48 pm" src="https://cloud.githubusercontent.com/assets/11636908/13963325/515f6d9c-f03b-11e5-8081-39b9c7d360b8.png">

More instances coming soon

**Comment by jenniferthibault** [comment]
The issue with Karla not loading in the specific instance above seems to be a VPN issue, since I'm not seeing it when I use BrowserStack  

The screenshot quality here isn't great, and I think creates more artifacts than were truly present, but here are a few more:

**Screenshots of Windows 10 and Firefox:** 

![win10_firefox_46 0_aurora 1](https://cloud.githubusercontent.com/assets/11636908/13969428/3d4623a0-f059-11e5-810d-24f4a5841e69.jpg)

![win10_firefox_46 0_aurora](https://cloud.githubusercontent.com/assets/11636908/13969427/3d461cb6-f059-11e5-92a8-5f59bf332dc4.jpg)

**Screenshots of Windows 10 and Internet Explorer:** 

![win10_ie_11 0](https://cloud.githubusercontent.com/assets/11636908/13969458/6f505f50-f059-11e5-9720-ae866fa4744d.jpg)

**Screenshots of Windows 7 and Internet Explorer:** 

![win7_ie_11 0](https://cloud.githubusercontent.com/assets/11636908/13969472/83ae8a30-f059-11e5-8fee-00b0694e414c.jpg)

**Comment by noahmanger** [comment]
Any next steps on this?

**Comment by jenniferthibault** [comment]
Looking at each case above, it appears that the largest interruptions happen over VPN (when fonts aren't loaded at all). Since I didn't see the same interruptions using BrowserStack, I don't think they're real. 

Observations:
- Gandhi gains some inconsistent widths in bold expressions, but not distracting unless yor'e focusing on fonts
- Closed counter spaces seen in Karla screen shots are artifacts of the screen shots, not what was seen on screen

Everything else I see is an acceptable amount of degradation to me. The changes proposed earlier in https://github.com/18F/fec-style/issues/155 would take care of errors in readability that could be controlled by leading & kerning

@noahmanger do you see anything else that indicates necessary changes?

**Comment by noahmanger** [comment]
Sounds good to me! Moving #155 to this sprint and closing this issue.
