### ISSUE TITLE
Make map styles and interactions more consistent

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#272]
We use two differently styled maps: one for data viz at the state-level, and one for district/zip code search on election search pages. We should align these styles more closely (which probably has limits based on what we're using to generate the maps), but also use this to plan any geography-based data exploration tool on the data dashboards. 

<img width="1021" alt="screen shot 2016-03-17 at 4 04 56 pm" src="https://cloud.githubusercontent.com/assets/11636908/13859480/04ace464-ec5a-11e5-8105-880195d18267.png">

<img width="1023" alt="screen shot 2016-03-17 at 3 57 09 pm" src="https://cloud.githubusercontent.com/assets/11636908/13859481/0878ed0e-ec5a-11e5-9e59-56895f185911.png">

<img width="1093" alt="screen shot 2016-03-17 at 3 58 25 pm" src="https://cloud.githubusercontent.com/assets/11636908/13859482/088052b0-ec5a-11e5-978c-efd583db3816.png">

<img width="1262" alt="screen shot 2016-03-17 at 4 10 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/13859636/cd2794ca-ec5a-11e5-8dac-c8f5c0432c7c.png">

cc @noahmanger

**Comment by jenniferthibault** [comment]
Looking back in the design files, I also dug up our intended interaction for the map comparison https://github.com/18F/openFEC-web-app/issues/645#issue-106097664

**Comment by noahmanger** [comment]
This is a pretty big task because it means replacing one of the two separate mapping libraries we're using. Is it ok if we icebox this for now?

**Comment by jenniferthibault** [comment]
What would it take to move a big task like this out of the ice box? It's a significant visual stumbling block.

**Comment by noahmanger** [comment]
Good question. To move it out of the icebox I think we should raise it with our partners and talk about the relative trade-offs in terms of what among current priorities we've identified would have to wait in order to do this. 

But if we end up picking up a map visualization for the new pages, I would see the value in addressing it as part of that for sure.

**Comment by jenniferthibault** [comment]
From @LindsayYoung , this could help us move to more precise district maps on the zip/election search:
http://sunlightfoundation.com/blog/2016/07/06/opengov-voices-creating-congressional-district-maps-with-github/

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-cms #1587](https://github.com/18F/fec-cms/issues/1587) via [**ZenHub**](https://www.zenhub.com/)
