### ISSUE TITLE
Begin unit tests on JS components

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#28]
I don't think we need full test coverage, since most of the components have been stable for a while, but we should at least set up the testing structure and write a handful of example tests.

**Comment by noahmanger** [comment]
I wouldn't mind taking the opportunity to learn up on this stuff if you wanted to give me an intro (or point me towards some reads).

**Comment by msecret** [comment]
I've set this up on other projects like peace corps and let girls learn. I'd suggest karma for a test runner. While not perfect, it seems to have the best support and is the most stable.

**Comment by jmcarp** [comment]
@msecret I wrote up https://github.com/18F/fec-style/pull/30 to add a basic testing framework and some tests. Right now it's using mocha as a test runner. It looks like it would be easy to add karma on top of that, but I'm not sure what it buys us--what are the benefits of karma + mocha over mocha on its own?

**Comment by jmcarp** [comment]
Done in #30. There are still more tests to write, but now it's part of the workflow.
