### ISSUE TITLE
Add "Work in progress" disclaimer to front of styleguide

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#281]
Let users know that the styleguide itself is a work in progress.

**Comment by jenniferthibault** [comment]
Trying to do this in code, but hitting walls everywhere. Going to submit a few changes for this as mockups instead, sorry for slowing things down!

**Comment by jenniferthibault** [comment]
This overlaps with #283 , but I'm trying to set up a simple approach that we can build on, which to me includes adding text to the overview, and adding a small "draft" statement to the nav header area:

![web-style-guide-1](https://cloud.githubusercontent.com/assets/11636908/14571071/5a5522e2-0315-11e6-94fe-19bfa3d02406.png)

Text:
_________________________________
## Getting started

This is the collection of styles and design patterns that make up beta.fec.gov. Like the main site, the style guide is a work in progress, and you may not find complete documentation behind what's here, or a full list of design patterns.

[Let us know](#) how we can improve.

**Comment by noahmanger** [comment]
I like it!

**Comment by jenniferthibault** [comment]
Closed by #317
