### ISSUE TITLE
Update SVG workflow

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#282]
I want to look into using a new workflow for our SVG icons that would allow us to style icons with CSS, making the icon library easier to maintain.

**Comment by noahmanger** [comment]
Doing some preliminary research on this, and it looks like it should be really easy to automate a process along the following lines:
- Maintain a single Sketch file in the `fec-style` repo with an organized collection of all SVG icons
- Use [Sketch Tools](http://www.sketchapp.com/tool/) and [gulp-sketch](https://github.com/cognitom/gulp-sketch) and either [gulp-iconfont](https://www.npmjs.com/package/gulp-iconfont) or [gulp-svgicons2svgfont](https://www.npmjs.com/package/gulp-svgicons2svgfont) to create an icon font directly from the sketch file (example [here](https://github.com/cognitom/symbols-for-sketch))
- Use [gulp-iconfont-css](https://github.com/backflip/gulp-iconfont-css) to generate the SCSS file
- And then use [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite) to generate an SVG spritesheet, which will be used to insert SVGs into the markup (rather than `img` tags)

The icon font will be used when inserting SVGs as a background image to buttons or headers. By using an icon font, it will automatically inherit the color of the text, so we won't need to export multiple color options for each scenario.

By using a sprite sheet and the `<use>` tag instead of `<img>` it allows us to modify the colors of the various parts of an SVG in the DOM with CSS, thus also saving us from having to export multiple color variants.

Curious if @adborden has thoughts on this.

**Comment by noahmanger** [comment]
FYI I started work here: https://github.com/18F/fec-style/pull/327

It's coming along well. Some next steps I'd like to try, but all in all the tools seem to do the job.

**Comment by adborden** [comment]
Very cool! Are the SVGs going to be used as a fallback? I just remember CFPB and eregs avoiding the iconfont for some reason (and using SVGs instead).

I wonder if it makes sense to keep the sketchtool stuff out of this repo, maybe create a new repo just for holding the sketch files and generating the SVGs which are then committed to `fec-style`. The reasoning is like this:

- I believe sketchtool is mac only, so you wouldn't be able to build the SVGs on Linux (and Travis) anyway.
- I'm not sure the relationship to Sketch/sketchtool, what's the license for sketchtool? I don't think we'd be distributing it so it doesn't _really_ matter but I do prefer open source tools over proprietary ones -- at least when we have the luxury of being picky :)

**Comment by noahmanger** [comment]
I'd be interested to know why they chose to avoid it. I know there's been a movement against icon fonts in favor of SVGs for accessibility reasons, but as I understand, that was a reaction to the way that a lot of people were using things like `<i class="save-icon"></i>` instead of `img` with alt tags. But I wonder if there was another reason.

Re: SketchTools, I ended up not going this route. You're right, it's proprietary and comes bundled with the app itself. A better solution definitely seems to be to just export icons as SVGs into a single directory manually and then have the build process turn those into the font, rather than the build process handle the exporting.

But yeah, might be worth setting up a separate repo for our purposes to share the file and have the automated exporting, but I agree it shouldn't be part of this.

**Comment by noahmanger** [comment]
Ok, summarizing conversations from various channels:

It turns out that CSS pseudo-content actually _is_ read by screen readers, which means that inserting icons this way results in a lot of gibberish being read by screen readers. Which basically makes this a non-starter. There's also a bunch of other reasons not to do it this way [as outlined here](http://blog.cloudfour.com/seriously-dont-use-icon-fonts/). I thought they wouldn't be relevant using them in this way, but apparently not the case.

So! That means plan B: Apparently it's possible to insert SVGs in as background-images using Data URIs. A [couple](http://stackoverflow.com/a/33435726/1864981) [places](http://codepen.io/noahblon/post/coloring-svgs-in-css-background-images) explain this.

My proposal:
1. Setup a Gulp task to create a Sass partial with each SVG assigned as a string to a variable.
2. Use Sass functions similar to those in the above examples to find-and-replace color values in the SVG strings. These functions can be called by classes or mixins so that icon color can be set programmatically rather than needing to generate each color by hand.

Fortunately, this doesn't mean anything for @jenniferthibault 's workflow and actually should be a slightly simpler process than the icon font approach.

**Comment by jenniferthibault** [comment]
@noahmanger does that imply any changes to what I was going to do for https://github.com/18F/fec-style/issues/328 ?

**Comment by noahmanger** [comment]
@jenniferthibault nope! You can just plan on doing things the same way.

**Comment by noahmanger** [comment]
Resolved by #334
