### ISSUE TITLE
Update information architecture of styleguide 

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#292]
Once we have the remaining components and modules included in the styleguide, examine the way that the pieces are organized in order to make a more intuitive, cohesive guide.

**Comment by jenniferthibault** [comment]
👍

**Comment by noahmanger** [comment]
Ok, thinking through this in the open. Based on a conversation in the design channel around pattern library taxonomies, I think I agree with the recommendation there that instead of trying to organize everything into a strict hierarchy (e.g. atoms > molecules > organisms), for the purpose of the style guide, it would be good to just have a broad category "components", which means you spend less time searching through the hierarchy to find the thing you're looking for.

I think this makes sense, with one modification: I think it makes sense to pull out certain base styles (like typography, icons, color) into their own pages. 

So here's a suggestion along those lines:

1. Overview (Home page)
2. Typography (base styles as well as utility classe included in Type Styles)
3. Colors 
4. Icons
5. Components (everything currently included in Elements, Layout, Components, Modules; organized alphabetically)

How does this sound? To me, the main need we want to solve here is to have it be intuitively organized so that you can easily find what you're looking for. Does this model make sense to the current users of the style guide, @jenniferthibault and @adborden ?

**Comment by jenniferthibault** [comment]
I mostly agree with the thinking you outlined in your last comment @noahmanger , but I have a few proposed differences.

I think there is value to showing levels of complexity that a loose interpretation of the atomic model does well. The structure that I've been following in my design files is "show what the small piece looks like" » "show how to combine it with other pieces" » "show how those pieces are arranged in patterns on pages". What this is missing is a way to show the underlying rules that build the pieces (something like Utilities/Mixins?) 

I've been working in a [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1pckUSGjmhPxFQwjTWTPvI2xderAL6MeWiin9V9cDkWQ/edit?usp=sharing) 🔒 , please head there with comments.

Preview:
![screen shot 2017-01-17 at 12 21 16 pm](https://cloud.githubusercontent.com/assets/11636908/22031708/7978abc0-dcaf-11e6-95aa-5e15aecc0a7d.png)

**Comment by jenniferthibault** [comment]
☎️ @xtine for your thoughts too!

**Comment by noahmanger** [comment]
Thanks for thinking on this! I just dropped some thoughts in.

**Comment by jenniferthibault** [comment]
Ping @xtine for your 👀

**Comment by xtine** [comment]
It might be a bit helpful to look at how cloud.gov organizes their design system: https://styleguide.fr.cloud.gov/

**Comment by adborden** [comment]
@thisisdano came up with the cloud.gov organization which is based on this https://docs.google.com/spreadsheets/d/1jz_R-92lRCUcOqzHBB9D-5AQvO6U7fZHJ_AKMChIkXM/edit#gid=0

**Comment by jenniferthibault** [comment]
Oh yes, I borrowed strongly from @thisisdano 's structure in cloud.gov, but differed because our system is not built on an atomic model as closely. 

I've also been 👀 peeping on what @line47 is thinking about in [Marigold's info architecture issue](https://github.com/18F/marigold/issues/32#issuecomment-274517111) . 👋 Scott, feel free to creep around in here if it's helpful to your research or process!

From a viz design conceptual standpoint, I reallllly like the idea @noahmanger & @xtine suggested of pushing Components + Features together, but borrowing @line47 's idea of moving the "fundamental" visual design components (color, typography, grid, possibly even icons, but maybe not icons) into the `Base` section, or whatever we call it.

I want to think through all the comments folks left in the Doc some more and give it another revision. Thank everyone 💪

**Comment by line47** [comment]
Thanks @jenniferthibault, I will definitely keep an eye out. I've also worked on [atomic design system guidelines](https://docs.google.com/spreadsheets/d/1dKkLKE8M41HMtdQQJbxbaM7f-1lgLehHbHrY4x3b-nY/edit#gid=0 ) based off of @thisisdano [sketch for a united design system](https://docs.google.com/spreadsheets/d/1jz_R-92lRCUcOqzHBB9D-5AQvO6U7fZHJ_AKMChIkXM/edit#gid=0).

**Comment by jenniferthibault** [comment]
Ok! I've done a lot of looking, reading, and thinking, and I have a next draft ready for @noahmanger & @xtine to check out.

## Proposed model:

### Priority 1: Main library categories
For our system, it feels right to separate out the visual basics from the components themselves. But with a broad collection of components, it also feels like we need to show people established ways of  how they come together (Layouts)
- **Style:** The visual basics that set the look, feel, and tone of the system
- **Components:** The organized building blocks of the system 
- **Layouts:** Repeated templates built from components

This is the basic structure, but I've started to flesh out what the sub-items in each could be (I'm sure it's incomplete, but it's a working start):
[Google Doc](https://docs.google.com/a/gsa.gov/document/d/1pckUSGjmhPxFQwjTWTPvI2xderAL6MeWiin9V9cDkWQ/edit?usp=sharing) 🔏  
_____________________________

### Priority 2: Methodology & working visual assets
I know less about how we want to integrate these, and they'd maybe be further down the line, but feels like they situate the pattern library in the rest of our design, content, and research process.
- **Guidance:** How the patterns fit within the rest of the product's design ecosystem (design principles, content principles, content guide, testing repo info)
- **Design kit:** Sketch files & plugins used



Thoughts? Reactions? Questions?

**Comment by jenniferthibault** [comment]
The model in my comment above is going to be the working model for the next iteration—issue can be closed if implementation wasn't part of the criteria, but should remain open if it was.

**Comment by noahmanger** [comment]
Looking pretty good. I just jotted down several more things that come to mind as well. Would love @xtine's thoughts when you're back.

**Comment by jenniferthibault** [comment]
@xtine does it make sense to transfer this task to you for this sprint? Or would you rather make a new issue for what you're working on and close this?

Completion criteria feels like it would be that the new top-level structural categories are implemented in Fractal (Style, Components, Layouts)

**Comment by xtine** [comment]
@jenniferthibault: I am closing this in favor of this issue I am working on: https://github.com/18F/fec-style/issues/725
