### ISSUE TITLE
Add modules to styleguide

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#293]
Add or update the following modules in the styleguide:
- [ ] candidate-page
- [ ] data-container
- [ ] datatable-panel
- [ ] datatables
- [ ] entity-header
- [ ] feedback
- [ ] filters
- [ ] footer
- [ ] glossary
- [ ] hero
- [ ] nav
- [ ] page-controls
- [ ] results-info
- [ ] search-controls
- [ ] section-headings
- [ ] site-header
- [ ] totals-tables
- [ ] calendar
- [x] downloads

**Comment by jenniferthibault** [comment]
Closing in favor of improvements being tracked in the pattern library
