### ISSUE TITLE
Implement new button styles

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#297]
Implement the new button styles defined in https://github.com/18F/fec-style/issues/288.

@jenniferthibault , let me know when this is good to move to implementation.

**Comment by jenniferthibault** [comment]
Here's [an InVision](https://invis.io/Z46U2A16W) with my take on how the styles from #288 would be implemented across screens: I've color-coordinated style matches for toggles, buttons, and drop-down lists. Feedback welcome ( @adborden @edmullen ! ) though I haven't done much annotating in the mockups, I could do that tomorrow if needed.

(Sorry, screenshots are a bit scrappy)

Closing out #228 , #236,  and #235 in favor of this inplementation

**Comment by noahmanger** [comment]
This is great! Thanks @jenniferthibault . Really helpful to see how they work in the wild, too. I left a few comments / questions in there that I noticed, but either way I'm going to start on this Thursday.

**Comment by jenniferthibault** [comment]
I wish I could reply to an InVision comment with a photo, but no dice, so here we are. @noahmanger per your first comment about button syntax, it's helpful for me to see the button styles in two ways (thinking to how we decide to present them in the style guide)

1: How many discrete button styles are there overall?
The types of buttons and how or if their style needs to be changed depending on what background they appear on. 
![screen shot 2016-04-07 at 12 15 16 pm](https://cloud.githubusercontent.com/assets/11636908/14358330/6fc427ce-fcba-11e5-933e-31f269355adb.png)


2: How do the buttons get used with different colored backgrounds? (What buttons can I choose from depending on what background color we're using in this instance?)
![screen shot 2016-04-07 at 12 08 18 pm](https://cloud.githubusercontent.com/assets/11636908/14358241/18c7be22-fcba-11e5-9956-0374e8191d77.png)

This makes it clear to me that the standard gray button could be used on the blue and red backgrounds, which you wouldn't know on the first one. (Though given that the solid backgrounds are usually call-to-action type areas, I haven't needed it yet)

**Comment by noahmanger** [comment]
Will we ever use the aqua or orange call to action buttons on neutral backgrounds? Wondering if we can just set those as a rule on certain backgrounds.

**Comment by jenniferthibault** [comment]
Not as I was planning it. The neutral background would be the same combos as a white background, because there is no fill to the button backgrounds (they are transparent as I've build them) Here's what that would look like more explicitly:

![screen shot 2016-04-07 at 1 38 02 pm](https://cloud.githubusercontent.com/assets/11636908/14360806/146995ec-fcc6-11e5-8f04-ce28de748490.png)
