### ISSUE TITLE
For best visual consistency, use consistent font sizes on candidate profile page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#299]
Text in the categories for Party, Status, and District are rendering as 14pt, while text in the categories for Principal Committee and Elections are rendering as 16pt. They should be the same. 

I'm kind of worried because I think I remember patching this at one point before? 

<img width="992" alt="screen shot 2016-04-07 at 10 40 13 am" src="https://cloud.githubusercontent.com/assets/11636908/14354946/4e39befa-fcad-11e5-8aae-7e9e72272e2b.png">

**Comment by noahmanger** [comment]
Derp. I found the issue. An errant `<p>` tag. Fixed in https://github.com/18F/openFEC-web-app/pull/1164
