### ISSUE TITLE
To reduce visual tension in the layout, adjust spacing in filter panel template

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#312]
Some refinements to the filter panels that will make them awwwwwesommmmme.

Desktop only change: **`.filter__header`:**
- Add `margin-top: .6rem`
- Increase `margin-bottom` to 1.5rem from 1rem

![screen shot 2016-04-14 at 10 46 13 am](https://cloud.githubusercontent.com/assets/11636908/14532225/52dd91ee-022e-11e6-9181-dcb55d4ac55c.png)

Existing:

<img width="535" alt="screen shot 2016-04-14 at 10 46 40 am" src="https://cloud.githubusercontent.com/assets/11636908/14532235/6022d1de-022e-11e6-94fb-73380d6f1c09.png">

Desired changes:

<img width="528" alt="screen shot 2016-04-14 at 10 46 28 am" src="https://cloud.githubusercontent.com/assets/11636908/14532244/67a42dea-022e-11e6-8d17-f3089c89fc54.png">

- When there's a search bar immediately under the header, add ~`2.1rem` of margin between the bottom of the header and the top of the search title. This happens on the Candidates and Committees pages. (implemented on all screen sizes):

<img width="650" alt="screen shot 2016-04-14 at 10 52 23 am" src="https://cloud.githubusercontent.com/assets/11636908/14532428/08475d94-022f-11e6-8d2b-c0b0f9ebc630.png">

- When an item is not inside of an accordion, add 1rem margin top between the line and the filter name. (implemented on all screen sizes)

Existing:

- Receipts
<img width="299" alt="screen shot 2016-04-14 at 10 58 10 am" src="https://cloud.githubusercontent.com/assets/11636908/14532651/cd45adbc-022f-11e6-82dc-7fa7a61778ac.png">

- Candidates
<img width="301" alt="screen shot 2016-04-14 at 11 07 24 am" src="https://cloud.githubusercontent.com/assets/11636908/14532989/2e9f6854-0231-11e6-975e-acff8cb7b79f.png">

- Committees
<img width="299" alt="screen shot 2016-04-14 at 11 07 44 am" src="https://cloud.githubusercontent.com/assets/11636908/14532990/2ea078f2-0231-11e6-837b-f3492dc3d226.png">

Desired:
<img width="302" alt="screen shot 2016-04-14 at 10 58 55 am" src="https://cloud.githubusercontent.com/assets/11636908/14532684/e924e0ac-022f-11e6-9223-0265d9031a76.png">

@noahmanger I am slightly afraid of the filter classes because they involve `child` tags, and I'm not sure what the best approach for these adjustments are. (Which is why I laid out so much detail here). This might be a good thing to pair through if we hit a slow period, or if you want to zip through them, by all means. This is definitely not a priority item, though.

**Comment by noahmanger** [comment]
Ok, I think I got all these changes in here: https://github.com/18F/fec-style/pull/329

Can you take a look? You'll also need to pull down the `feature/office-filters` branch from the web app.

**Comment by jenniferthibault** [comment]
Looks great, thank you!

**Comment by noahmanger** [comment]
Resolved by #329
