### ISSUE TITLE
To maximize useful page real estate, consider designing a mini-header for interior pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#313]
We currently use about 1/4 of the space for headers and navs. 

![screen shot 2016-04-14 at 12 25 37 pm](https://cloud.githubusercontent.com/assets/11636908/14535563/66139e62-023c-11e6-8245-c6150247ae2c.png)

I think we can do better and allow the real important stuff to take the spotlight more. One approach would be to use a simplified iteration of the header on pages that are not the home page. Or: we could design an interaction that shrinks the header to a simplified version once a user scrolls down from the top of the page.

**Comment by jenniferthibault** [comment]
The header space is really part of a information navigation system, which has two parts: the header and the footer. Each of my ideas for the header below has a corresponding dependency for IA in the footer. Our overall IA is still up in the air, which makes this a little hard, but it helps to think of this as an intermediary design until we know more about what needs to be in the priority top nav.

To think about: it's possible to have different nav arrangements on the home page and on the interior pages, but also possible to just use one template

So let's dig in.

### Our current header
- Height: A _whopping_ 190px
- Great for intro/display heroism. Not great for page visibility, especially on data tables

![main header](https://cloud.githubusercontent.com/assets/11636908/15253836/f3f14fdc-1901-11e6-94ed-c087551647ca.png)

### Possible minified header 1
- Height: 112px
- Keeps main nav + second level nav, moves Glossary and Calendar to second level
- Leaves room for more nav elements 

![mini-header](https://cloud.githubusercontent.com/assets/11636908/15253972/95c402dc-1902-11e6-9564-9deea1250644.png)

### Possible minified header 2
- Height: 78px, the mini-est
- Forces us (in a good way, I think) to reduce the nav items to only the most needed elements
- Will rely heavily on the footer for supplementary information. This is similar to the approach we've taken on https://18f.gsa.gov/

![mini-header copy](https://cloud.githubusercontent.com/assets/11636908/15254062/e97fa12e-1902-11e6-87e6-137d0c856b08.png)

#### Accompanying Big footer 

![big footer](https://cloud.githubusercontent.com/assets/11636908/15254078/f62d11b8-1902-11e6-996f-4407e141290e.png)

![bigfoot-footage](https://cloud.githubusercontent.com/assets/11636908/15254103/1b69009a-1903-11e6-8d40-16440f673b75.jpg)

cc @edmullen @noahmanger @onezerojeremy @emileighoutlaw

**Comment by noahmanger** [comment]
Dig it.  I think the first option works best for a few reasons:
- It probably scales easier to screen sizes between tablet and full-size desktop
- I like that it keeps the main nav items in essentially the same position as the full-size header, which probably makes for a more seamless transition between the home page and other pages (and also is probably easier for the mega menu)
- I like moving calendar to the utility nav
- I think I like having the glossary button in the utility nav as well, as it allows us to add the label, but wonder if it should have more of a button appearance since it triggers an overlay rather than going to a new page

And 👍  to the big footer, though we should think about how this works on mobile. I believe the USWDS technique is to turn those columns into accordions, which could work.

**Comment by edmullen** [comment]
I second Noah's comments. I like the first version for the same reasons. 

I have two very small thoughts. The pipes in the utility nav seem heavy. I wonder if they could be the light gray.

I'm finding the upper left a tiny bit too disarranged. I wonder about increasing the logo size and letting it peep over the horizontal rule and left-align the _looking for FEC_ and _Federal_.
![image](https://cloud.githubusercontent.com/assets/2654503/15258871/e73c22ac-191b-11e6-9223-a34d4735ca22.png)

**Comment by emileighoutlaw** [comment]
Agree with Ed and Noah. This looks rad, Jen! I think minified header 1 is easier for me to read and sort through— I appreciate having the main content chunked out on its own, which I think will be a nice visual clue about the difference between the utility nav and rest of the site content.

Aside: I still can't see anything other than _FEC cupcakes_ when I look at their Twitter handle.

**Comment by onezerojeremy** [comment]
Agree that 1 is better as well! 

Tiny thing, and I might be wrong but my eye feels like there is something unrestful in the current horizontal placement of the main nav. For me, I get a bit of visual jitter in how the "Campaign" starts just below where the seal sits. I also recognize that this may be both a. just me, and b. incredibly hard to control given different screen sizes, so feel free to ignore.

**Comment by jenniferthibault** [comment]
Thanks for the feedback, all! I've made some adjustments in addition to your suggestions:

- Repositioned the disclaimer bar and tweaked the language a tiny bit so that we could combine the beta/FEC.gov statements into one. 
- Making the Glossary link into a button style brought too much visual attention to it, so I opted not. I think the icon flags that it's something different, but since you aren't brought to a different page (and thus possibly thrown off course by its specialness), it doesn't feel like an interaction we need to overcompensate for with other signifiers. Here's how USEITI uses it on their site, which I also don't think feels jarring. https://useiti.doi.gov/
- Added a state for current nav position once you're in a child page

I'd like to propose that the calendar _may not_ permanently belong in such a prime nav position, given the two use cases. Maybe not now, but let's keep open minded? Especially knowing that someday we will need to incorporate the universal search (likely, though not certainly somewhere in this vicinity).

@onezerojeremy your eyes are spot on, when the main nav items are off-center of the sliced seal, it feels weird. My intent is to align the start of the nav with the first column of the grid, which should be about at the center of the seal. (crossing fingers that works out on the front end)

If we go with this direction, we're buying back 80px of vertical space. I'm not sure that's enough, but it may balance the hesitancy I'm perceiving about losing the utility nav. Thoughts here?

Here's what this all looks like in a design mockup with context. Since it's a screenshot, the proportions might not be an exact fit:
![desktop - nav mini](https://cloud.githubusercontent.com/assets/11636908/15298086/98191db8-1b6b-11e6-9815-5dc79c1a1b8e.png)

**Comment by noahmanger** [comment]
That all sounds good to me! Only thing I have is related to the column alignment question. The tricky thing here is that we have two layout styles: 1) full-width containers (with 20px padding on the sides), and 2) fixed-width containers, centered on the page.  When the window as only as wide (or less than) the width of the fixed container, they're the same. But when the window is larger, they're not going to be the same. Here's how they work in practice:

![image](https://cloud.githubusercontent.com/assets/1696495/15299173/0a8412f4-1b58-11e6-907e-cd6c85a55502.png)

![image](https://cloud.githubusercontent.com/assets/1696495/15299179/15968fdc-1b58-11e6-8f08-679ed1276068.png)

![image](https://cloud.githubusercontent.com/assets/1696495/15299181/19b5625a-1b58-11e6-9191-d6d625f8a7d4.png)

**Comment by jenniferthibault** [comment]
@noahmanger  Is it possible to introduce this as a `div` element within an existing layout style? (If the answer is No, because obvious front end things that I don't know, I'd love to learn more! I genuinely have no idea what's hard/easy about this)

![desktop - nav intermediate](https://cloud.githubusercontent.com/assets/11636908/15304520/d5f80be2-1b8b-11e6-8c29-444f0304b030.png)

**Comment by noahmanger** [comment]
Oh yeah totally. I might have over-explained there. My point was just that when we talk about aligning columns, we're talking about two different layouts, so we can't necessarily line up the first column between the two. But the the layout like you have there is fine.

**Comment by jenniferthibault** [comment]
OHHHHHH. I misinterpreted. I get it now 😅 

Will hold off for others to chime in on the design, or to give 👍  to move forward.

**Comment by jenniferthibault** [comment]
This feels like we've reached a good solution to implement and try in context. 

Closing and moving the last design to implementation. Will hold on footer changes until we have more info from @emileighoutlaw and @jeanninehunter 's IA workshop.

**Comment by jenniferthibault** [comment]
Being implemented in https://github.com/18F/openFEC/issues/1663
