### ISSUE TITLE
Improve usability and visual design of check box and radio button elements

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#314]
Users have reported that the check boxes are [difficult targets to hit](https://github.com/18F/FEC/issues/171) (especially on mobile).

The styles could also use a small color adjustment to align them with the new button styles.

I have some preliminary ideas on this, which I'll pick up later once we work this into a sprint.

**Comment by jenniferthibault** [comment]
Thinking through a few options for this, inspired by patterns and research of other systems that have been built and tested.

![checkboxes](https://cloud.githubusercontent.com/assets/11636908/14730841/2e16219c-0818-11e6-9459-fc1379675440.png)

Looking at the [notes and insights](https://designpatterns.hackpad.com/Radio-buttons-and-checkboxes-8eBuLm9eRaz) that led to the gov.uk pattern, I think that pattern best addresses the need to increase the hit area of each selection.

I've applied this to other scenarios ([seen here](https://beta.fec.gov/data/elections/president/2016/)) with long text or many selection areas, and think it performs well visually. I like how it makes each option more distinct, and it's quick to see how many options you're presented with. The one drawback I'm seeing is that it takes up more vertical space, but I haven't heard that as a loud concern yet.
![checkboxes-2](https://cloud.githubusercontent.com/assets/11636908/14730898/0f27ab56-0819-11e6-9e27-4c8b21fc3d0c.png)


**Steps from here:**
- discuss preferences for which direction to pursue and test out with @noahmanger @adborden @edmullen 
- Regardless of direction, we should apply the recent color changes from the button interactions (same default/hover/clicked color states) to the checkbox interactions.

**Comment by noahmanger** [comment]
Just checking: is the only difference between the USWDS and ours the color? We also have the outline on `:focus`:

![image](https://cloud.githubusercontent.com/assets/1696495/14748078/995ad084-086c-11e6-830f-46b0aaff0c5f.png)

(At least, it should be the only difference, since I lifted the code straight from them).

I don't have a strong opinion on the alternate style. It feels _a little_ noisy to me, but I also appreciate the usability gains.

What would it look like if they were all 100% width? I wonder if it would help.

**Comment by adborden** [comment]
Does the hit area actually need the border? To @noahmanger's point, maybe it would only appear on `:focus`, otherwise it feels like a lot going on. We could still expand the hit area without it being visually different.

**Comment by noahmanger** [comment]
Yep. And also to be clear: the hit area actually does include the label currently. Different than making the visual hit area obvious, but it's there.

**Comment by jenniferthibault** [comment]
@noahmanger right, the difference now between ours and USWDS is the colors (and I think maybe size?) Ours look smaller but my eyes may be tricking me.

My preference for the outlined hit area is that the visual emphasis makes it look more **obviously** hittable. Cruising around some research online affirms that people assume you need to hit the actual box for selecting a check box item, even when the whole term is hittable. (like you reiterated above) 

GOV.UK has talked about [fixed width vs dynamic](https://designpatterns.hackpad.com/Radio-buttons-and-checkboxes-8eBuLm9eRaz#:h=Dynamic-vs-fixed-width) and their current guidance is for dynamic. With our content, and since the checkboxes exist in full-width, heavily lined areas such as the filter panels, I think full-width may blend in with the accordions too much.

If the burden for implementing isn't too high, I'd like to try this approach as designed above (dynamic width, & border there full time). My concern about only showing the border on unselected items on focus/hover is that it doesn't aid mobile users in the default state.

**Comment by jenniferthibault** [comment]
Bumping this up in your alerts—let me know if this is ok to move to close the design stage and move to implementation, or if you want to talk through other ideas!

**Comment by noahmanger** [comment]
Thanks for the bump! That sounds good. I'm down to try it! Shouldn't be much work at all.

**Comment by jenniferthibault** [comment]
Implementation happening in #320
