### ISSUE TITLE
Improve usability and visual design of accordion elements

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#315]
I've found that we have three instances of accordions on the site.

On [committee overview pages](https://beta.fec.gov/data/committee/C00574624/?cycle=2016) 
![screen shot 2016-04-14 at 12 58 39 pm](https://cloud.githubusercontent.com/assets/11636908/14536957/f9bb00fa-0242-11e6-9a5c-802ed505766c.png)

In the glossary
![screen shot 2016-04-14 at 1 03 28 pm](https://cloud.githubusercontent.com/assets/11636908/14536960/fba17de0-0242-11e6-863e-fb93251e027e.png)

And in filter panels
<img width="299" alt="screen shot 2016-04-14 at 1 17 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/14537040/53b25496-0243-11e6-969c-aaec52b830a4.png">

I've seen some interaction confusion on the committee overview pages where it's harder to tell that the accordion element is there.

Small improvements could be made to the glossary if we want to break the patterns set in the filter panel less frequently. I'll look into these once we work this into a sprint task.

**Next steps: **
- audit accordion pattern in Legal Resources designs. 

cc @edmullen

**Comment by edmullen** [comment]
A bit premature, but my quick thought on committees would be to do this...
![image](https://cloud.githubusercontent.com/assets/2654503/14538224/a986ac3c-0248-11e6-94b2-1089c3afeadb.png)
...which would follow the alignment in the expanded table of two columns. And make sure there is a top and bottom border for each row.

**Comment by noahmanger** [comment]
Yeah, the committee page is definitely not great :)

Small note though: We have some markup constraints with the accordion elements. We're making the entire header row of each accordion item a `<button>` so that the whole thing is focusable and clickable. But you can't nest html inside buttons, which means that we can't arrange multiple things in a row and control the spacing. 

I'm sure we can find a good solution in spite of this, but just wanted to note the constraint.

**Comment by jenniferthibault** [comment]
Looking through the legal resources for accordion patterns, the only new one I'm seeing is on the side of a [Regulation page, like this](https://gsa.invisionapp.com/share/9Q710V45R#/screens/152289930) but I'm not entirely sure what they contain. 

@edmullen how much/what types of content would these hold? Is this a place where we could use the pattern we're using for more info on the side of the Registration and Reporting item pages, but in blue?

https://beta.fec.gov/registration-and-reporting/get-tax-id-and-bank-account/

<img width="1221" alt="screen shot 2016-04-26 at 1 07 38 pm" src="https://cloud.githubusercontent.com/assets/11636908/14827413/3bbcbbe4-0bb0-11e6-89bf-8616f1d060ff.png">

**Comment by edmullen** [comment]
The content in that area will vary, as far as I can tell. It is within the eregs platform and so we don't want to modify it much beyond visual styling. I'm open to how we do that, but it'll need open and closed states and the content is loaded via ajax based on interactions. See https://atf-eregs.18f.gov/447-21/2015-12992#447-21 as an example.

**Comment by jenniferthibault** [comment]
Thanks! Really helpful.

**Comment by jenniferthibault** [comment]
A few ideas for improvements on the full-width and small accordions:

- When on a white background, add the `$gray-lightest` color to the toggle panel to show the hit area. This is especially helpful on full-width elements where the text is far from the `+` icon
 - This adjustment also brings the pattern closer to what we use in the filter panel
- On full-width accordions, introduce a two-column layout to the content area
- Make sure that accordion elements have a top and bottom border at all times (these should be identical to the filter panel accordions
- I also adjusted some of the text styles within the accordion button area that make the hierarchy more clear

**Closed**

![accordion-full-width-closed](https://cloud.githubusercontent.com/assets/11636908/14858880/bc9a276e-0c6f-11e6-8786-87e054d2c420.png)

**Opened**

![accordion-full-width-expanded](https://cloud.githubusercontent.com/assets/11636908/14858881/bc9c4dc8-0c6f-11e6-99d0-0da781412902.png)

For the small accordion pattern on the Regs page, @edmullen I think we can use the pattern set on the Reg/Reporting side by simply adding a header to the accordion space, adjusting the type styles to match, and adding the `$gray-lightest` background from above.

![accordion-small](https://cloud.githubusercontent.com/assets/11636908/14858978/1d8f7646-0c70-11e6-9bc9-1648d162c3cc.png)

I'd leave the glossary and filter panel instances alone, as those are pretty consistent across the board, and the changes above make the other elements match them more closely.

What do you think @noahmanger @adborden @edmullen ?

**Comment by edmullen** [comment]
I like what you've done with the accordions generally and specifically think the eRegs right-side accordion looks great.

**Comment by noahmanger** [comment]
I like the light gray fill on white backgrounds a lot. That definitely helps. 

Only thing that _might_ be tricky is for the ones on the committee page: currently, I know the accordion library works when the buttons are actually `<button>` elements, which do not allow other html inside them. The design you lay out there would require multiple `<span>`s to make it work. 

It might not be an issue. I'll try to make it work with a `<div>` instead of a `<button>` while retaining the acccessibility benefits of `<button>` but I might come back and need to rethink it.

**Comment by jenniferthibault** [comment]
Ohhhh shux, I had misinterpreted because I thought that the titles _already were_ in the button elements before, and had based my design on thinking that was safe:

<img width="302" alt="screen shot 2016-04-27 at 12 59 56 pm" src="https://cloud.githubusercontent.com/assets/11636908/14860726/0c14b11c-0c78-11e6-9049-a11e6f40d43b.png">

Now I see that they aren't. Keep me posted on if this is wrecking your life & I can rethink.

**Comment by noahmanger** [comment]
Yeah...That's why it looks ugly and weird now. 

Shouldn't be a big deal. I noticed CFPB used divs for their accordions so I should be able to make it work.
