### ISSUE TITLE
Adjust spacing and color of bar chart tooltips

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#333]
- The aqua/white color combo isn't 508 compliant
- The spacing between the category and the amount is too large, items aren't visually grouped

From: https://beta.fec.gov/data/committee/C00577130/

<img width="239" alt="screen shot 2016-04-25 at 3 12 51 pm" src="https://cloud.githubusercontent.com/assets/11636908/14795832/53dd42e2-0af8-11e6-9f7d-f480ecbc08de.png">

**Comment by noahmanger** [comment]
No longer relevant.
