### ISSUE TITLE
Implement changes to search results pattern 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#335]
The interaction pattern from https://github.com/18F/fec-style/issues/318#issuecomment-214396124 uses the side menu from Registration & Reporting to align how search results are presented across the legal resources side and the data side.

![search_candidate or committee-copy copy](https://cloud.githubusercontent.com/assets/11636908/14867330/046035f4-0c96-11e6-9a37-364d477e23ec.png)

This issue is specifically for the data side — @edmullen is creating a separate issue for the style changes for the legal side, which are less substantial.

There may be an initial step to implement this which excludes the election results, not sure!

**Comment by jenniferthibault** [comment]
Whoops, I put this in the wrong repo! Meant for `open-fec-web-app` Closing and relocating.

**Comment by edmullen** [comment]
Link to issue in `open-fec-web-app`: https://github.com/18F/openFEC-web-app/issues/1202
