### ISSUE TITLE
Refine styling on navigation

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#343]
When the Campaign Finance drop-down nav has passed usability testing, pair with @noahmanger to refine the styling.

**Comment by jenniferthibault** [comment]
### Current design:

<img width="1278" alt="screen shot 2016-05-16 at 10 34 09 am" src="https://cloud.githubusercontent.com/assets/11636908/15292708/5ad17180-1b52-11e6-8451-648c3a554d66.png">

### Adjustments I'd like to make
- buy back some left/right padding away from the edges of the nav menu. We need some white space around the edges to make it more restful
- The `Committees` category should be double-width as originally designed instead of double height. This allows us to keep the `Receipts` and `Disbursements` categories next to each other
  - if that's not possible, I would switch the grid positions of `Report Summaries` and `Receipts`
  - the principle here is that Receipts and Disbursements should always be grouped by proximity
- Copy corrections: (from https://github.com/18F/openFEC-web-app/issues/1153 )
  - `Form 5 filers only committees` » `Independent expenditure (Form 5) filers`
  - `Most recent statements of candidacy (form 2)` Should be capitalized as `Most recent Statements of Candidacy (Form 2)` because it is the title of a form
  - `Most recent statements of organization (form 1)` Should be capitalized as `Most recent Statements of Organization (Form 1)` because it is the title of a form (I'm using @emileighoutlaw 's copy verbatim here from the issue linked above, assuming her capitalization was intentional)
- Add `Fundraising – coming soon` and `Spending – coming soon` under Interactive overviews to preview the organization (and give clues to what the rest of the disabled states mean)
- Can we make the nav have a custom link style from the rest of the site? I don't think everything needs the dotted underline as the default. Maybe just the category headers: when everything is underlined, nothing stands out. The child page elements could use the underline on hover/focus?
- Line height and paragraph spacing: there should be a clear difference between when a line is wrapping and when there is a hard break between two list item elements. Right now that space is all equal, so it's hard to decipher. (For comparison, in the design file, I have the font size set to 16pt, line = 19 pt, paragraph = 8. That might translate to something in CSS like a line height + margin bottom on all list items?)  
- It would be awesome if we could get the new SVG icons in at the same time for this: that line of work has all the most recent designs for the icons used here.

![desktop - nav 1 copy 3](https://cloud.githubusercontent.com/assets/11636908/15293353/949be0be-1b55-11e6-8f45-dff58b24f74c.png)


@noahmanger I bumped this to priority this morning, hoping to unblock you from implementing. Let me know how I can help and if you'd like to pair through some of the details!

**Comment by noahmanger** [comment]
Awesome. Thanks for the detailed notes. A couple thoughts:

On the committee group: whether this is a section broken into two columns, or a single column with the others moved around depends on how this changes at smaller breakpoints (mostly thinking at the tablet / small desktop width). Which way do the pieces squish, stretch and flow? What we want for this has implications to how things flow at the large screen size.

My other question is a little bigger: I remember talking about how the current layout puts a lot of emphasis on the more advanced categories. What do you think about making it so that the items that are currently in the left column were instead along the top, and the advanced stuff was below?

**Comment by emileighoutlaw** [comment]
Copy changes are perfect @jenniferthibault! Thank you!

**Comment by jenniferthibault** [comment]
Ahh I see what your'e thinking @noahmanger ! I hadn't mocked up tablet view because we switch to the mobile menu style on tablet, so they don't flow because we use a different interaction pattern. Do you think it's worth revisiting that design choice for tablet?

Here's what it would look like if we only re-ordered Receipts:

![desktop - nav intermediate copy](https://cloud.githubusercontent.com/assets/11636908/15344005/63713f7c-1c70-11e6-964a-557a67ff9ebd.png)



Great thought on the hierarchy! Unfortunately this layout gains us a good bit of unwanted vertical space, which feels beyond the max we'd want. If we like the approach, I can try to buy some back with some fiddling, but not sure I'll be able to do it entirely through layout. A quick initial mock:

![desktop - nav intermediate copy 2](https://cloud.githubusercontent.com/assets/11636908/15343993/3147f6a8-1c70-11e6-9a87-be6e4589a5b1.png)

**Comment by noahmanger** [comment]
Ah, right on. I suppose that at the point where these columns would need to re-arrange is the point when we just go to the mobile style. That works for me.

Personally, I'm kind of fond of the second option. I appreciate the way it balances out the emphasis. But I definitely see your point, and I'm not crazy about adding more height. I wonder if by introducing an advanced data index page we could save space by not showing _everything_ in the menu, but instead showing high-priority items and then linking to that index page. Would that be bad practice?

**Comment by emileighoutlaw** [comment]
I feel like I read somewhere that things divided horizontally (as in option two) make the top options more prominent to readers, but I'm having trouble remembering where. I'm going to keep digging for that.

**Comment by emileighoutlaw** [comment]
Y'all! It was about _food menus_ ( 😂 )

http://www.dailymail.co.uk/sciencetech/article-2095034/Eye-tracker-reveals-restaurant-menu-history-designed-WRONG.html

**Comment by jenniferthibault** [comment]
Capturing a chat Noah and I had in person about this:

We want to try reducing the Advanced Data items in the mega menu to ones we understand as priority interest, or most used, but without _drastic_ cuts. Users would be able to access the full list either on the data landing page or its own page,(which there would be a prominent like to in the mega menu). This also involves a few copy changes, that would look like this: 

![desktop - nav intermediate copy 3](https://cloud.githubusercontent.com/assets/11636908/15371792/2fbf1f50-1d0b-11e6-8469-bc64f1f8f1b4.png)

And we'd like to find out:
- Do users go mostly to the first three options (Profiles/overviews/location)? Or are they drawn to the Advanced Data?
- When looking for the detailed data categories no longer shown in the menu, do users use "View all advanced data categories" link to look for it?

**Comment by emileighoutlaw** [comment]
Really digging this— I'm pausing at the `+View all advanced data categories` being _above_ the line, because my eye keeps trying to put it with the the `Profiles, Interactive views, Location`. Maybe just me, though?

**Comment by noahmanger** [comment]
Really digging this as well. I think I agree with @emileighoutlaw . What would it look like to move that below?

**Comment by jenniferthibault** [comment]
I hear ya, good call!

We could do something like this instead:
(I preferred the `All advanced data categories` but that button was lonnnnng. Open to microcopy edits!)

![desktop - nav intermediate copy 3](https://cloud.githubusercontent.com/assets/11636908/15381305/7190aca0-1d4c-11e6-91e3-32e277cc592c.png)

**Comment by emileighoutlaw** [comment]
Just noticing here too that those `Alls` in the category headers should be lowercase: `Committees - all`

I'm also thinking about our use of the word "All" in general on this menu. `All disbursements` is sticking out because it's the only subcategory with `All` in it. 

Is `All disbursements` different from what would exist if we made the header `Spending - all` ?

**Comment by jenniferthibault** [comment]
Yessss, Noah talked me through this a bit and I found it super helpful.

In the category of spending, "Independent expenditures" is the odd duck , because it's not included when you view "All disbursements".  We talked a bit about maybe instead indenting or show child relationships like this, but without bullets:
- All disbursements
 - Operating expenditures
 - Expenditures to committees
- Independent expenditures

This would be an easy switch, if you'd prefer that layout @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Oh I do! I love that!

**Comment by noahmanger** [comment]
Just to be clear: do we want to move to having each of the "all" links called out as separate items? Or is it only in the case of disbursements? Strikes me as a little weird to have it incongruous, but maybe it doesn't matter. 

+1 to indenting

**Comment by jenniferthibault** [comment]
We moved it to the headline to save vertical space. Ideally the menu should not touch bottom of the window (though I know that varies by screen). Let's put this out, and adjust if it creates confusion in testing:

![desktop - nav intermediate copy 3](https://cloud.githubusercontent.com/assets/11636908/15405830/aa74f2c6-1dd1-11e6-92f1-e724b4b3214e.png)


Closing and carrying over the to-do's to implementation
