### ISSUE TITLE
Consider adding a dropdown menu for Registration and Reporting

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#350]
For parity & consistency with the Campaign finance data menu's interaction

**Comment by emileighoutlaw** [comment]
This is a great issue (and question). I'm glad you bring it up! I'm trying to think back to the murky days of our early registration and reporting designs. I believe one of our intentions was that we *wanted* everyone to go to the registration home and see the options. But I also think we were anticipating having more and different content than we ended up developing for those pages.

**Comment by jenniferthibault** [comment]
Sorry for the vague issue! Seems like you grokked it anyways 😄  Im' intending to come back to this thought next sprint

**Comment by emileighoutlaw** [comment]
It's been on my mind, too! :)

**Comment by jenniferthibault** [comment]
Closing in favor of work in https://github.com/18F/fec-cms/issues/827
