### ISSUE TITLE
Hero content for of each landing page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#356]
Separating content design out from the discussion in https://github.com/18F/fec-style/issues/330

![screen shot 2016-05-23 at 9 43 55 am](https://cloud.githubusercontent.com/assets/11636908/15472825/fa410154-20ca-11e6-841a-61c84f633218.png)

![screen shot 2016-05-23 at 9 44 05 am](https://cloud.githubusercontent.com/assets/11636908/15472824/fa40ca22-20ca-11e6-86c1-83ba27cbe996.png)

![screen shot 2016-05-23 at 9 44 14 am](https://cloud.githubusercontent.com/assets/11636908/15472826/fa422408-20ca-11e6-9fda-b0ab5ba4d495.png)

**Comment by emileighoutlaw** [comment]
Thoughts from https://github.com/18F/fec-style/issues/330


#### Content thoughts
I like the consistency of language of "Find details on..." that we have in Legal and Campaign finance. 

##### Campaign finance
I'm eyeing the introductory sentence now that you've moved it to the same level as the search box— it feels both broad _and_ hard to parse somehow.

Our search bar already has "candidates and committees" in the placeholder. Could we winnow this sentence to something like:
> Find details about fundraising and spending in federal elections.
(I'm feeling a little subversive here, but I'm wondering what would happen if this text even went away completely? With the header and the placeholder text, I feel like we've already pretty much conveyed what's in the intro sentence?)

Speaking of placeholder text, the word "profile" is throwing me— I like it in our mega-menu, but it doesn't feel like the right word to have in this box. Could it be:

> Search candidates and committees

**Comment by emileighoutlaw** [comment]
## Suggested content for hero sections:

> ## Campaign finance data
>See how money is raised and spent in federal elections.

--

> ## Registration and reporting
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they make regular reports about their financial activity.

>Learn more about those groups and the requirements that apply to them.

--

> ## Legal resources
Find details on the laws and regulations that govern federal campaign finance.




What I like about this draft is that each ends with an action-oriented sentence. It's clear what the user can do in the section. Issues with this? Let me know!

**Comment by jenniferthibault** [comment]
+1 to action-oriented closer = 👍 

💭 Looking at the three together, Registration and Reporting's first intro sentence is a really nice bit of context that CF Data and Legal could also benefit from. It would be nice to keep the parity across the board of: 
1: Intro sentence or two:  _the why_ or maybe _why this exists_
2: Action sentence: _what you can do_

Could we?

**Comment by emileighoutlaw** [comment]
Yes we can! :)

On Wed, May 25, 2016 at 3:27 PM, Jennifer Thibault <notifications@github.com

**Comment by emileighoutlaw** [comment]
Been jamming on this for a while. What do you think of:

> ## Campaign finance data
> Showing how money is raised and spent in federal elections helps the public make informed voting decisions. See the financial data for federal candidates and committees. 

--

> ## Registration and reporting
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they make regular reports about their financial activity.

>Learn more about those groups and the requirements that apply to them.

--

> ## Legal resources
> Candidates and committees rely on laws, regulations, Commission actions and court cases to follow campaign finance rules. Learn more about the legal components of campaign finance.

**Comment by emileighoutlaw** [comment]
Ready to have @amykort and @amypike take a gander at these unifying blurbs for our landing pages. What do y'all think about the above? 

Thank you!

**Comment by AmyKort** [comment]
Showing how money is raised and spent in federal elections helps the public make informed voting decisions. See the financial data for federal candidates and committees. 

I'm a little hung up on "showing," and I don't know why. We provide access to information about the sources of candidates' and committees' financial support. Is that the same as showing? Maybe it is.

**Comment by AmyKort** [comment]
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they make regular reports about their financial activity.

Learn more about those groups and the requirements that apply to them.

I like this, except maybe it's odd to say folks "make regular reports." Can we say the file regular reports?

Also, is it "those groups" or "these groups"?

**Comment by emileighoutlaw** [comment]
I hear you! Great comments. I'll post a revised draft here tomorrow morning! :)

**Comment by emileighoutlaw** [comment]
Thoughts
- In registration and reporting, great call on _file_ regular reports. That's more consistent with what I want to say across the site, anyway (I know file is a legal term, but whenever it applies, I want to use it!). Additionally, I think both _those_ and _these_ are grammatically correct, but I agree that _those_ reads a little funky. Let's go with _these_.

Question
- I hear you on the word "showing." But _make available_ didn't quite feel right to me. I tweaked the intro a little. Let me know what you think. I wonder if we need the second _voting_ or if we can just omit it and say "helps voters make informed decisions" or maybe "helps voters make informed election decisions." What do you think?

> ## Campaign finance data
> Making public how money is raised and spent in federal elections helps voters make informed voting decisions. See the financial data for federal candidates and committees. 

--

> ## Registration and reporting
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they file regular reports about their financial activity. Learn more about these groups and the requirements that apply to them.

--

> ## Legal resources
> Candidates and committees rely on laws, regulations, Commission actions and court cases to follow campaign finance rules. Learn more about the legal components of campaign finance.

**Comment by AmyKort** [comment]
I like it! Also, I completely agree about removing the second "voting."

**Comment by emileighoutlaw** [comment]
Awesome! We'll go with:

> ## Campaign finance data
> Making public how money is received and spent in federal elections helps voters make informed decisions. See the financial data for federal candidates and committees. 

--

> ## Registration and reporting
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they file regular reports about their financial activity. Learn more about these groups and the requirements that apply to them.

--

> ## Legal resources
> Candidates and committees rely on laws, regulations, Commission actions and court cases to follow campaign finance rules. Learn more about the legal components of campaign finance.

**Comment by AmyKort** [comment]
For legal resources, how about something more general--I think our audience is broader in population and needs.

The FEC provides public access to campaign finance legal resources and research aids. Explore the campaign finance statutes, FEC regulations, advisory opinions, relevant court cases, matters under review (MURs) and more.

**Comment by AmyKort** [comment]
(That statement gets more true the more content we add)

**Comment by emileighoutlaw** [comment]
That makes so much sense, and I agree that we don't want folks to feel this section is only for candidates and committees! 

So far in testing, people who are looking for advisory opinions and matters under review haven't have any trouble identifying that `Legal resources` is the place to find them. I'm wondering if we can wrap up all those types of things into a blanket "Commission actions" (or a similarly phrased list item) to prevent our list from becoming unwieldy?

How about:

> **Legal resources**
> Making these resources public clarifies the legal components of campaign finance. Explore relevant statutes, regulations, Commission actions and court cases.

**Comment by AmyKort** [comment]
What about "requirements" instead of components?

**Comment by emileighoutlaw** [comment]
Requirements is much better!


> **Legal resources**
> Making these resources public clarifies the legal requirements of campaign finance. Explore relevant statutes, regulations, Commission actions and court cases.


?

**Comment by AmyKort** [comment]
Yep. Or 
Making these resources public clarifies campaign finance legal requirements. Explore relevant statutes, regulations, Commission actions and court cases.

**Comment by emileighoutlaw** [comment]
I love it!

**Comment by AmyKort** [comment]
Thank you!

**Comment by emileighoutlaw** [comment]
👍 ⚡

**Comment by emileighoutlaw** [comment]
Reopening this quickly because my content critique group had trouble understanding the Campaign Finance blurb. @AmyKort, what do you think of the suggested new text they helped me draft:

## Campaign finance data
See how candidates and committees raise and spend money in federal elections. This financial data helps voters make informed decisions.

**Comment by AmyKort** [comment]
I like it. Thanks!

**Comment by emileighoutlaw** [comment]
Yay. re-closing
