### ISSUE TITLE
Content for data landing

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-style#360]
This is where I'll be keeping content thoughts related to https://github.com/18F/fec-style/issues/322#issuecomment-221297768

For @jenniferthibault and @noahmanger, I think it makes the most sense for me to [start a document](https://docs.google.com/document/d/1ZuatMQS9VUb0cD_MRqFHZto5Isd4O4rtmFoN7Nk4VXA/edit) with all the content for this section. If y'all want to suggest edits, please do, and if it looks good to you, you can also 👍 as is.

Once we're happy with it, I'm happy to work on implementation (alongside design) however we decide is best.

**Comment by jenniferthibault** [comment]
Sounds good! Thanks @emileighoutlaw !

**Comment by emileighoutlaw** [comment]
Updated doc ready for fresh eyes: https://docs.google.com/document/d/1ZuatMQS9VUb0cD_MRqFHZto5Isd4O4rtmFoN7Nk4VXA/edit

**Comment by emileighoutlaw** [comment]
This is definitely done. Can be moved to implementation here: https://github.com/18F/openFEC-web-app/issues/1229
