### ISSUE TITLE
Images not loading for cards

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#363]
![screenshot from 2016-05-24 18-49-06](https://cloud.githubusercontent.com/assets/509703/15525635/a438afb6-21e0-11e6-9dfd-2ce9e1026645.png)

https://pages.18f.gov/fec-style/section-components.html#kssref-components-buttons

I think the sample markup is just pointing to the wrong place.

**Comment by adborden** [comment]
Oh, it's in the handlebars template. Not sure if that's used elsewhere, that might make this more tricky.

**Comment by kwhaler** [comment]
It appears that paths need to reference the /fec-style/ directory.

https://pages.18f.gov/img/i-calendar--primary.svg
_should be_
https://pages.18f.gov/fec-style/img/i-calendar--primary.svg

Seems like a global issue (hopefully) resolved via config.

**Comment by noahmanger** [comment]
Thanks @kwhaler ! So, this works locally. Are we not running the [copy-images](https://github.com/18F/fec-style/blob/master/package.json#L16) command when building on 18F Pages?

**Comment by kwhaler** [comment]
Hi @noahmanger not sure what I am overlooking but it appears to me that it might be a relative URL issue (or the generation code). Image is here in the /fec-style/ directory https://pages.18f.gov/fec-style/img/api@2x.png   But the markup references `../img` 

![screen](https://cloud.githubusercontent.com/assets/611096/15843117/62839bf6-2c14-11e6-867a-8b5d7fe454b9.png)

**Comment by noahmanger** [comment]
Thanks @kwhaler and sorry for the delay. That did the trick!

**Comment by noahmanger** [comment]
Or at least I think it did. PR on the way...
