### ISSUE TITLE
Search results count missing padding

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#365]
I'm not even sure if this component should still exist, it doesn't fit the new messaging styles.

![screenshot from 2016-05-24 19-03-49](https://cloud.githubusercontent.com/assets/509703/15525878/73abb594-21e2-11e6-9945-8036fa15fe02.png)
https://pages.18f.gov/fec-style/section-components.html#kssref-components-search-results-count

**Comment by jenniferthibault** [comment]
Nope, this instance isn't supposed to be an alert anymore. Smite it!

**Comment by noahmanger** [comment]
Ah, this is just a case of the styleguide markup lagging behind real life. We just need to remove the `message--alert` class from the example.

**Comment by noahmanger** [comment]
No longer an issue.
