### ISSUE TITLE
Suggest publish to NPM via Travis

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#368]
This is a placeholder for the discussion, I'm only bringing this up as a suggestion. [Travis supports publishing to npm](https://docs.travis-ci.com/user/deployment/npm/) based on git tags.

Pro:
- Consistent builds/packaging
- Anyone with push access to fec-style can publish to npm; avoids having to make everyone an npm owner
- More consistent with how we deploy other apps via creating branches/tags
- Fewer steps to publish

Con:
- An extra step on travis you might need to debug

The release would look like this:

    $ git checkout master
    $ npm version <patch|minor|major>
    $ git push origin master --follow-tags

And travis takes care of the rest. You could even match the tags from git flow's publish command and use git flow to manage the release, like we do other apps.

**Comment by noahmanger** [comment]
Seems like a good idea to me. But I'll defer to people more experienced in the matter.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/477
