### ISSUE TITLE
Implement design changes to hero template

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#370]
Background on visual design here: https://github.com/18F/fec-style/issues/330#issuecomment-220986174

Copy for all sections is in progress here: https://github.com/18F/fec-style/issues/356

![hero-desktop-data copy](https://cloud.githubusercontent.com/assets/11636908/15584645/83e737fe-2349-11e6-9160-5742ff4c112c.png)

![hero-desktop-legal copy](https://cloud.githubusercontent.com/assets/11636908/15584644/83e6ac30-2349-11e6-9c23-a7ba68c20996.png)

![hero-desktop-regreport copy](https://cloud.githubusercontent.com/assets/11636908/15584646/83ee50e8-2349-11e6-832f-d50483abd3ef.png)

_____________________________

This will impact some space & placement of elements on the data landing page and legal resources landing page, as you can see through the pink screens. Due to this, on the data side, we may want to hold on implementing this template on any pages until work begins on https://github.com/18F/openFEC-web-app/issues/1229
 
cc @adborden @noahmanger @emileighoutlaw

**Comment by jenniferthibault** [comment]
Whoops. Just realized I still need to find real images 😬 
As a template, this is all still good to go

**Comment by emileighoutlaw** [comment]
Here's our nifty new content for the implementation:



> ## Campaign finance data
> Making public how money is received and spent in federal elections helps voters make informed decisions. See the financial data for federal candidates and committees. 

--

> ## Registration and reporting
Federal candidates and political committees must register with the FEC when they reach certain thresholds. Once registered, they file regular reports about their financial activity. Learn more about these groups and the requirements that apply to them.
--

> ## Legal resources
> Making these resources public clarifies campaign finance legal requirements. Explore relevant statutes, regulations, Commission actions and court cases.

**Comment by noahmanger** [comment]
**Criteria for completion**
- [ ] Data landing page is updated
- [ ] Reg & reporting landing page is updated
- [ ] Legal page is updated

**Comment by emileighoutlaw** [comment]
I want to try to get in another change to the content.

**Comment by jenniferthibault** [comment]
From @emileighoutlaw  in https://github.com/18F/fec-style/pull/388#issuecomment-224299796, which adds the images, final copy for the data header. 

> ##Campaign finance data
> See how candidates and committees raise and spend money in federal elections. This financial data helps voters make informed decisions.

**Comment by emileighoutlaw** [comment]
Woohoo. Thank you! Didn't realize I hadn't added the updated content to this issue.

**Comment by jenniferthibault** [comment]
Working with @edmullen , we found a way to help with transitioning the search functionality on data/legal out of the hero space, and doing so by creating a predictable pattern. 

We've created a panel with $gray-lightest` that contains the search bar. 

The search bar has two width variations: 
- full-width 
- half-width

And two functional variations:
- Able to specify categories to search in (in this case, on legal resources)
- Combined search (in this case, candidates/committees, I know this functionality isn't implemented yet, but since it's intended, I've designed according to that)

On legal, where the priority action is to search among the resources, 
![screen shot 2016-06-10 at 1 17 26 pm](https://cloud.githubusercontent.com/assets/11636908/15973926/c690baa0-2f13-11e6-95be-208b712a7313.png)

On data, the search is the feature users want most, but is one of many features available on the data side, that aren't inter-searchable, so we didn't want to make the mage look like the search applies to everything below it. 

![screen shot 2016-06-10 at 1 17 46 pm](https://cloud.githubusercontent.com/assets/11636908/15974033/6eca8bba-2f14-11e6-965e-23721b4cfd36.png)

We think these two scenarios are representative and flexible enough to handle other times we need the search in the future. I've put this thought stream here, because implementing the new hero template makes this layout adjustment to the rest of the landing page content necessary, and we wanted @adborden and @noahmanger to see it & decide how to handle the tasks of implementing these landing changes together. Feel free to spit out separately.

**Comment by adborden** [comment]
:+1: great work. In the half-width case, would the search bar ever include the category dropdown? It looks like it might be a tight fit.

**Comment by jenniferthibault** [comment]
Is "I hope not 😬 " an acceptable answer?

Good point, and in the first implementation of this for the data side, the candidate/committee search won't be combined, so we will need the dropdown, and it is tight, even after condensing some space. Any ideas?

![screen shot 2016-06-10 at 5 41 54 pm](https://cloud.githubusercontent.com/assets/11636908/15979575/cb734a1e-2f32-11e6-99fa-71b6d40bd23f.png)

**Comment by edmullen** [comment]
Conceptually I think the dropdown is probably inappropriate in the half width version. In the Profiles example, the Profiles content is describing the scope of the search bar. Having that description of the search bar scope _and_ being able to change the scope seems contradictory.

@jenniferthibault would you be open to starting with the full width version and switching to the half once the merged search is ready?

**Comment by jenniferthibault** [comment]
I'm only sort of sad to lose the icon, but the full-width keeps it a prominent feature, and it's not a total deal-breaker. 

I'm wary that the full-width search bar looks like it's searching the content on the rest of the page, but that's something we can observe through testing. If we were able to move the word "profile" into the dropdown (Committee profiles, Candidate profiles) instead of a title, that also seems like it will help limit the perceived scope of the search. Meaning that hopefully, people won't confuse it for a universal search.

![screen shot 2016-06-10 at 5 55 22 pm](https://cloud.githubusercontent.com/assets/11636908/15979903/09e888f2-2f35-11e6-9be9-44de93c52fc5.png)

**Comment by noahmanger** [comment]
Resolved on CMS and web app.
