### ISSUE TITLE
Find images for the landing page hero templates

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#371]
Find images for the space reserved in the template from #330 

- [x] Image for data hero
- [x] Image for registration and reporting hero
- [x] Image for legal resources hero

**Comment by jenniferthibault** [comment]
Here are some concepts for each: Conceptually I feel like good about these as starters for Data & Legal, but I've been trying out a few different options for Registration & Reporting. 

### Data:
- Yes, this site is a digital collection of data, and a photo of microfische records, but the fact that the FEC has been doing open data since practically forever (yes, my millennialism is showing :) ) is one I think makes a strong reference.
- I took this photo of the FEC records room the last time we were there, and I chose it to show a a tie to historical data, and because the image of the records room really stuck me on the scale of the FEC's records and data.
- The image isn't the best angle: next time I'm in DC I'd love to reshoot to get a better angle, or possibly ask Jim Jones from the FEC to take a few. For now, I've chosen a crop that gets an office and a date label, and also has a lot of depth to show how much data we're talking about.

![screen shot 2016-05-27 at 4 09 49 pm](https://cloud.githubusercontent.com/assets/11636908/15620059/fc69fd92-2425-11e6-8c56-153b28c39a3d.png)

### Legal:
- I'm aiming to find a very FEC-specific legal reference, rather than generic. The FEC meeting room speaks volumes to this in my mind's eye, and the six chairs are nice references to the commissioners as the legal decision makers.
- Although you don't see the whole room, it's a memorable one and strikes me immediately since I've been in it. I'm wondering if the reference is strong enough for those who haven't seen the inside, but if not, I think the chairs give a strong official feeling.
- I haven't been in any of the legal offices at the FEC: are there other striking, specific image references from the space that we could make, @edmullen ?

![screen shot 2016-05-27 at 4 10 20 pm](https://cloud.githubusercontent.com/assets/11636908/15620064/04778702-2426-11e6-80ae-26b8c48962c4.png)

### Registration & Reporting:
- This one is by far the toughest. @emileighoutlaw and I chatted and thought that exploring campaign activity images (like rallies, or events) would be a good starting point, so I've captured a few variations of that here.
- There's a tough balance to strike of images that feel textural, and not candidate specific, so I've tried a few "zoom" levels

![screen shot 2016-05-27 at 4 10 49 pm](https://cloud.githubusercontent.com/assets/11636908/15620085/1d9100c4-2426-11e6-907e-b8f06d3e5611.png)

![screen shot 2016-05-27 at 4 11 05 pm](https://cloud.githubusercontent.com/assets/11636908/15620084/1d90d914-2426-11e6-8789-74a4335d8b24.png)

**Comment by noahmanger** [comment]
I dig these. Totally agree with your choices for the first two. But yeah, the third is tricky. Of those options, I think I prefer the third. I think the others just don't read as clearly. I could also see taking it in another direction to emphasize the experience of the person filing these reports: maybe pictures of people at desks or using computers? I seem to recall you had something like this in early moodboards.

**Comment by emileighoutlaw** [comment]
Conceptually, people are the ones registering and reporting. So I *do* like having people featured in the picture. I like the zoomed out nature of the second one, maybe because the first one feels like a sea of white dudes.

**Comment by jenniferthibault** [comment]
R&R is indeed tough! I moved away from paper/screens because after talking with Emileigh, there are so many different tools & ways that different entities register and report, that it felt like a vague connection. 

Was looking in to campaign activities (gatherings, rallies) because those are ubiquitous _activities_ for candidates and their committees that have passed the _thresholds_ (emphasis because those are mentioned in the copy). 

I agree about the white dude tidal wave of the first, and was reticent to suggest it at first because of that. However the scale of that image feels the best to me, in context of the other two, which are much more close range. I'm going to keep searching govt photo databases along that theme, and will look for crowds with a better spread of women & non-white people. I wish I could say this will be an easy search. If this leads me nowhere though, it may be better to start off with the screen-oriented theme.

**Comment by emileighoutlaw** [comment]
I am not surprised and don't envy you that search. I remember us having
similar issues when we were looking for diverse images for Every Kid in a
Park 😑

On Tue, May 31, 2016 at 1:50 PM, Jennifer Thibault <notifications@github.com

**Comment by edmullen** [comment]
I initially thought that you were planning to use the blurry photo in the previous sketches, which I kind of liked, but I get it's abstract. This is a difficult task, and one that will need to be repeated for each section. For legal, the only things that come to mind are the hearing room and the legal library, but unlike your comment about FEC being a longtime open data participant, the library doesn't speak to pioneer status. I think the chairs are as good a physical reference to the commission. The current image and cropping feel a bit tomb-like and the room seems to be without sunlight. Maybe when you get the data image you could  get one at a slight angle with the shades open to express the 'sunlight is the best disinfectant' idea.

**Comment by jenniferthibault** [comment]
Funny @edmullen — that image is the brightest and most naturally lit scenario I've ever seen of the meeting room! I have a different crop of a different image that breaks away from the chair backs, and gets a little more abstract, which feels more in line with what I was aiming for:

![screen shot 2016-06-03 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/11636908/15787430/66da73e0-2990-11e6-8af9-5ec4258e3513.png)


For registration and reporting, I have a different crop of an earlier image that I had left on the cutting room floor, but the more I look at it, the more I come back to it being a decent option to start with:
- It shows a hint of a podium and speaker, as if it's a campaigning activity
- It shows people, but the blur effect I added keeps it distanced
- Even though it's blurred you can recognize women and people of color in the crowd
- The table (again, not super obvious) looks like a place where you'd expect to register for an event or something. It nods to "registration" of sorts.

![screen shot 2016-06-03 at 1 37 03 pm](https://cloud.githubusercontent.com/assets/11636908/15787447/84dea8ca-2990-11e6-90b8-d63b0c109c75.png)


These two, plus the data image above are the ones I'd feel good about moving forward with to show the FEC, unless folks want to talk through counter points?

**Comment by jenniferthibault** [comment]
Criteria for completion:
- [ ] review with FEC at demo on Monday
- [ ] export images

**Comment by AmyKort** [comment]
Thanks so much for all of your thoughtful work. These look great!

**Comment by jenniferthibault** [comment]
Thanks for all the helpful feedback everyone! I'm excited about where we've landed. These images were added in this pull request: https://github.com/18F/fec-style/pull/388
and we've moved these forward to implementation in: https://github.com/18F/fec-style/issues/370
