### ISSUE TITLE
fec-style depends on hbsfy but doesn't package it

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#373]
Using fec-style in another project and running into an error with browserify.

My code:

``` javascript
var SiteNav = require('fec-style/js/site-nav').SiteNav;
```

Error:

```
Running "browserify:dev" (browserify) task
>> /home/adborden/projects/fec/fec-eregs/node_modules/fec-style/js/templates/nav-data.hbs:1
>> <div class="mega">
>> ^
>> ParseError: Unexpected token
```

The issue is that the fec-style build depends on hbsfy to bundle the handlebar templates, but this is not  documented.

Either we should document the dependencies that your app must install (maybe via peerDeps) or bundle the dependencies in fec-style. I'm not sure of a good way to bundle build plugins like this.

It kind of reminds me of my coffeescript days, where we built the npm package to export the compiled javascript. So in this case, the npm package would have already browserified the handlebar templates,  and just export a template function or the handlebar template string itself.

**Comment by noahmanger** [comment]
Ah! Good catch. Is there a downside to just compiling it all in fec-style and exporting it?

**Comment by adborden** [comment]
The downside is that the that an app requiring `fec-style` would bring in the entire javascript, rather than include it file by file. I think there are some better ways to bundle this kind of stuff these days. There's a way to register parsers with node's require. Then it's transparent to the consuming app.
