### ISSUE TITLE
Add style for alt--primary dropdown lists

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#375]
Just caught this [on the calendar](https://beta.fec.gov/calendar/), which looks to be a misapplied style, or applying a style that we don't have set?

![screen shot 2016-05-31 at 9 23 15 am](https://cloud.githubusercontent.com/assets/11636908/15687963/b7d75de6-2745-11e6-9856-28390f44ba25.png)

I believe that the calendar is the first place we've implemented a dropdown style that isn't the default neutral. Looking at [the style guide](https://pages.18f.gov/fec-style/section-components.html#kssref-components-dropdowns), I don't believe we have a style set for this. Is that correct @noahmanger ? Or do we have one, but haven't listed it in the style guide? 

Since this makes the feature illegible, glad to prioritize it for this week's release, once I know which scenario we're in.

**Comment by noahmanger** [comment]
Got it! Simple fix.
