### ISSUE TITLE
Provide a more descriptive empty state for dropdowns

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#384]
Currently, when a dropdown filter has no options selected, the button just says `Select`. In order to communicate that this state means all options are included in the displayed results, add a more descriptive empty state to the button itself. For example, if no states are selected, have the button say `All states` and then change to `Select` or something generic after one is selected.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-pattern-library #16](https://github.com/18F/fec-pattern-library/issues/16) via [**ZenHub**](https://www.zenhub.com/)
