### ISSUE TITLE
SiteNav::switchMenu does not account for scrollbars

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#385]
At around ~864px, I see the mobile nav unstyled. Once over the large breakpoint (860px) it should be removed. The reason is the body width calculation doesn't account for scrollbars.
![screenshot from 2016-06-02 18-13-33](https://cloud.githubusercontent.com/assets/509703/15796255/c7dafb78-29af-11e6-9936-8ecb39e2f052.png)

Here's some background on the issue: https://github.com/jquery/jquery/issues/1729. As of jquery 2.2, you can use `$(window).outerWidth()` to compute this properly.

**Comment by noahmanger** [comment]
:shakes_fist: _scrollbaaaaaars_!!!

**Comment by adborden** [comment]
Gaaa, sorry, accidently committed this to master. I pushed a revert and will submit a PR proper.

**Comment by adborden** [comment]
In the future, `window.mediaMatch` might also be an option https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
