### ISSUE TITLE
Hamburger menu icon not universally understood as trigger for mobile menu

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-style#396]
User did not understand the hamburger icon was the trigger for the menu. 

🔧 Hamburger menu might not be effective for various users different levels of computer literacy/less text and mobile savvy users.

[Navigation feature set in research repo](https://github.com/18F/FEC/blob/master/feature_sets/ia_primary_nav_menu.md)
tagging: @jenniferthibault @noahmanger @jeanninehunter @emileighoutlaw @edmullen as likely interested parties.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-testing #101](https://github.com/18F/fec-testing/issues/101) via [**ZenHub**](https://www.zenhub.com/)
