### ISSUE TITLE
Create a new pattern for form validation-style alerts

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#416]
So that users can tell if their filter inputs are acceptable or need to be adjusted more quickly, design a new alert pattern appropriate for form elements. 

This would be used in place of this alert pattern here
<img width="292" alt="screen shot 2016-07-01 at 12 24 21 am" src="https://cloud.githubusercontent.com/assets/11636908/16511813/6dec2b04-3f22-11e6-93e8-dbe127bd1776.png">

And here
![screen shot 2016-07-01 at 12 31 42 am](https://cloud.githubusercontent.com/assets/11636908/16511866/34b7a858-3f23-11e6-9614-4a925fa09ad3.png)

**Criteria for completion**
- [ ] Visual styles for success & failure have been established
- [ ] When an input isn't valid, users are alerted to the problem and given guidance on how to fix it
- [ ] When an input is accepted, users understand that is has been accepted

Relevant issues:
https://github.com/18F/openFEC-web-app/issues/1303
https://github.com/18F/openFEC/issues/1727

**Comment by jenniferthibault** [comment]
I'm thinking we should map closely to the [US Web Design Standards](https://standards.usa.gov/form-controls/) system here. 

![screen shot 2016-07-08 at 7 17 32 pm](https://cloud.githubusercontent.com/assets/11636908/16704031/afcdeffc-4540-11e6-990d-277c107a9e46.png)


But with a few customizations to make them fit our system:
- Slight tweaks to colors so that the colored text can be used over our `grey-lightest` background and meet 508 standards
- Moves the response message to be below the field instead of above, to accommodate the titles

### Response color schemes:

**Success (green)**
border color: USWDS `green-light`: `#4AA564`
text color: `#287538` a slightly darkened version of USWDS's `green` variable

**Error (red)**
border color: USWDS `secondary-dark`: `#CD2026 `
text color: USWDS `secondary-dark`: `#CD2026 `


These designs don't address any real interaction design changes (and especially don't address known issues with the date field entry interaction), but are rather meant to show placement of alerts, and style, across different implementations.

![form-validations-date](https://cloud.githubusercontent.com/assets/11636908/16704062/ecc72f40-4540-11e6-98e5-ec6b8ac988d3.png)


![form-validations](https://cloud.githubusercontent.com/assets/11636908/16704094/3771ef80-4541-11e6-9c36-667fa32f0ed2.png)

cc @noahmanger @onezerojeremy

**Comment by noahmanger** [comment]
I don't have anything to offer other than this is looking really good. Is there anything else you want to do on this issue before closing?

**Comment by jenniferthibault** [comment]
Nope! If you 👍 then it's ⚡ 🚀
