### ISSUE TITLE
FEC header logo is cutoff on smaller screens

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#421]
At width ~960px, the FEC header is cutoff on all/most pages of https://beta.fec.gov/

![screenshot from 2016-07-07 16-04-43](https://cloud.githubusercontent.com/assets/509703/16672784/38f31ec2-445d-11e6-885f-c692e449f8cd.png)

**Comment by ccostino** [comment]
If you resize your window to anything smaller than 960px, you'll see that the logo gets more covered the smaller you make your viewport.  Appears to be a site-wide style issue with the header.

**Comment by noahmanger** [comment]
Resolved in the latest fec-style version.
