### ISSUE TITLE
Candidate summary figures not matching the Committee's figures

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-style#433]
Example:
Charles Schumer:
https://fec-dev-proxy.18f.gov/data/candidate/S8NY00082/

Total Receipts value is $23.7 million 
Total Disbursements is $6.8 million

Both of these are inflated.

Friends of Schumer (his only committee)
https://fec-dev-proxy.18f.gov/data/committee/C00346312/?cycle=2016

Total receipts value is $15.9 million 
Total Disbursements is $2.2 million
Both of these agree with the fecp data and with the CC Viewer.

Both the candidate and the committee should show the $15.9 million value.

**Comment by jwchumley** [comment]
Here is a candidate /  committee that doesn't have the above issue. I'm finding some of each.

https://fec-dev-proxy.18f.gov/data/candidate/S8WI00026/
https://fec-dev-proxy.18f.gov/data/committee/C00578013/?cycle=2016

**Comment by LindsayYoung** [comment]
For Schumer do you think you might have been comparing a 6 year cycle to a 2-year cycle on the current site? This is what I am seeing

Full cycle:
https://fec-dev-proxy.18f.gov/data/candidate/S8NY00082/?cycle=2016&election_full=true
Total receipts
$23,677,187.71
Total disbursements
$6,780,968.03
Ending cash on hand
$27,088,272.72

2-year looks ok to me:
https://fec-dev-proxy.18f.gov/data/candidate/S8NY00082/?cycle=2016&election_full=false
Total receipts
$15,863,651.74
Total disbursements
$2,185,362.79
Ending cash on hand
$27,088,272.72

**Comment by jwchumley** [comment]
Um. Embarrassingly enough, yes.
