### ISSUE TITLE
District capitalization

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-style#436]
I just noticed our style for `district` is inconsistent:

<img width="268" alt="screen shot 2016-07-25 at 4 32 21 pm" src="https://cloud.githubusercontent.com/assets/10552702/17121042/803e51ee-5285-11e6-9f80-9ceb8fae6967.png">

Do we want it to be capitalized or not capitalized? 

**Capitalized**:
There are 16 Districts in Ohio.

**Lowercase**:
There are 16 districts in Ohio.

👀 at @amykort and @amypike if there's a preferred FEC style on this. If not, we'll just pick one and make a thorough pass on the website for consistency.

**Comment by amypike** [comment]
@emileighoutlaw, I did a quick survey of our publications and "district" is normally not capitalized.

**Comment by emileighoutlaw** [comment]
Perfect! Lowercase is my preference, too.

In situations where we talk about a specific district, a lá `District 12`, I _do_ think district should be capitalized, as we do with all proper nouns. What do you think?

**Comment by emileighoutlaw** [comment]
@jameshupp and @jamiealbrecht — this is another great future Jamie eagle-eyes-copyeditor task 💟
