### ISSUE TITLE
In order to have access to recent improvements, bug fixes, and accurate documentation, update to latest version of typeahead.js

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#44]
We're using an older version of typeahead.js, which means we don't have access to recent improvements and bug fixes, and it's hard to find accurate documentation (Twitter doesn't surface documentation for old versions in an accessible way). This is a low priority, but we should upgrade to the latest version, time permitting.

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/l2oCx5HOcS-6eDnUEFZhfg

**Comment by noahmanger** [comment]
New issue: https://github.com/18F/fec-style/issues/232
