### ISSUE TITLE
Fix calendar filter counts

### ISSUE THREAD

**Issue by ccostino** [18F/fec-style#449]
The calendar filters were susceptible to an issue that is being temporarily fixed by #448, but we want to look into this further and fix it more appropriately.  From the PR:

> This is a temporary fix to prevent a bug from shipping out, but we'll want to actually fix this eventually. Here's the problem: the calendar filters each have the same name attribute: category. So the check that we have on the handleAddEvent method to see see if the event name === the filter name passes for all of them on every filter:added event.

> The reason they all share the same name is that we really just have one API filter for category but on the frontend we break it out by different subgroups. That's what the MultiFilter class is designed to handle.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/522
