### ISSUE TITLE
Implement new financial range filters

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#458]
In order to make financial range filters easy to use and read, implement the new financial range filter design from https://github.com/18F/openFEC-web-app/issues/1493

![image](https://cloud.githubusercontent.com/assets/11636908/17502981/3547dc88-5dba-11e6-8fe3-58bddde120fc.png)

**Criteria for completion:**
- [x] Min and max filters display side-by-side, with a single button and hyphen in between
- [x] Text input is right aligned
- [x] The $ is always visible as a background image
- [x] Submitting either of the inputs triggers the loading and success state in the button

**Comment by jenniferthibault** [comment]
Corresponding tag designs are in https://github.com/18F/openFEC-web-app/issues/1542

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/484 . Nice work!

**Comment by noahmanger** [comment]
Because we're not acting on the changes to the tag design yet (and have that captured in another issue), I'm closing this.
