### ISSUE TITLE
Audit & reconcile main heading styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#467]
We've generated a few page types that all use identical, or close-but-a-little different heading styles, that I think I can clean up. This will be a light visual lift and hopefully a light front end dependency.

On the following pages:
- Essentials pages
- Article pages (checklist items)
- AO pages
- Missive templates

After synthesizing the patterns, update the style guide with documentation when this moves to implementation.

**Comment by jenniferthibault** [comment]
While pairing with @adborden to set up the Advisory Opinion landing page and canonical page templates, we found some inconsistencies in how our h1 styles are designed, built, and implemented. 

I hoped to improve these by auditing the styles in place, finding areas for refinement and simplicity, and (with front end help) possibly refactoring the page templates as needed to use fewer classes overall, by designing more common classes.

The timing for this is good now because the legal resources sections are growing into templates quickly, and the Press/news page templates are just about to be build. Refining the classes before those templates are built will help us nip this meandering pattern in the bud before it gets unruly. 

There's a reaaalllly big imge of the audit below, where the first column shows the current design, the second shows the code classes applied, and the third shows a screenshot of me fiddling with design changes in the inspector, or some notes/questions.

Overall I notice two main patterns to our h1's:

1. When they are used as article titles (orange dots)
  - variation: followed by a subheadline
  - variation: used in a hero pattern for a section (red dot)

2. When they are used in data table results (blue dots)
  - variation: when they are used for search results (dark blue dot)

For all instances of scenario 1 , the most meaningful change I can see is to set one common font and line-height size for all of them. (I've recommended 3.6 rem). 

I think there's a huge opportunity to refine our base pattern in these instances and reduce the number of modifying classes, but I'm not entirely sure what that approach is. @noahmanger and @adborden , what do you think we can do here to make these more efficient?

For scenario 2, I think it makes sense for these to remain a little smaller than scenario 1's (the current 3 rem is ok) because they are introducing tables or lists rather than articles. It seems like we could improve the formatting on the legal search results h1 here by making that format match the other table h1's. What do you think?

![h1-audit copy](https://cloud.githubusercontent.com/assets/11636908/17939856/5d33c56c-69fa-11e6-945b-50cafd1813ac.png)
![h1-audit-2](https://cloud.githubusercontent.com/assets/11636908/17940452/3dd83baa-69fd-11e6-92de-fa37f5bbae6e.png)

**Comment by jenniferthibault** [comment]
Small update: on scenario 1 I found another instance of upcoming pages that rely more strongly on incorporating the icon with h1 styles: the data breakdown page templates:

<img width="861" alt="screen shot 2016-08-24 at 3 46 12 pm" src="https://cloud.githubusercontent.com/assets/11636908/17945508/28f5beb4-6a12-11e6-8a9b-b0cca6aded6b.png">

With more real need for icons on these pages, I'd take back my earlier suggestion for removing them from the advanced data pages, and instead implement the pattern with more detail, as illustrated in this issues' screenshot of the design file:
- the underline should go under the icon, and be the full-width of the text container
- the icon should be at the vertical optical centered with the h1 text

**Comment by noahmanger** [comment]
This is awesome! Super thorough and really helpful to see. I'm sure we'll be able to reduce the styles into a few common ones. Sorry, nothing more to add.

**Comment by jenniferthibault** [comment]
I was thinking about how to move this forward, and I think I can do a little bit more to make sense of things before we move in to front end refactoring. I'm going to try to abstract out the basic templates with grids & markup. This won't take long, so I think that it and still move to front end implementation this sprint.

**Comment by noahmanger** [comment]
This is great! Really helpful to document the vertical spacing like this. Only question I have is what font size things should be on smaller screens? We've been reducing the size of certain headings at smaller breakpoints.

**Comment by jenniferthibault** [comment]
Gosh, I can make up a number, but without looking at the whole system that's hard to say. (I didn't realize we were already doing this, since I remember that task being firmly ice-boxed. Exciting! But also makes me realize how far from the code I am.)

What exists already that could help make a more logic-based choice?
- Are there existing h1 mobile sizes?
- Are there existing h2 mobile sizes for comparison?

**Comment by noahmanger** [comment]
This can also be something we pair on, too. But FYI the code is all [here](https://github.com/18F/fec-style/blob/master/scss/mixins/_type-mixins.scss). The default style is the mobile style, and then the sizes adjust at the `$med` breakpoint.

**Comment by jenniferthibault** [comment]
I think pairing together feels like the best way to make that size choice.

Ok to move this to implementation? We could keep this issue open, or close & start a new front end targeted issue.

**Comment by noahmanger** [comment]
Let's do it!

**Comment by jenniferthibault** [comment]
@noahmanger could I enlist your help making an implementation issue from this? I'm not sure I know how you'd approach it.

**Comment by jenniferthibault** [comment]
@noahmanger ping! I don't see any new issues connected to this for implementation, and I'm worried it might fall through the cracks. Don't need to implement it this sprint, but I'd like to make sure an issue is created so that it's tracked in our task list for an opening. I could take a crack at drafting, but I'd like to at least chat with you first about what approach you think it right.

**Comment by noahmanger** [comment]
Implementation issue is here! https://github.com/18F/fec-style/issues/490

I was going to get to this this sprint.

**Comment by jenniferthibault** [comment]
Omg I made it and everything. Hello brain. 
I really couldn't give it much detail for completion criteria, but if you know your approach and are't worried, then sounds good. Thanks!
