### ISSUE TITLE
Bug: "Clear all filters" removes certain checkboxes

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#476]
In cases where dropdown filters have certain checkboxes pre-separated from the dropdown (like below), clicking "clear all filters" or the "x" on the tag deletes the checkbox in the filter panel and leaves the tag. 

![image](https://cloud.githubusercontent.com/assets/1696495/17745272/10317b28-6460-11e6-9109-efaa2dbad6f5.png)

Expected behavior: It should delete the tag and unselect, but not remove, the checkbox.

I _think_ this is a bug introduced by the new dropdown behavior. Can you take a look @xtine ?

**Completion criteria:**
- [ ] Make the fix
- [ ] Add tests

**Comment by xtine** [comment]
Yep, I'm pretty certain this was from dropdowns. I have most of it fixed in the new tags, but I will make sure the additional checkboxes from dropdowns won't be removed.

**Comment by xtine** [comment]
Just for clarification, the checkboxes that should never be removed that have a dropdown underneath are:
Candidates
- Political Party (Democratic Party, Republican Party)
Filings
- Amendment Indicator (New, Amendment)
Committees
- Political Party (Democratic Party, Republican Party)
- Independent Expenditure Committees (Super PAC)
- Other Committees (Joint Fundraising)

I plan on setting a data attribute on these in the template to mark as non-removable.

**Comment by noahmanger** [comment]
That looks right. If you're in the checkbox.html macro, it's all the ones generated by the `checkbox_list` macro.
