### ISSUE TITLE
Filters creates a right gutter on mobile

### ISSUE THREAD

**Issue by adborden** [18F/fec-style#488]
There's a `.filters label::after` rule that creates a 20px gutter on the right side of the screen for mobile. Looks like it's for the loading animation but acting up on mobile.

<img alt="screenshot from 2016-08-25 18-36-22" src="https://cloud.githubusercontent.com/assets/509703/17991381/ece781e6-6af2-11e6-9971-4fb5cbc80ee8.png" width="300">

**Comment by adborden** [comment]
Digging a little deeper, it's because the label on the search text field is so wide, having the `label::after` hangs off the page. setting `position: relative` on the `.filter` class helps, but there's still a bit of a gutter.

**Comment by xtine** [comment]
@adborden: Is this still an issue? Tried to load this at mobile size and it looks fine to me:

<img width="330" alt="screen shot 2016-09-19 at 3 11 28 pm" src="https://cloud.githubusercontent.com/assets/24054/18650721/6c75286e-7e7b-11e6-9a5b-8d533d0e5536.png">

**Comment by adborden** [comment]
Yep, still an issue https://fec-dev-proxy.18f.gov/data/candidates/?election_year=2012&election_year=2014&election_year=2016&has_raised_funds=true

Just scroll right. I'm on linux, but I see it in every browser, chrome, firefox, and epiphany (webkit)
![screenshot from 2016-09-19 17-13-40](https://cloud.githubusercontent.com/assets/509703/18653114/8d50dbee-7e8c-11e6-8c5d-1394d6faf63f.png)

**Comment by adborden** [comment]
It also happens on my mobile, but only when the filters are open. If you still can't repro it I'm happy to pair with you on it.

**Comment by noahmanger** [comment]
Yeah, I've seen this too. I think in iPhones it defaults to zooming you in so you don't notice it, but if you scroll over it's there.

**Comment by xtine** [comment]
Ahh, I didn't see it because I didn't try to scroll right. Just pushed up a fix.

**Comment by noahmanger** [comment]
Resolved by #518
