### ISSUE TITLE
Reinstate dev/staging/feature banners on those environments

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#489]
We used to have banners on our dev and staging sites that could help tell you what you were looking at in a more human-readable way than our URLs.

These seemed to disappear at some point and I'm not sure why (and since this was also a surprise to @noahmanger , I'm guessing it wasn't on purpose?) It would be really helpful to have them back.

**Comment by noahmanger** [comment]
I believe this happened because we lost the environmental variables somewhere along the way. Does the `environment` env variable need to be set in Travis? cc @adborden

**Comment by adborden** [comment]
Awww my bad. Yeah I think you're right, we dropped the environment variables at some point. I suspect they should be in the manifest files. I'll take this one.
