### ISSUE TITLE
Reconcile h1 main headings

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#490]
Based on https://github.com/18F/fec-style/issues/467 , reduce the number of classes it takes to build a main header, and implement them consistently across templates. 

(Holding for final designs)

**Comment by noahmanger** [comment]
@jenniferthibault ran into a little snag. If all `headings` have 30px margin at the bottom, how should the press release / digest heading pattern work. Here's what it does by default with the new styles:

![image](https://cloud.githubusercontent.com/assets/1696495/18730473/5b61ebe8-800b-11e6-9aab-cca3cb630e67.png)

**Comment by jenniferthibault** [comment]
@noahmanger is the problem with that screenshot that the button is creating additional clearance?

Sorry, if that's not what you mean, then I'm not really sure what the snag is.

**Comment by noahmanger** [comment]
Oh sorry. Yeah, so basically, by default, our `heading` class has 30px space below. Which when applied in this case forces extra space between the border and the button. So wondering if the design rule is "30px space between the heading and everything below it" or "count the button as part of the heading and the 30px should be below the button".

**Comment by noahmanger** [comment]
Bumping this again now that the release is out. @adborden do you want to take a look and see if there will be implications for any work you did between when I started this and now?

**Comment by jenniferthibault** [comment]
I'm diving in now to look around more thoroughly, but in general I think the rule is that the main text column and right-hand columns should align evenly at the top. In this case, the button should be in the right-hand column, not in a row above the body copy. It should look aligned, like the image in your CMS work:
https://github.com/18F/fec-cms/pull/509

**Comment by noahmanger** [comment]
Ah great! So it's in the "sidebar" column as part of the body, not part of the header?

**Comment by jenniferthibault** [comment]
Yes! Thanks for helping me understand.

**Comment by adborden** [comment]
@noahmanger there are, I have two PRs up, but I will update them.
