### ISSUE TITLE
To create a beautifully scaled experience on mobile, define mobile styles in style guide

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#5]
Bringing this over from OpenFEC.
We should build a style guide specific to mobile.

**Comment by msecret** [comment]
I think a cool thing to do here, for the KSS generated styleguide, would be to have a button the drinks the pages width so you can see what it would look like on mobile.

**Comment by noahmanger** [comment]
https://18f.storiesonboard.com/m/fec/!card/X8Hup180Dv1Y7TnTwpqTLg
