### ISSUE TITLE
Update DateFilter component to work with non-transaction-period dates

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#501]
We want to implement the new date filter style across all date filter instances, including those that aren't bound by a two-year transaction period. The code currently requires that for setting min and max years, though, so it needs to be updated in order to finish applying it everywhere.

**Comment by xtine** [comment]
Where are the instances of date filter that isn't bound by a two year transaction period?

**Comment by noahmanger** [comment]
Basically any transaction or report page other than receipts and disbursements. For example:
- http://localhost:3000/independent-expenditures/
- http://localhost:3000/filings/
- http://localhost:3000/reports/presidential/

**Comment by xtine** [comment]
Ah, is it the radio date selection? Is it just selecting date in the "custom" option or also within the cycle?

**Comment by noahmanger** [comment]
We want to replace the radio button pattern and instead have a single date-picker interaction. The difference being that these won't be restricted to any given two-year period. 

I think it's fine for the months to default to the months in years we're actually in, though. Maybe if you enter a date that's earlier the months don't show?

I don't know that we completely fleshed out the interaction here, so tagging in @onezerojeremy and @nickykrause if they have thoughts.

**Comment by jenniferthibault** [comment]
Recapping our convo today, we're going to start minimal, and use the same date text/entry boxes for Beginning and Ending fields, but remove the date picker interaction for non-cycle-bound instances altogether.

That looks like this:

![screen shot 2016-09-19 at 4 43 53 pm](https://cloud.githubusercontent.com/assets/11636908/18648386/6d94bee6-7e88-11e6-8b56-ab11a3aeaf0c.png)


TBD through testing is if users expect any graphic date selection aid to appear.

**Comment by noahmanger** [comment]
Resolved by #517
