### ISSUE TITLE
Date Filter picker doesn't properly select a date outside border radius click

### ISSUE THREAD

**Issue by xtine** [18F/fec-style#502]
Clicking outside of the border radius in a date grid square doesn't properly set a date:

![screen shot 2016-09-01 at 3 19 26 pm](https://cloud.githubusercontent.com/assets/24054/18389775/c155d210-76a7-11e6-94ea-6e1c67f9833c.png) <img width="280" alt="screen shot 2016-09-09 at 4 04 57 pm" src="https://cloud.githubusercontent.com/assets/24054/18389774/c1520e00-76a7-11e6-9133-f8ec3dd2bcb6.png">

**Comment by noahmanger** [comment]
While you're in the CSS, I just realized that these aren't looking too hot on mobile screens:
![img_1634](https://cloud.githubusercontent.com/assets/1696495/18535224/213b545e-7aa7-11e6-91a9-6b624abd5a58.PNG)

**Comment by noahmanger** [comment]
Resolved by #512 and #513
