### ISSUE TITLE
Implement new footer layout to accommodate Press section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#503]
Designs and convo carried over from https://github.com/18F/fec-style/issues/498

Using a four-column grid template with the [USWDS' Big Footer](https://standards.usa.gov/footers/#big-footer) we've created the next iteration of the FEC's footer design that will accommodate some of the expanding utility nav items, starting with the new Press section, and relocating the Contact section.

<img width="806" alt="screen shot 2016-09-09 at 10 42 14 am" src="https://cloud.githubusercontent.com/assets/11636908/18391761/126cdf2a-767d-11e6-9991-e1d6b5782f37.png">

The template also moves the GitHub links out of the bottom footer, so that would mean the first iteration of live links would be the following, until we know more about the later, more full IA:

<img width="806" alt="screen shot 2016-09-09 at 10 59 25 am" src="https://cloud.githubusercontent.com/assets/11636908/18391853/76e1ad00-767d-11e6-82eb-a49fc64bc138.png">

Moving the contact link down would adjust the utility nav in the header like so:

<img width="1266" alt="screen shot 2016-09-07 at 7 14 37 pm" src="https://cloud.githubusercontent.com/assets/11636908/18331923/65b07b68-7530-11e6-9b64-67273cc7938b.png">

Implementing this also incorporates the YouTube social media link and would resolve https://github.com/18F/fec-style/issues/201

cc @noahmanger / @adborden / @xtine for front end heads up

**Comment by xtine** [comment]
@jenniferthibault: can you export the social media icons? I just need icons in the style that the other icons in `fec-style/img/` are.

**Comment by jenniferthibault** [comment]
@xtine sorry for the delay!

Exported. Could you also add them to the style guide as part of this? 
A think to look out for when you load them into the style guide & generate it is that sometime exporting to SVG from the design program Sketch has bugs, and will turn it into a solid-filled blob, even though the image preview in Finder looks right. If that happens, let me know.

[social-icons.zip](https://github.com/18F/fec-style/files/496392/social-icons.zip)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1608
