### ISSUE TITLE
Gather inspiration for home page from FEC stakeholders

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#504]
In order to foster stakeholder participation and demonstrate how their participation is informing the design of the home page, we have a series of meetings & exercises planned for the coming weeks. This issue outlines one part, the rest may overlap or fall into  https://github.com/18F/fec-cms/issues/462

There will be a Wednesday meeting with FEC home page stakeholders in which the 18F team presents the principles for the home page design for discussion. Ahead of that meeting, we'll ask attendees to complete an exercise that gets them thinking about what kind of home page experience they think will be successful for the FEC's audience, by finding examples on other websites and sharing them with us.  (like summer reading!)

We'll use these examples and the provided rationale to find patterns and points of alignment across the stakeholders which will inform the first rounds of wireframes for the FEC home page. 

We'll then share these findings back to the group in a way that shows them what we heard overall, and top patterns we found that we'll pursue to test out. 

- [x] Determine meeting dates to set benchmark deadlines (cc @noahmanger )
- [x] Design exercise prompt (and get feedback from 18F team)
- [x] Provide examples
- [x] Decide & outline who the participants are
- [x] Share with the FEC by ____9/14____
- [x] Set due date for receiving feedback ____9/20____
- [ ] Synthesize feedback & identify patterns (carried over into a next step issue in https://github.com/18F/fec-style/issues/505)

cc @emileighoutlaw @nickykrause @noahmanger & @onezerojeremy : this attempts to recap yesterday's meeting.

**Comment by jenniferthibault** [comment]
I've been working on this in a [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1FWzLY2f8Fs2JkZb87KyM7XRIfpTH1q1vas-Te0HvrCE/edit?usp=sharing) and surfaced it for feedback in Slack. I think it's mostly wrapping up and ready to show our partners for answering questions about who they'd like to direct contact to.

Just wanted to drop some reactions from @nickykrause in here, because they're thoughts that have been floating in my head and I don't want to lose them, but I want to clean the doc up.

> I think this exercise gets at what we’re trying to find out. At first, I was asking myself if I thought we should include additional or more specific guidance--like, when we say “this would be helpful to the websites users because…”, to have the participants specify which user groups. But then I backed up and focused on the idea that (a) a lot of the specifics might come out in their responses, unprovoked, and (b) there is a lot of value in keeping the exercise really simple. If it’s simple, our synthesis will be easier. Also, people will actually do it! 
> I love that you provided an example; I think it can be difficult sometimes to determine what might confuse people and what won’t. We can wordsmith and whatnot to make this as clear as possible, but examples are also such a great, straightforward way to provide clarity (--NK)

Next steps are to check in with Amy & Wei about who they'd like to direct feedback to during the sprint planning today, and hand it over for them to send out.

**Comment by onezerojeremy** [comment]
This looks great!

**Comment by jenniferthibault** [comment]
Thanks everyone for the great review and quick thinking on this exercise. I just emailed it over to the FEC, which completes this issue in favor of synthesizing the results in https://github.com/18F/fec-style/issues/505
