### ISSUE TITLE
Add a screenreader-only class

### ISSUE THREAD

**Issue by toolness** [18F/fec-style#521]
Hello!  @emileighoutlaw brought up the accessibility of the "Learn more" links on the FEC site:

<img width="758" alt="screen shot 2016-09-06 at 10 29 37 am" src="https://cloud.githubusercontent.com/assets/10552702/18279911/dd48b2ae-741c-11e6-9e9b-6e536ce21db3.png">

We discussed this in https://github.com/18F/content-guide/issues/131 and decided that the most accessible solution would be to add a "screenreader-only" class (called e.g. `sr-only`) that makes text invisible to sighted users but read aloud by screen readers, and then use it to add important context to the "Learn more" links, e.g.:

```html
<a href="https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/">
  Learn more
  <span class="sr-only">about candidates and candidate committees</span>
</a>
```

The WebAIM guide on [Invisible Content Just for Screen Reader Users](http://webaim.org/techniques/css/invisiblecontent/) recommends the following rule for this:

```css
.sr-only {
  position: absolute;
  left: -10000px;
  top: auto;
  width: 1px;
  height: 1px;
  overflow: hidden;
}
```

I'm happy to submit a PR that adds this class, I just have a few questions:

* Does such a class already exist somewhere in FEC's CSS?

Er, wait, I think I just answered my own question.  It looks like [`scss/mixins/_utilities.scss`](https://github.com/18F/fec-style/blob/master/scss/mixins/_utilities.scss) has a class called `u-visually-hidden`, so you should be able to use that @emileighoutlaw!

Let me know if that doesn't work, though, and we can re-open this issue.

**Comment by noahmanger** [comment]
Yep, `.u-visually-hidden` is exactly the class for this. Thanks @toolness !
