### ISSUE TITLE
Create related cards on press landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#532]
In order for visitors to the press page to find related sections that are of interest, create related section cards that direct them to the data, calendar and latest updates:

![image](https://cloud.githubusercontent.com/assets/1696495/19087942/cec2973c-8a28-11e6-9fed-f7d4de0f1650.png)

There's two tasks here:
- [x] Write descriptions that explain the value of each section (e.g. "Use the calendar to find...")
- [x] Create new monochrome icons for latest updates and campaign finance data

If this can be done for the release we can include it, but it's not necessary to launch the page.

cc @jenniferthibault @emileighoutlaw

**Comment by emileighoutlaw** [comment]
I think it's probably wise to keep this content as lightweight as possible, so people can easily scan it. My first thought is something like:

> Calendar
> _Deadlines and events_


> Latest updates
> _Press releases, Weekly Digests, FEC Record_


> Campaign finance data

**Comment by jenniferthibault** [comment]
I took a look at what we do elsewhere, and it seems we have been inconsistent in language, and I'm  noticing some unintended style bugaboos.

Sometimes we just use the label, and sometimes we give hints to why it's helpful.

<img width="1071" alt="screen shot 2016-10-06 at 12 03 43 pm" src="https://cloud.githubusercontent.com/assets/11636908/19160224/16f9ade8-8bbd-11e6-838d-275f4f489a35.png">

<img width="1108" alt="screen shot 2016-10-06 at 12 04 01 pm" src="https://cloud.githubusercontent.com/assets/11636908/19160225/16fa6f1c-8bbd-11e6-850c-cabf4f6e44ef.png">


So if we were to set a consistent approach, it seems we need to balance scanability and providing helpful context to _why_ this thing might be a helpful next path to travel down. (think trailheads!) I worry slightly that with just what's in each section, if people don't know what they are, they won't know why they should go there. Particularly in the case of `Press releases, Weekly Digests, FEC Record`

Here's my take on the icons (new one for latest updates) - I'm not sure about the language, but it's my rough stab at reconciling scanability & context

![screen shot 2016-10-06 at 12 10 42 pm](https://cloud.githubusercontent.com/assets/11636908/19160415/cbd6a450-8bbd-11e6-9db9-bcc2566879f0.png)

**Comment by jenniferthibault** [comment]
Closed by https://github.com/18F/fec-cms/issues/540
