### ISSUE TITLE
Design review of new utility footer

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#539]
Review new style implementation of utility footer and propose changes:

<img width="1274" alt="screen shot 2016-10-12 at 1 30 24 pm" src="https://cloud.githubusercontent.com/assets/11636908/19320595/e7424480-907f-11e6-87c1-8c96c611812b.png">

**Comment by noahmanger** [comment]
FWIW, here it is with the other links:
![image](https://cloud.githubusercontent.com/assets/1696495/19327163/9843854e-909b-11e6-83a8-4bb1b15b6271.png)

**Comment by jenniferthibault** [comment]
Yes thank you!

Only change:
- In the footer nav, the font family should be Karla, or `sans-serif`. I'm not sure what the best classes to use are, so I'm hesitatnt to implement it myself.

To be super duper extra clear, that only applies to this part:
<img width="1101" alt="screen shot 2016-10-19 at 1 56 22 pm" src="https://cloud.githubusercontent.com/assets/11636908/19530982/035a4b0c-9604-11e6-8c40-cb0fc7c988dd.png">


This part is totally fine and should stay exactly as is
<img width="1005" alt="screen shot 2016-10-19 at 1 58 03 pm" src="https://cloud.githubusercontent.com/assets/11636908/19531008/1541ca84-9604-11e6-9041-6ef9af16794b.png">


@noahmanger / @xtine would either of you like to take this for implementation?

**Comment by noahmanger** [comment]
Oh great! Yeah, I'll take it.
