### ISSUE TITLE
Design template for Explanation and Justification (E&J) index

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#541]
Used frequently, provides historical context for regulations.

http://fec.gov/law/cfr/ej_toc.shtml

http://fec.gov/law/cfr/ej_toc_1970.shtml

**Comment by porta-antiporta** [comment]
@jenniferthibault @adrianwebb @nickykrause  Just a comment for consideration.  E&Js track the changes and rationale behind changes to 11 C.F.R of regulations.  

Would it make sense to look at whether E&Js should belong on the eregs viewer.

Couple things lead me to ponder this:
1. In eregs, there are related asssets that are referenced in the right hand nav: https://atf-eregs.18f.gov/478-11/2016-12100#478-11. In this particular example, rulings could be viewd as akin to AOs.   
2. eregs supports diff'ing regulations as they change over the years.  https://atf-eregs.18f.gov/diff/478-74/2016-13878/2016-12100?from_version=2016-12100

So _could_ E&Js be shown as context of related assets and diffs of 11 C.F.R over time.  Does it meet the usage pattern of the user and also, is the juice worth the squeeze?

Offhand this would seem like a lot of effort, but did want us to look wholistically when we migrate E&Js, Rulemakings; we consider whether it should be treated as part of regulations as opposed to the separate entities they are on the current fec.gov site.

**Comment by jenniferthibault** [comment]
@porta-antiporta that was my first instinct too! But @noahmanger and Amy Kort seemed to think that it wasn't possible, based on what they had been told earlier about eregs' capabilities?

If it IS possible, I think that's the preference, though I know it would take some design thinking to figure out how best to do it.

**Comment by porta-antiporta** [comment]
That _may_ be related to something I mentioned when we tried supporting _diff_ functionality on our eregs instance.  @anthonygarvan had found that the federal register was missing a lot of the XML we would like to render those diffs.

However, eregs can also parse text (not used often, so may need some dusting off).  So this is where the effort starts to grow.  We never went in and actually tried to size that effort though; it was more "hairs on the back of my neck are tingling" estimation.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-cms #1333](https://github.com/18F/fec-cms/issues/1333) via [**ZenHub**](https://www.zenhub.com/)
