### ISSUE TITLE
Design template for Election and Justification citation index

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#542]
This page largely has content that's accurate, but might need design work for either a new template, or finding an existing template that fits.

http://www.fec.gov/law/cfr/ej_citation_parts9038-9039.shtml

**Comment by noahmanger** [comment]
Is this a duplicate of https://github.com/18F/fec-style/issues/541 ?

**Comment by jenniferthibault** [comment]
When we filed them both in the workshop with @emileighoutlaw and Amy, I understood how they were different, and why I made two. Now I can't remember.

**Comment by emileighoutlaw** [comment]
Blurg. I can't remember now, either.

**Comment by jenniferthibault** [comment]
Let's say it's a duplicate and as we get closer to E&J's we can make new issues as needed.
