### ISSUE TITLE
Create formatting guide for Weekly Digest items

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#544]
While making all of the 2016 weekly digests consistent, bring the underlying style patterns into a formatting guide based on headline level and bullet/paragraph stylings.

**Comment by jenniferthibault** [comment]
I've made an unpublished draft Digest page in Wagtail called `Week of [Month] [dd] – [Month] [dd], [yyyy] [FORMATTING GUIDE]`

This document labels each headline style and has basic notes on when to use certain formatting. I'm hoping that this document can be used as a template to duplicate & start from when posting a new weekly digest. 

Try [this link](https://beta.fec.gov/admin/pages/4291/edit/) to get there. 

cc @noahmanger / @emileighoutlaw for 👀 & if you think this could be improved as a tool.

**Comment by noahmanger** [comment]
This is awesome! We'll test it with folks there to see how it works, but looks really helpful.

**Comment by emileighoutlaw** [comment]
That is awesome. I may want to make a small tweak to how we write the dates at the top (based on what comes out of my exploration in https://github.com/18F/fec-style/issues/553. But that's a small thing.

**Comment by noahmanger** [comment]
Can we close this issue?

**Comment by jenniferthibault** [comment]
We can close it— @emileighoutlaw and I found this format is possibly too brittle to use as a guide, because it's too easy to accidentally erase the template. Let's revisit this when we get closer to wagtail training/documentation
