### ISSUE TITLE
Fix markup documentation for Messages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#549]
We might have broken something when we were adding the new documentation styles last time, because the Show Markup container is empty:

https://pages.18f.gov/fec-style/section-components.html#kssref-components-messages

<img width="818" alt="screen shot 2016-10-19 at 1 59 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/19531111/782605c0-9604-11e6-8816-1bca424eaf19.png">

cc @noahmanger

**Comment by noahmanger** [comment]
Closing this since we're changing the tech.
