### ISSUE TITLE
Unify formats for displaying dates and times

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#553]
We currently display dates and times in a number of formats throughout the design. While not urgent, I think it would be good to at some point clean up the approach we take. 

For example:

`MM-DD-YYYY`:
![image](https://cloud.githubusercontent.com/assets/1696495/19651575/69b562d0-99db-11e6-8b13-5eea0b13556b.png)

`MM/DD/YYYY`:
![image](https://cloud.githubusercontent.com/assets/1696495/19651585/75a4c284-99db-11e6-8c5e-53dafe3e73da.png)

`mm dd, yyyy`:
![image](https://cloud.githubusercontent.com/assets/1696495/19651595/8290dfc8-99db-11e6-9bfe-9f486090b903.png)

![image](https://cloud.githubusercontent.com/assets/1696495/19651615/994195a0-99db-11e6-9549-2fb007e52d85.png)

`MM dd, YYYY`
![image](https://cloud.githubusercontent.com/assets/1696495/19651631/aaac8520-99db-11e6-87a2-64633f17a1ed.png)

I think there's a lot of sense in having  a format that's just digits, as these are easier to scan in data, and another that's actual month names. But we should probably standardize on `/` vs `-` and also decide when to use which.

Paging @emileighoutlaw and @jenniferthibault

**Comment by emileighoutlaw** [comment]
Existing date displays (for reference):

<img width="190" alt="screen shot 2016-10-25 at 5 06 46 pm" src="https://cloud.githubusercontent.com/assets/10552702/19898440/f69ed6e6-a029-11e6-94eb-4b9de3ef273c.png">

<img width="671" alt="screen shot 2016-10-24 at 12 23 57 pm" src="https://cloud.githubusercontent.com/assets/10552702/19898441/f884ffc6-a029-11e6-9479-829c55ce1ac3.png">

<img width="456" alt="screen shot 2016-10-24 at 12 17 31 pm" src="https://cloud.githubusercontent.com/assets/10552702/19898455/06df786c-a02a-11e6-979a-a376e54c169e.png">

<img width="744" alt="screen shot 2016-11-01 at 12 00 00 pm" src="https://cloud.githubusercontent.com/assets/10552702/19898613/c6241476-a02a-11e6-8b41-486ade1648f9.png">

<img width="1015" alt="screen shot 2016-11-01 at 11 57 24 am" src="https://cloud.githubusercontent.com/assets/10552702/19898619/c8a3d650-a02a-11e6-8d51-e41b5662e3b2.png">

<img width="825" alt="screen shot 2016-11-01 at 11 56 29 am" src="https://cloud.githubusercontent.com/assets/10552702/19898514/491655ac-a02a-11e6-80db-17224b9c9455.png">

**Comment by emileighoutlaw** [comment]
## Months and ordinals
- It's faster for readers to parse `November 8, 2016` than `November 8th, 2016`.
- It's easier to read `November 8, 2016` than `11/8/16`. (_There's also a small argument to be made that, for international users, the ordering of mm/dd is unexpected, and writing the month out eliminates any confusion._)

**Conclusion:** We should display dates as: `November 8, 2016`. 

That isn't feasible in many charts, but more on that next.

## Displaying dates in charts and graphs 
- `11-08-2016` will linebreak partway through, whereas `11/08/2016` won't:
<img width="222" alt="screen shot 2016-11-02 at 1 40 06 pm" src="https://cloud.githubusercontent.com/assets/10552702/19942519/02db5b4a-a102-11e6-8cef-06efbcff4574.png">

**Conclusion:** Dates should follow this format: `11/08/2016`

## Ranges
Our brilliant EITI folks (h/t @gemfarmer) did testing on ranges: 
- It's easier for users to scan and read ranges that have the word "to" in them. This jives with my content strategy upbringing that "to" is more accessible for readers than "–" (n dash). It's also a slightly better experience for screen readers (which read a dash as "dash" and not "to").

**Conclusion:** Depending on context, ranges should follow one of two patterns: `November 8 to 9, 2016` or `11/08/2016 to 11/9/16`


If this reasoning sounds good to @jenniferthibault and @noahmanger, I'll start working on implementation. :)

**Comment by noahmanger** [comment]
This makes a ton of sense to me. Seems like a great way to go.

**Comment by emileighoutlaw** [comment]
This will be complete when dates are unified in:

- [ ] Registration and reporting
- [ ] Data (filters, candidate/committee pages)
- [ ] Legal resources
- [ ] Press section

**Comment by noahmanger** [comment]
@emileighoutlaw do you need a developer to pick up the task of getting these everywhere else?

**Comment by emileighoutlaw** [comment]
I'm actually trying to muddle through on my own first (because I want to be better at HTML) :)

**Comment by emileighoutlaw** [comment]
Hey @noahmanger — I'm actually struggling to find and get through this. Maybe it would be smarter and more time-efficient to have a developer pick up this task and me review the PR. I'm starting to be a blocker on this, and that feels icky.

**Comment by noahmanger** [comment]
Sounds good. Yeah this gets tricky because the date formatters live in a few places.

**Comment by jenniferthibault** [comment]
I did a quick review and didn't find any outstanding places in legal resources where the dates were inconsistent with the decisions above. Closing
