### ISSUE TITLE
Design visual styles for home page wireframes

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#554]
When wireframes from https://github.com/18F/fec-cms/issues/518 are selected and completed, apply visual styling, including:
- select & apply existing patterns
- design any new elements called for
- select & design photo options
- design new icons

Completed deliverable will be an InVision mockup that shows basic interactions & linking as important for understanding the home page & navigation system.

**Comment by jenniferthibault** [comment]
Quick update on what's been happening behind the scenes:

We've been meeting with the content manager group to get signoff for final home page content & styles and have hit some snags on detail-level content modules. Visual styling is a secondary concern to nailing the wording & content structure at this point, but is keeping pace with that discussion as it moves. 

Emileigh, Nicky, and I are pairing tomorrow morning through the latest feedback with the goal of finding an implementation-ready subset. 

This item remains in progress, but we indent to section out pieces of the home page that are ready for implementation before others.

**Comment by jenniferthibault** [comment]
All designs have been transferred to new issues for the first rounds of implementation. Closing.

 - [Implement home page version of header and hero #634](https://github.com/18F/fec-cms/issues/634)
 - [Implement "What's happening" section for home page #636](https://github.com/18F/fec-cms/issues/636)
 - [Implement "Campaign finance data" portion of home page #637](https://github.com/18F/fec-cms/issues/637)
 - [Implement "totals raised/spent over time" chart portion of home page #652](https://github.com/18F/fec-cms/issues/652)
 - [Implement "Registration and reporting" section of the home page #644](https://github.com/18F/fec-cms/issues/644)
 - [Implement "Citizen information" portion of home page #646](https://github.com/18F/fec-cms/issues/646)
 - [Implement "Legal resources" section on home page #638](https://github.com/18F/fec-cms/issues/638)
 - [Implement "Commissioners" portion of home page #639](https://github.com/18F/fec-cms/issues/639)

**Comment by noahmanger** [comment]
👏  Huge round of applause for @jenniferthibault @nickykrause and @emileighoutlaw for shepherding this through. Awesome work.
