### ISSUE TITLE
Consider updating link color

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#563]
Our links are currently styled using `color: inherit` which means that they inherit their color from the color of the parent element. So if the color of a paragraph is black, they'll be black; if it's white (like in a slab), they'll be white. 

However, a few people have noted that this makes it hard to tell that they're links:
![image](https://cloud.githubusercontent.com/assets/1696495/19948597/99c221bc-a10a-11e6-85b3-c5fb64932ae1.png)

I don't know that I'd suggest having a different color when they're on a dark background, but when they're on a white background I think it would be worth making them a more vibrant color. 

This came through in @ChristianHilland 's feedback on the press releases, so wanted to file an issue to discuss with @jenniferthibault .

**Comment by jenniferthibault** [comment]
Are there other cases where this came up specifically besides the press releases? Not disagreeing at all, but always cautious of generalities and "people are saying". 
(Which is not what you said, I know!) I'd like to understand other scenarios where this came up to see if there are any times when it's specifically hard to find hyperlinks people are looking for.

**Comment by noahmanger** [comment]
I don't have specifics off the top of my head other than that it's caught my eye a few times. I'm not suggesting we make a change on this feedback alone, but wanted to raise it in case you or others agreed.

**Comment by emileighoutlaw** [comment]
I'm not sure I have strong feelings either way on this one

**Comment by ChristianHilland** [comment]
Just speaking for the Press Office, the hyperlinks are important in news releases on open meeting and litigation matters. Often times, people seek documents that have been discussed at public meetings such as advisory opinions, rulemaking initiatives, etc.  To me, it seems that the hyperlinks are not as easily identifiable in the Press section of the beta site.  While I'm bringing up the issue, it's not one of great concern.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-pattern-library #18](https://github.com/18F/fec-pattern-library/issues/18) via [**ZenHub**](https://www.zenhub.com/)
