### ISSUE TITLE
Travis didn't publish a new version

### ISSUE THREAD

**Issue by ccostino** [18F/fec-style#568]
We just pushed version `5.8.0`, but the Travis build didn't publish it for us automatically despite the build finishing successfully and tags being pushed.

**Comment by LindsayYoung** [comment]
got this error again

**Comment by ccostino** [comment]
Argh, okay - https://github.com/18F/fec-style/pull/569 should fix this, I see it was merged after trying here, we can try again to verify if it does indeed fix it or not.

**Comment by LindsayYoung** [comment]
passed https://travis-ci.org/18F/fec-style/builds/178426674
