### ISSUE TITLE
Finish porting pattern library to Fractal

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#571]
In order for our pattern library and style guide to be easier to maintain and use, and in order for it to accommodate more robust documentation, we need to move it entirely over to the new Fractal system.

The purpose of this issue is just to complete the migration of all patterns from the old KSS system to the new system. We will need future tasks for building out documentation, adding more patterns and finding a way to host it. 

**Completion criteria:**
- [x] All existing documented components are moved to Fractal
- [x] Old KSS code is removed from fec-style
- [x] Pat and John have been walked through the system

**Comment by jenniferthibault** [comment]
@noahmanger before you put a huge amount of additional effort into this, could you show me how it works? Wondering if this is a an opportunity for thinking about the stucture

**Comment by noahmanger** [comment]
Dependent on https://github.com/18F/fec-style/issues/292
