### ISSUE TITLE
Review/improve visual styling of "What's happening" homepage section

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#602]
Some of the default type styles on this section could use some finessing, and now that we have real data populating the feed, I'd like to give it some attention to fine detail.

https://beta.fec.gov/

![screen shot 2017-01-04 at 3 36 10 pm](https://cloud.githubusercontent.com/assets/11636908/21658267/dd90f85e-d293-11e6-80e3-f4a79986c228.png)

**Comment by noahmanger** [comment]
All done!
