### ISSUE TITLE
Make icon sizes consistent on AO Process page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#616]
https://beta.fec.gov/legal/advisory-opinions/process

The email icon is smaller than the others: the hand delivery & fax icons are the correct size.

<img width="569" alt="screen shot 2017-01-19 at 9 44 09 am" src="https://cloud.githubusercontent.com/assets/11636908/22111064/f99d09e0-de2b-11e6-8d23-bcefead2e831.png">

Not sure what is causing this, but if it's something I can help with let me know!

cc @xtine

**Comment by AmyKort** [comment]
Wholly unrelated: can you take Shawn's name off of the hand delivery address and have it just go to the office of the commission secretary? Thanks!

**Comment by jenniferthibault** [comment]
🎉 Removing the name has the side effect of making the text columns more even in length. Definite visual perk!

I also just noticed that the email address next to the email icon looks like a smaller font size. Weird things happening with that one! 

(Have I mentioned lately that it's awesome having you on GitHub Amy?)

**Comment by AmyKort** [comment]
Aw shucks. Thanks @jenniferthibault !

**Comment by noahmanger** [comment]
Removed Shawn's name and put a fix for the icon sizing in at #617
