### ISSUE TITLE
Implement new pattern for sidenav that changes main container sections

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#620]
So that users can navigate between sections of content when the sections are too long for a graceful page-jump, implement side nav pattern from the [USWDS](https://standards.usa.gov/sidenav/) with FEC visual styling.

This issue represents one step toward  implementing [home page changes for Candidate & committee services](https://github.com/18F/fec-cms/issues/684#issuecomment-276253358)

and the [new layout for candidate and committee profile page templates](https://github.com/18F/openFEC-web-app/issues/1786)

<img width="275" alt="screen shot 2017-01-30 at 9 20 33 pm" src="https://cloud.githubusercontent.com/assets/11636908/22450074/3f8de7bc-e732-11e6-95c4-a1000cff0337.png">
<img width="250" alt="screen shot 2017-01-30 at 9 21 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/22450075/3f94c26c-e732-11e6-86d9-3c91976964ba.png">

**States:**
![screen shot 2017-01-30 at 9 37 50 pm](https://cloud.githubusercontent.com/assets/11636908/22450408/6656155c-e734-11e6-8bf4-5c5b0694914f.png)

@noahmanger would appreciate your :eye: for completion criteria ✅

**Comment by noahmanger** [comment]
This has been implemented.
