### ISSUE TITLE
To create consistency and clean layouts, create image guidance for Latest Updates articles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#622]
Guidance should include:

- [x] What dimensions should be standard (for small and large images)
- [x] Where images should be placed in relation to text

System design opportunity:
- [x] Investigate whether guidance can be incorporated as helper text to Wagtail admin interface.

Share and demo with the FEC team.

**Comment by noahmanger** [comment]
If it helps, it's possible for us to control this tightly in the system if we want (and live less room for mistakes). For instance, we could only allow images as separate fields, and then control where they get placed, what dimensions they're rendered and cropped at, etc.

**Comment by jenniferthibault** [comment]
Thanks to @noahmanger's help with the feed styling in https://github.com/18F/fec-cms/issues/549 , we have some recommendations for how to integrate images that leaves a lot of flexibility for FEC.

We're thinking that we should **keep the ability to add images at any point in the post** (don't limit images to only appearing in one place), but **provide guidance on image sizes** for consistency.

### Add multiple images at any point in the post
This way, for posts with many detailed images, like [Statistical posts](http://www.fec.gov/pages/fecrecord/2017/february/21monthsummary_2016cycle.shtml) you can include more than one large image, and intersperse them between the text. This allows images to appear large enough on the page that you shouldn't have to open them in a separate window.

It also allows the author to choose the right point in the text for an image, instead of making the call with code.

### Provide guidance on image sizes
Limiting to small, medium, and large sizes will help fit the majority of the images I've seen in posts so far.

#### Large images
Should be 620px wide, but can be any height. This keeps a lot of flexibility, and will be great for statistical images, election district images, or banner-type images that the FEC makes

#### Medium images
Should be 460px wide x 240px tall (but height is a bit flexible). This is very close to the existing size for most FEConnect images, and could also fit the dimensions of Commission chair announcements

#### Small images
Should be 140px wide x 180px tall. The dimensions of this size are pretty strict to create standardization of even the smallest images on FEC's site. It best fits cover images for brochures, publications, or single commissioner bio photos

## How images should be placed in Wagtail:

### Step 1: Placing images in the post

@noahmanger recommended that it's better to use the ImageBlock field 
(this)
![screen shot 2017-02-09 at 8 40 08 pm](https://cloud.githubusercontent.com/assets/11636908/22810619/fec14a5c-ef07-11e6-81f9-3313deb18852.png)

instead of the richtext image button in the paragraph block
(not this)
![screen shot 2017-02-09 at 8 40 38 pm](https://cloud.githubusercontent.com/assets/11636908/22810644/1ea9c8f8-ef08-11e6-81bc-f352b5443488.png)

This means a slight change in the regular copy/paste workflow, because if you'd like to add a new image between text paragraphs, you need to make a `paragraph block`, `image block`, `paragraph block`

If I were to add one of each image size, that would look like this in Wagtail:
![screen shot 2017-02-09 at 7 50 44 pm](https://cloud.githubusercontent.com/assets/11636908/22810801/d3956b6e-ef08-11e6-9f19-8f5925979d9a.png)


Which would look like this as a generated page:
![screen shot 2017-02-09 at 7 52 05 pm](https://cloud.githubusercontent.com/assets/11636908/22810805/dbe13dca-ef08-11e6-9de2-715a3bf60d77.png)


### Step 2: Assigning "Feed images" 

This tells wagtail which image to show in the Latest Updates feed as a thumbnail. You'll be able to select any image already uploaded (so no need to upload a separate thumbnail unless you want to). The image will be automatically resized to fit the feed, as seen [here](https://cloud.githubusercontent.com/assets/1696495/22808590/98a50f0e-eee1-11e6-8ad2-3f14d74cc59a.png).

__________
Ok!

This was a lot to read, but it's not a very burdensome workflow when you see it in action for a new page. Once the changes from https://github.com/18F/fec-cms/pull/808 are implemented and running on the live site, it's worth a walkthrough with @patphongs and @dorothyyeager + whoever else would like to join in the fun 😄 

Feel free to ping with any questions on your mind in the meantime!

**Comment by noahmanger** [comment]
@jenniferthibault can we capture this guidance somewhere permanent, like Drive or Github docs (wherever other things like this are going) and then we can close?

**Comment by jenniferthibault** [comment]
I would love that. @emileighoutlaw where are you keeping Wagtail guidance?

**Comment by emileighoutlaw** [comment]
I've been keeping it in [this Google Doc](https://docs.google.com/document/d/1X5DNJFAWgzL-jdT9lDBmitQmg1dnAcQnXpzPCp4CRJA/edit), but maybe it's time to consider a better, long-term solution. Maybe it should be incorporated into the Content Guide?

**Comment by jenniferthibault** [comment]
Where does the content guide live?

**Comment by emileighoutlaw** [comment]
Also [Google Doc](https://docs.google.com/document/d/1cIWTO4X9kNvjL-Lpq8A6t9NrA3ZtWvSZ5mKS1ic0-Js/edit?pli=1#heading=h.6st9dlvd68xh) 😬

**Comment by jenniferthibault** [comment]
Comparing the content in each, it seemed to fit better with the Wagtail guidance for now, so I put it in that document. I know this may change in the future. 

Ok to close this?

**Comment by noahmanger** [comment]
Yep! Thanks, @jenniferthibault .
