### ISSUE TITLE
Design and implement block quote styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#632]
So that quotations can be pulled out from body copy in a way that makes them visually distinct from the rest of the body copy, design a style for them and implement it on the front end.

**Steps to completion**
- [x] Visual design styled: @jenniferthibault
- [x] Implemented in stylesheet
- [x] Added to Wagtail WYSIWYG editor for paragraph blocks

**Comment by jenniferthibault** [comment]
What I was thinking for visual styling is super related to the Example styles pulled from https://github.com/18F/fec-cms/issues/727#issuecomment-276272557 . The type style would be standard body copy size, but italic weight:

![screen shot 2017-02-15 at 3 18 42 pm](https://cloud.githubusercontent.com/assets/11636908/22993728/11159ba2-f392-11e6-9525-395fac05a9ce.png)

I was also looking specifically at spacing because in the E-Filing report there are a few back-to-back block quotes, so this style would need to work in sequence:

![screen shot 2017-02-15 at 3 20 12 pm](https://cloud.githubusercontent.com/assets/11636908/22993813/6443ee5a-f392-11e6-9f3c-cced96332346.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/861
