### ISSUE TITLE
[ATO] Address cross-site scripting and content-spoofing issues

### ISSUE THREAD

**Issue by ccostino** [18F/fec-style#633]
The folks performing testing for our ATO have found several instances where it could be possible to initiate a cross-site scripting attack by adding JavaScript as values to the parameters in our web requests, or supplying additional content as a part of the URL request.

We need to make sure we're sanitizing user input appropriately and escaping things that need escaping to address this issue.

NOTE: This is intended for GovCloud, but needs to be fixed across the board.  This is also related to this issue: https://github.com/18F/openFEC-web-app/issues/1839

**Comment by ccostino** [comment]
@xtine and I have identified [this line](https://github.com/18F/fec-style/blob/master/js/filter-set.js#L51) as the apparent root of the issue that we can fix.

**Comment by ccostino** [comment]
I've done a bit more research and that line is just the root for the issue reported - it goes a bit deeper than that.  We need to sanitize the query string wherever it is parsed by URI.js.  Working on a solution that I'll put up as a PR soon!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/634
