### ISSUE TITLE
Create list of currently used design tools

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#638]
In order to begin practical design transition work to the FEC team, we should ensure that everyone has the tools they need to get their hands dirty in design work. 💪 

The 18F team should put together a list of:
- Current tools and software we use to do our work on this project
- How we use each tool
- Why we use it over others (if applicable)

Then, we can whittle that down into a starting toolkit for the FEC, and start submitting purchase requests.

cc @onezerojeremy @noahmanger @emileighoutlaw @nickykrause I'll be coming to you for input on this 👀

**Comment by jenniferthibault** [comment]
:construction_worker_woman: Work in progress in 🔏 [Google Docs](https://docs.google.com/a/gsa.gov/spreadsheets/d/1S0bu17vDjwVb2e1Zxf8EJDYXY43zX6qKdjuK2r3GREI/edit?usp=sharing)

**Comment by jenniferthibault** [comment]
👓 needed from fellow designers @noahmanger @onezerojeremy @emileighoutlaw @nickykrause

**Comment by noahmanger** [comment]
I have nothing to add to this. Looks great.

**Comment by emileighoutlaw** [comment]
Looks good to me too. I fleshed out a little more about why Google Docs is beneficial for content. Everything else looks A+ to me.

**Comment by nickykrause** [comment]
The only thing I was going to add when you shared this originally was Murally, but it looks like someone added that already. 

I see there is also line item for Google Hangouts/Appear.In/Adobe Connect, which I assume was added as a nod to our distributed team meetings. I added some notes that a remote video conferencing tool is also good for usability testing. 

Can't think of anything else to add at the moment!

**Comment by jenniferthibault** [comment]
Thanks everyone!

@patphongs this is ready for you to take a look. You should have access to the [Google Doc](https://docs.google.com/a/gsa.gov/spreadsheets/d/1S0bu17vDjwVb2e1Zxf8EJDYXY43zX6qKdjuK2r3GREI/edit?usp=sharing), but if you don't, let me know. Glad to talk through any of the tools or use cases further to help with any decisions.

cc @porta-antiporta cuz I know you were creepin' on this too 😄

**Comment by porta-antiporta** [comment]
:guilty:

**Comment by noahmanger** [comment]
Anything more needed here or can we close this?

**Comment by jenniferthibault** [comment]
Checked in quickly with Pat this morning, and no more work needed. Some applications are moving to access requests.
