### ISSUE TITLE
Incorrect district information in search by election

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-style#675]
https://beta.fec.gov/data/elections/?cycle=2018&zip=20754

I'm pretty sure we had this issue a long time ago but I can't find it. This zip code is entirely in district 5 but it displays the warning that this zipcode is in two congressional districts. It shows two elections. One for MD House District 5 and one that just says MD House with no district.

**Comment by noahmanger** [comment]
Huh. I just see this, which looks right:

![image](https://cloud.githubusercontent.com/assets/1696495/25360617/c1d4fa40-28fe-11e7-8448-e4fcecd291b0.png)

**Comment by noahmanger** [comment]
@jwchumley any further examples of this? Otherwise we should close.

**Comment by jwchumley** [comment]
It's correct now. Did something change? I had multiple zips doing this and now I can't find one that's wrong.

**Comment by noahmanger** [comment]
Not sure, but closing since it's apparently resolved.
