### ISSUE TITLE
Button text overflowing box

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#68]
I don't remember this happening before, so there may have been a recent change in fec-style that's related. @noahmanger I wonder if percy.io could be helpful in catching issues like this.
Example: https://fec-dev-cms.18f.gov/registration-and-reporting/
<img width="469" alt="screen shot 2015-09-08 at 9 21 42 am" src="https://cloud.githubusercontent.com/assets/1633460/9735773/44c370b2-560b-11e5-817d-f1d70a865aed.png">

**Comment by noahmanger** [comment]
Ah yeah. I know exactly what that is. Yep, set up right it could definitely
be helpful. The trick is to have enough variations in content (i.e. buttons
with long titles like these) to catch the errors.

On Tue, Sep 8, 2015 at 6:23 AM, Joshua Carp <notifications@github.com>
wrote:

> I don't remember this happening before, so there may have been a recent
> change in fec-style that's related. @noahmanger
> <https://github.com/noahmanger> I wonder if percy.io could be helpful in
> catching issues like this.
> Example: https://fec-dev-cms.18f.gov/registration-and-reporting/
> [image: screen shot 2015-09-08 at 9 21 42 am]
> <https://cloud.githubusercontent.com/assets/1633460/9735773/44c370b2-560b-11e5-817d-f1d70a865aed.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/issues/68>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Resolved
