### ISSUE TITLE
Add additional hierarchy styles within bullet & numbered lists

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#693]
This issue was broken out from https://github.com/18F/fec-cms/issues/782

So that the hierarchy and order of content in complex nested sections is clear, add additional styles for hierarchy levels within bullet and numbered lists.

We currently only have one layer of hierarchy within our bulleted & numbered lists, and our content has proven that we need more.

### Examples
A great example of a complex list hierarchy (2 levels) is the [Coordinated communications](https://beta.fec.gov/help-candidates-and-committees/making-disbursements/coordinated-communications/) page. This example shows an attempt to nest a bulleted list underneath a numbered list.

<img width="753" alt="screen shot 2017-05-03 at 5 49 47 pm" src="https://cloud.githubusercontent.com/assets/11636908/25683174/ef118650-3028-11e7-9ef3-18e8dceb07ad.png">

The[ Taking in receipts](https://beta.fec.gov/help-candidates-and-committees/candidate-taking-receipts/) page shows how we currently work around to get a nested bulleted list

<img width="568" alt="screen shot 2017-05-03 at 5 51 59 pm" src="https://cloud.githubusercontent.com/assets/11636908/25683271/61933156-3029-11e7-938b-8520f6201290.png">

__________________________________________________

**Completion criteria**
- [x] Design styles for hierarchy in bulleted lists
- [x] Design styles for hierarchy in numbered lists
- [ ] Implement styles in `fec-style` and pattern library
- [ ] Add styles to all Wagtail templates with a WYSIWYG paragraph editor
- [ ] Add indentation controls to WYSIWYG paragraph editor interface
<img width="139" alt="screen shot 2017-05-03 at 5 28 56 pm" src="https://cloud.githubusercontent.com/assets/11636908/25683327/a9c17258-3029-11e7-9778-f9f9c0edb6e1.png">

cc @emileighoutlaw

**Comment by jenniferthibault** [comment]
Designs!

One thing I think we should do is make a clear distinction between numbered lists and bulleted lists: so no more mixing bullets under numbers like in the first example above.

Here are the basic character/graphic patterns I think we should follow, which take after standard Google/Word defaults and should be easiest for internal users to recreate & widely recognizable by outside users:

- Number, lowercase letter, lowercase roman numeral (italic)
<img width="212" alt="screen shot 2017-05-03 at 6 15 59 pm" src="https://cloud.githubusercontent.com/assets/11636908/25683968/ad4a36f0-302c-11e7-9b6b-32d966d9068e.png">

- Solid round, outlined round, solid square
<img width="198" alt="screen shot 2017-05-03 at 5 28 48 pm" src="https://cloud.githubusercontent.com/assets/11636908/25683967/ad4993a8-302c-11e7-91d3-894897a12232.png">



And how they'd be aligned/indented against text with semi-real content (I mixed in a few more levels for demo-ing):

**Numbered**
![screen shot 2017-05-03 at 6 17 18 pm](https://cloud.githubusercontent.com/assets/11636908/25683989/cfcd561c-302c-11e7-8ff1-5038cccd8dfc.png)

**Bulleted**
![screen shot 2017-05-03 at 6 18 49 pm](https://cloud.githubusercontent.com/assets/11636908/25684018/febe4db4-302c-11e7-9799-df2d407fa884.png)

What do you think @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
Squeeee! I am so excited to see the work happening on this (and @llienfec will be too, I know, because we were just talking about this on Monday!). 

The trickiest thing, I think is defining when and how we use ordered vs. unordered lists. Nielsen has [a whole fabulous article](https://www.nngroup.com/articles/presenting-bulleted-lists/) about this content strategy, but basically:

- Numbers are for lists that are sequence order
- Bullets are for everything else


So a numbered example would be:

> To get to work:
> 1. Leave your house.
> 1. Get on the bus.
> 1. Listen to S Town while you ride.


And a bulleted list would be:

> Before you leave for work, don't forget your:
> - Keys
> - Wallet
> - Phone

Where things get tricky is that I forsee content situations where one level of a list might be sequential, but another would not. For example we could just as likely have a situation like this:

> To get to work:
> 1. Leave your house. Don't forget your:
>     - Keys
>    - Wallet
>    - Phone
> 1. Get on the bus.
> 1. Listen to S Town while you ride.

And in another spot we might have:

> To get to work:
> 1. Leave your house.
> 1. Get on the bus.
>    1.1 Let other people off first.
>    1.2 Swipe your metro card.
>    1.4 Find an open seat.
> 1. Listen to S Town while you ride.

This isn't a 100% perfect example, but what I'm trying to get at is that I can envision content needing to convey both a series of ordered events as well as a series of ordered and unordered events. And for a lot of this complex content, I think the numbered vs. unnumbered context clue can be important for understanding.

**Comment by llienfec** [comment]
Yes, this is great!

**Comment by jenniferthibault** [comment]
OOOOH a fun twist!

I think we're systematically reading the whole NN site through the process of this work 😉 

Thank you for pulling together the example of putting unstructured lists inside of structured lists (your first example), I can see now that is in fact what we were looking at in the [Coordinated communications](https://beta.fec.gov/help-candidates-and-committees/making-disbursements/coordinated-communications/) page example. So I take back my earlier request to not mix them, and would do it with the styles just as you have: the number takes the place of the first solid black bullet, so the following section is the outlined bullets

> To get to work:
> 1. Leave your house. Don't forget your:
>     - Keys
>    - Wallet
>    - Phone
> 1. Get on the bus.
> 1. Listen to S Town while you ride.

The tweak I'd make to your second example is to stick to alternating styles when making subsections, instead of 0.X numeric changes:
> To get to work:
> 1. Leave your house.
> 2. Get on the bus.
>    a. Let other people off first.
>    b. Swipe your metro card.
>    c. Find an open seat.
> 3. Listen to S Town while you ride.

To me, this is the visual equivalent of not repeating the first word in list item.  What do you think?

**Comment by emileighoutlaw** [comment]
Yes! I think all that looks spot on and makes perfect sense!

**Comment by jenniferthibault** [comment]
This is ready for front end implementation.

Recap: 

**Ordered list format and styles:**
- Number, lowercase letter, lowercase roman numeral (italic)
![screen shot 2017-05-04 at 1 30 18 pm](https://cloud.githubusercontent.com/assets/11636908/25716685/e2bcea2a-30cd-11e7-9ca4-105923fe1c8d.png)


**Unordered list format and styles**
- Solid round, outlined round, solid square
![screen shot 2017-05-04 at 1 30 24 pm](https://cloud.githubusercontent.com/assets/11636908/25716693/e8a8887c-30cd-11e7-98d3-eea7267c6751.png)

**Ordered list with unordered sub-section styles**
- Number, outlined round
![screen shot 2017-05-04 at 1 30 08 pm](https://cloud.githubusercontent.com/assets/11636908/25716720/0916f760-30ce-11e7-8b1b-d1b8b61222b2.png)

**Comment by noahmanger** [comment]
Is the idea that this style of indents will be replaced by regular bullet lists?

![image](https://cloud.githubusercontent.com/assets/11636908/25683271/61933156-3029-11e7-938b-8520f6201290.png)

**Comment by jenniferthibault** [comment]
Visually that would make sense to me. As long as the content is supposed to be an unstructured list and it looks good to @emileighoutlaw 
- Discounts and services
  - [Food and beverage discounts](#)
  - [Legal and accounting services](#)

**Comment by dorothyyeager** [comment]
Just noticed this. You found the best example of where we need this - pages where we'll talk about coordinated communications so it will be great to have it! Thanks.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1105 . This will be up with the next release.
