### ISSUE TITLE
Resolve typeahead problems

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#714]
There's a bug with the typeahead lookup where the results that it shows exclude data that should be included.

Two bugs have already been reported:
- [Obama](https://github.com/18F/openFEC-web-app/issues/1960)
- [Paul Ryan](https://github.com/18F/openFEC-web-app/issues/2076)

And I caught another one:
![image](https://cloud.githubusercontent.com/assets/1696495/26509691/c2d66f90-420e-11e7-9798-307117be5943.png)

There's something that's causing the matches to not be consistent.

**Comment by nickykrause** [comment]
This happened in usability testing today as well. Can't remember what the name of the committee was -- @patphongs may remember the example.
