### ISSUE TITLE
Update data menu with prominent link to individual contributions

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#715]
Once the final design decision has been made in https://github.com/18F/openFEC-web-app/issues/2061, update the data dropdown menu.

**Comment by jenniferthibault** [comment]
Design component: 

- [ ] Design icon for individual contributions card

**Comment by jenniferthibault** [comment]
Here's the design carried over with slight styling adjustment to the icon colors to bring them into standard use pattern. Here is the [icon for individual contributions](https://github.com/18F/fec-style/files/1040188/individual-contributions.svg.zip), zipped.

It would be great if the two cards at right could be the same width and height, but I'm not sure how it's actually going to play out on the grid and in the space.

![screen shot 2017-05-30 at 10 46 16 pm](https://cloud.githubusercontent.com/assets/11636908/26613749/4791a366-458a-11e7-98f4-23df9c92b681.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/731
