### ISSUE TITLE
Clean up SCSS files for Pattern Library

### ISSUE THREAD

**Issue by xtine** [18F/fec-style#725]
Go over the SCSS files to:
- Clean up comments
- Add any gaps in documentation
- Modify or remove outdated styles
- Possibly reorganize component folders

Review classes that are not currently documented in the Pattern Library that need to be. For reference: https://github.com/18F/fec-style/issues/292

**Comment by xtine** [comment]
Styles in `fec-style` that aren't on Pattern Library yet:

### "Components"
- Agendas/Meetings
- Raising/Spending breakdowns
- Charts
- Contact form
- Date picker grid (filter on Datatables)
- Icons
  - We need to figure out a way to showcase, maybe write script to generate it on Pattern Library when icons are added/modified/deleted
- Maps
- Mega Menu (site nav)
- Modals
- Overviews (used on data landing page to describe Raising/Spending breakdowns)
- Posts (like on latest updates)
- Richtext formatting (CMS specific)
- Tags (filters on Datatables)
- Type styles (large numbers, ruled, highlights, etc)

### "Modules"
- Calendar
- Data container (content surrounding Datatables)
- Datatable panel
- Entity header (header on election pages)
- Feedback (button and popup panel)
- Filters (for Datatables)
- Glossary
- Navigation
- Results (box of controls and info above and below Datatables)
- Search controls (used at the top of election lookup page)
- Site header
- Site orientation tour
- Totals tables (simple tables, often paired with accordion components to expand and collapse)

**Comment by noahmanger** [comment]
SCSS files cleaned up. We'll add new components in future issues.
