### ISSUE TITLE
Figure out what format Styles will take in the pattern library guidance

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#733]
Laid out in #292 , our new pattern library is composed of:
1. Styles (the visual identity pieces: typography, color, images, etc)
2. Components (the re-usable pieces of the system: buttons, filter combinations, tables, etc)
3. Templates (the most common reusable layouts that the components create: header/footer, CMS templates pages, data table pages, etc)

Fractal is a _relatively_ obvious plug and play for the components, but not necessarily as great of a fit for the type of information and guidance offered in the style section, where it could possibly help to have more in-line comments.

**Completion criteria:**
- [x] Use mockups from #718 to assess the type of info in this section—use this to consider various approaches to integrating these elements into a website that makes the pattern library (Fractal, fractal+something else hybrid, or something else?)
- [x] Discuss and decide on a direction with the team (probably @xtine @jenniferthibault @noahmanger & FEC design folks)
- [ ] Implement at least one Style section in the decided format

**Comment by jenniferthibault** [comment]
[Designs](https://gsa.invisionapp.com/share/FDC5XMYKB#/238949401_Font_Families) 🎨  |  [Content copy](https://docs.google.com/a/gsa.gov/document/d/11FWZK4tbWN0OOO2FL2A51mZfKlUbl43cIpgtmZ4XdGQ/edit?usp=sharing) 📝  🔏 

**Approach:** We're going to use the Documentation section of Fractal to build a Style folder, and embed components into the markdown pages.

@xtine both of the Typography pages and Color page are ready to go—we synced up earlier about starting with these to test the concepts

**Comment by jenniferthibault** [comment]
@xtine any blockers here I could help with?

**Comment by xtine** [comment]
From my notes, components that need attention still:

- Banner
  - will expand/collapse
- Breadcrumbs
  - show other colors and reasons for using them (like wagtail pages)
- Buttons
    - We should do this: https://uspto.github.io/designpatterns/1.x/docs/components/buttons.html
    - Basic
        - rename descriptions
        - add more hover states
    - Add button w/ icon
    - Icon and text buttons
        - update grid
        - add background colors
    - Add page with remove button, dropdown, etc
- Callout
    - Should rename to card
    - Change code in Candidate/Committee page
- Card icons
    - Should just put into Cards
- Cards
    - redesign
- Contact item
    - fix
- Documents
    - maybe come back to this later
- Dropdowns
- Filters
    - add page
- Forms
    - add each element into each page
- Heroes
    - use Campaign Finance Data as only example
- Icon headings
    - search in code to see if we still use, it not then delete
- Icon headings simple
    - come back to this later
- Messages
    - but all banners in one page
    - put big message into banners page
    - inverses
        - figure out how to show them
    - show small message in banners page
- Option components
    - research this
- Overlay
    - Have a screenshot
    - Or build table into example
- Page Controls and Tabs
    - Elections page tab
- Pagination
    - Implement datatable pagination to latest updates
- Search bar
    - don’t use anymore
    - think about having search page
- Search results
    - come back to this
- Side nav
    - show both on same page, but explain one jumps down and one takes you to another page/section
- Side bar
    - call side nav (left side), side bar (right side)
    - think about renaming
- Simple table
    - show all on same page
    - add financial table
    - complex tables
    - have all tables on same section?
- Slabs
    - maybe show examples of stuff to put in it
- Tag
    - add secondary tag thats used on latest updates
- Tooltip
  - come back to this

**Comment by AmyKort** [comment]
Is this one we can close?

**Comment by jenniferthibault** [comment]
Closing in favor of more specific issues in the pattern library repo: https://github.com/18F/fec-pattern-library
