### ISSUE TITLE
Train 18F and FEC team to run and edit pattern library locally

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#735]
So that the FEC team can start interacting with, testing, and giving feedback on the pattern library (and so that we can expand the team members able to work on it) provide training on how to run it locally and contribute changes.

**Completion criteria**
- [ ] Training is held
- [ ] Readme setup docs are improved

**Comment by PaulClark2** [comment]
[removed list of people]

**Comment by JonellaCulmer** [comment]
Scheduled for 10/2 1-2pm. 

https://docs.google.com/document/d/1MOt4Gnll4Vgx6SkCCclrcXiOFBHEybwFD80S-2pUQmM/edit
