### ISSUE TITLE
Typeahead UI tweaks for greater clarity

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#738]
It seems that some users see the typeahead suggestions as a definitive set of results for a given search, rather than the top X matches for a given term. We should consider minor UI or microcopy changes to make it clear that if you don't see the results in there it might still be worth it to submit the search. 

cc @jenniferthibault

**Comment by jenniferthibault** [comment]
Closing since it's gone stale. Will reopen if concerns surface in a pattern
