### ISSUE TITLE
Link citations in glossary terms to source documents

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#760]
So that people looking up a term in the glossary can easily reference the source of the citation, add links to cited resources such as regulations, statutes, and AOs.

<img width="297" alt="screen shot 2017-08-16 at 11 19 14 am" src="https://user-images.githubusercontent.com/11636908/29370904-c6821c60-8274-11e7-823d-3fba85f5b803.png">

Completion criteria
- [ ] Connect citations to sources for all definitions
- [ ] Make sure link underline style is visible against the dark background (use `$aqua`, hat tip to @patphongs 🎩 )

(cc @dorothyyeager for 👀 )

**Comment by dorothyyeager** [comment]
Just a note to say the basic link coding and pull request for this has been done, although I'm not sure about the aqua part which I only now just picked up on. Pull request is at https://github.com/18F/fec-style/pull/765.

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/fec-style/pull/765
