### ISSUE TITLE
Move to a new CI/CD system

### ISSUE THREAD

**Issue by hollyallen** [18F/fec-style#767]
This repository has been using Travis CI, however access to Travis CI is now turning off. When you need to use this repository again, convert it to a CI/CD system which is in the ITSP such as Circle CI.

**Comment by AmyKort** [comment]
@xtine Is this issue still relevant?

**Comment by xtine** [comment]
@amykort: issue is no longer relevant. Once eregs is migrated off fec-style dependencies, then we can archive this repo as it won’t be used anymore.

**Comment by AmyKort** [comment]
Thanks!
