### ISSUE TITLE
Change font of tab styling

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#81]
Current:

<img width="433" alt="screen shot 2015-09-10 at 8 27 59 pm" src="https://cloud.githubusercontent.com/assets/11636908/9804320/76c27252-57fa-11e5-9cf6-8ac2717adfa8.png">

Proposed:
<img width="367" alt="screen shot 2015-09-10 at 8 28 27 pm" src="https://cloud.githubusercontent.com/assets/11636908/9804332/8f46bc48-57fa-11e5-9dd7-8832b8228e5f.png">

Filing so that I don't lose track of it. To be clear, the size of the tabs shouldn't change, I'm just using screenshots from different places.

**Comment by noahmanger** [comment]
:+1:

**Comment by noahmanger** [comment]
Done
