### ISSUE TITLE
Create a flexible toggle button/slider for mobile

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#82]
Current:
<img width="343" alt="screen shot 2015-09-10 at 8 30 29 pm" src="https://cloud.githubusercontent.com/assets/11636908/9804357/d8845064-57fa-11e5-96bd-a01abb6b8e48.png">

**Comment by noahmanger** [comment]
I just stacked em on smaller screens. This work for you?

![screen shot 2015-09-18 at 2 28 06 pm](https://cloud.githubusercontent.com/assets/1696495/9971552/8ecd03e0-5e11-11e5-8790-1a48211b93fd.png)

**Comment by jenniferthibault** [comment]
Would you mind rounding the corners to match? Otherwise, works for me!

From a words perspective, do you think this needs to be clarified? I'm not quite sure what to expect when I select "Compare by Employer"... whose employer? The candidate's employer? The committee's employer? Same for "Occupation"

I think what we're getting at is "Contributor employer" and "Contributor Occupation" , right?

**Comment by noahmanger** [comment]
Will round the corners. And yeah, I agree the language needs to be sharpened. Contributor employer and Contribtor occupation might work great.
