### ISSUE TITLE
On contributions tables, change hyphen to en-dash without spaces

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#83]
<img width="675" alt="screen shot 2015-09-10 at 8 36 23 pm" src="https://cloud.githubusercontent.com/assets/11636908/9804455/b0940d96-57fb-11e5-9660-10bfa7f0fe3c.png">

Categories currently read:
$200.01 - $499.99

Should read:
$200.01–$499.99

I wonder if it could even be:
$200.01–499.99  ?

**Comment by emileighoutlaw** [comment]
Good catch on that – (en) dash and spaces, Jen! My gut for readability is that  it's better to keep both dollar signs in. 

(I don't have my AP style book in front of me, so I'm not sure if we can grammatically get away with  eliminating one of the dollar signs, but I can check when I'm back in the office Monday, if you feel strongly about this! Let me know!)

**Comment by emileighoutlaw** [comment]
Has been resolved. Doing a last QA sweep now.
